// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `account.oauth.cancel`. Was an inline
 * `json!({ "cancelled": .. })`. False means there was no in-flight flow.
 */
export type AccountOAuthCancelResult = { cancelled: boolean, };
