// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCounts } from "./TokenCounts";

/**
 * Response from session:activity_summary. The backend also writes
 * `term:ambient_summary` to block meta. `tokens` is `None` when the request
 * was rejected as stale-on-arrival or the underlying call failed/was
 * cancelled — callers should only record usage when it's `Some`.
 */
export type ActivitySummaryResult = { summary: string, tokens?: TokenCounts, };
