// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCounts } from "./TokenCounts";

/**
 * Response from session:activity_summary. The backend stores the title in
 * `term:ambient_summary` itself (`ambient::title`); `summary` is the title this
 * call stored, empty when it left the title as it was. `tokens` is `None` when
 * the request was rejected as stale-on-arrival or the underlying call failed or
 * was cancelled — callers should only record usage when it's `Some`.
 */
export type ActivitySummaryResult = { summary: string, tokens?: TokenCounts, };
