// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A content blob attached to a agent definition (e.g. "instructions").
 */
export type AgentContent = { agent_id: string, content_type: string, content: string, updated_at: number, };
