// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSkillImport = { name: string, trigger: string, skill_type: string, description: string, content: string, };
