// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `agentdefcreatefromtemplate`. The frontend uses
 * `definition_id` to launch the freshly-created agent.
 */
export type AgentDefCreateFromTemplateResult = { definition_id: string, 
/**
 * Echoed back so the caller's launch step doesn't need to
 * re-thread these — they flow through to the launch overrides.
 */
identity_id: string, memory_id: string, };
