// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSessionArchiveResult = { 
/**
 * Empty string when nothing was archived (current zone was empty).
 */
archive_zoneid: string, archived_at_ms: number, };
