// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-defined AI agent in the user's agent-definition catalog.
 */
export type AgentDefinition = { id: string, 
/**
 * Stable, filesystem-safe identifier. Drives working directory,
 * env var keys (AGENTMUX_AGENT_ID), and cross-references.
 * NEVER changes after creation — distinct from `name` which is
 * the renameable display. See
 * docs/specs/SPEC_AGENT_IDENTITY_RESTRUCTURE_2026_04_14.md.
 */
slug: string, name: string, icon: string, provider: string, description: string, working_directory: string, shell: string, provider_flags: string, auto_start: number, restart_on_crash: number, idle_timeout_minutes: number, created_at: number, agent_type: string, environment: string, agent_bus_id: string, is_seeded: number, 
/**
 * JSON-encoded per-provider account assignments
 * (`{"github":"acct-id", …}`). Written by the Agent pane's Identity
 * tab (`AgentIdentityPanel`) via `updateagent`, read back by
 * `parseAgentAccounts` and consumed by startup credential
 * resolution. (An older v6 comment called this deprecated in favour
 * of `db_agent_identity_links`; that migration never completed — the
 * JSON blob is still the live store, so the schema flatten keeps the
 * column.)
 */
accounts: string, 
/**
 * Parent definition id (db_agent_definitions.id). Empty string = root
 * definition; non-empty = this agent was forked from another.
 * Added in v6. See spec §Phase 1.
 */
parent_id: string, 
/**
 * Label describing the branch (e.g. `"pr-422-review"`,
 * `"experiment-refactor"`). Empty for root definitions and for
 * branches that didn't set a label. Added in v6.
 */
branch_label: string, 
/**
 * Last-modified timestamp (epoch ms). Set to `created_at` on insert
 * and refreshed on every `agent_def_update`. Schema v2. `0` for
 * rows written before v2 (until next update).
 */
updated_at: number, 
/**
 * Per-user hide flag for seeded templates. `1` = the user clicked
 * "Hide template" on the picker's `+ New from template` tier; the
 * row stays on disk (templates are manifest-managed; deletion would
 * fight re-seed) but the default `listagents` view filters it out.
 * Reset to `0` by the agent-seed re-sync flow for any NEW template
 * id newly added to the manifest, so a fresh template surfaces once
 * even if a same-named one was previously hidden. Schema v3 (Phase
 * 2 of `SPEC_AGENT_PICKER_TWO_TIER_2026_05_24.md` — Q2 Decision Y).
 * User-owned rows (`is_seeded = 0`) MUST stay at `0` here; their
 * removal path is `deleteagent`, not hide.
 */
user_hidden: number, 
/**
 * Docker image to use when `agent_type == "container"`.
 * e.g. `"ghcr.io/agentmuxai/agent-claude:latest"`.
 * Empty string for host agents. Schema v6.
 */
container_image: string, 
/**
 * JSON array of volume mount specs for container agents.
 * Each element is a string in Docker bind-mount format:
 * `"source:target"` or `"source:target:options"`.
 * Empty JSON array (`"[]"`) for host agents. Schema v6.
 */
container_volumes: string, 
/**
 * Stable Docker container name managed by the server.
 * Set to `"agentmux-<slug>"` on first container spawn;
 * empty for host agents. Schema v6.
 */
container_name: string, 
/**
 * Explicit per-agent opt-in to the CLI's global (ambient) login when no
 * oauth-class account resolves at spawn time. `0` (default) = spawn
 * FAILS when an oauth-class provider the agent is supposed to have
 * credentials for is missing/unresolvable ("fail by default"); `1` =
 * the spawn proceeds WITHOUT injecting a config dir so the CLI reads
 * the user's global login (e.g. `~/.claude`) — surfaced via the
 * `identity.spawn.ambient:` log line, never silent. Toggled from the
 * Agent setup modal's Accounts tab. Schema v12; the m0017 migration
 * grandfathers pre-existing linkless agents to `1`. Layer 3 of
 * SPEC_ACCOUNT_DELETE_DEAUTH_LAYERS_2_4_2026_07_14.md (§2.2-§2.4).
 */
use_ambient_login: number, 
/**
 * Redirects this agent's harness (CLI) at a non-default model vendor
 * backend — e.g. `"https://my-proxy.example.com"` for a `claude`-provider
 * agent, injected into `ANTHROPIC_BASE_URL` at spawn time. Empty string
 * (default) = use the harness's default vendor endpoint. Only settable
 * when the resolved provider declares `ProviderConfig::base_url_env_var`
 * (validated in `agent_define_core`) — see docs/specs for the harness
 * vs. model-vendor concept this formalizes. Schema v15. Channel-local:
 * does not currently survive a cross-channel reopen of the same agent
 * (known limitation, not wired into the registry mirror).
 */
model_vendor_base_url: string, 
/**
 * Per-agent opt-in: when non-zero, a running Warden Supervisor watcher
 * agent is permitted to auto-continue this agent's session on
 * turn-end (subject to a server-side consecutive-nudge ceiling).
 * Default 0 = opt-in required, same fail-by-default posture as
 * `use_ambient_login`. Schema v17. Toggled from the Warden Supervisor
 * panel. See
 * docs/analysis/ANALYSIS_WARDEN_AUTO_CONTROLLER_CONTINUATION_WATCHER_2026_08_12.md.
 */
auto_continue_enabled: number, 
/**
 * The agent's own dedicated ABF bundle (`db_bundles.id`). Distinct from
 * `AgentInstance.memory_id` (a specific *launch*'s bundle, which can
 * still be pointed at a different bundle on purpose — this is just the
 * default a launch inherits when it doesn't override). Empty string =
 * not yet provisioned (legacy row predating this field, or a definition
 * awaiting `m0021`'s backfill). Stored in `db_agents.default_memory_id`
 * — a separate column from `db_agents.memory_id`, which is the
 * instance-scoped field this doc paragraph opens by distinguishing it
 * from. Schema v19; the two-column split dates to
 * ARCHITECTURE_MANDATORY_ABF_RETHINK_2026_08_14.md §3.1.
 */
memory_id: string, 
/**
 * This agent's own disclosure policy for an incoming cross-tier
 * `transcript_request` jekt (`muxspect` Phase B/C — LAN/WAN
 * conversation visibility, `SPEC_MUXSPECT_CROSS_TIER_CONVERSATION_VISIBILITY_2026_08_21.md`,
 * jekt tier rules confirmed in `SPEC_JEKT_TRANSCRIPT_REQUEST_TIER_RULES_2026_08_22.md`).
 * One of `"private"` (default — auto-deny, fail-closed), `"trusted_peers"`
 * (auto-approve only a requester in `db_conversation_trust_grants`), or
 * `"ask"` (force human escalation, never auto-respond). Schema v26.
 * Channel-local only, like `model_vendor_base_url`/`memory_id` above —
 * deliberately NOT added to `DefinitionRecordV1`'s cross-channel wire
 * format yet; a cross-channel-reopened agent starts back at the safe
 * `"private"` default rather than carrying a stale value. Known
 * limitation, not a bug — same precedent as those two fields.
 */
conversation_visibility: string, };
