// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `agent:session:read`. `content == None` means no zone /
 * snapshot exists for this definition (NOT an error — fresh agent).
 */
export type AgentSessionReadResult = { content?: string, 
/**
 * `modts` of the `output.state.json` file in the agent's
 * `:current` zone, if it exists.
 */
modts?: number, };
