// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row per running/historical execution of an agent definition.
 * `block_id` / `session_id` / `github_context` are modelled as empty
 * strings on the wire rather than `Option<String>` to match the
 * existing schema conventions (`NOT NULL DEFAULT ''`). Callers
 * that need structured absence can use `.is_empty()`.
 */
export type AgentInstance = { id: string, definition_id: string, parent_instance_id: string, block_id: string, session_id: string, status: string, 
/**
 * JSON-encoded `GitHubContext`, or empty string.
 */
github_context: string, started_at: number, ended_at: number, created_at: number, 
/**
 * Legacy Identity-bundle id column — `db_identity_bundles` was
 * dropped in Phase 4c of SPEC_PRESET_TO_BUNDLE_REFACTOR_2026_07_02.md.
 * The launch modal now writes an account_id here instead; credential
 * resolution and display names both go through
 * `db_agent_identity_links`/`db_accounts`. Empty string means
 * "ambient creds, no env-var injection."
 */
identity_id: string, 
/**
 * FK to `db_bundles.id`. Empty string means "use the blank
 * singleton" (= vanilla CLI, no instructions). Set at
 * instantiation via the launch modal's Bundle dropdown.
 */
memory_id: string, 
/**
 * User-chosen instance name (becomes `AGENTMUX_AGENT_ID` in the
 * spawn env). Empty for pre-v8 rows and for un-named launches.
 * Drives the "Continue agent" dropdown in the launch modal.
 */
instance_name: string, 
/**
 * Absolute path returned by `allocate_agent_workdir` at spawn.
 * Stored explicitly (rather than re-derived from the slug at
 * continue-time) so the continue flow is robust against
 * slug-rule changes and user-side renames.
 */
working_directory: string, 
/**
 * Soft-delete flag for the "Forget agent" affordance. Hidden
 * rows stay on disk for audit + recovery.
 */
display_hidden: boolean, };
