// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the agent's archive list. Mirrors `RecentSessionRow`
 * preview shape so the frontend can reuse the same row component.
 */
export type AgentArchiveRow = { archive_zoneid: string, archived_at_ms: number, 
/**
 * First user_message in the archived `output.state.json` (up to
 * 240 chars, newlines collapsed). Empty when unreadable.
 */
preview: string, 
/**
 * Total `nodes.length` from the archived snapshot. 0 when
 * unreadable / missing.
 */
node_count: number, };
