// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The remembered runtime after the command: the same JSON object, or `""`
 * when the agent has none (or is unknown or a template).
 */
export type AgentLastRuntime = { runtime: string, };
