// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Junction row: which identity an agent uses for a given provider.
 */
export type AgentIdentityLink = { agent_id: string, account_id: string, provider: string, };
