// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent registration record.
 *
 * `#[ts(type = "number")]` on the u64 timestamps: ts-rs maps 64-bit integers
 * to `bigint`, which is not assignable to `number` in TypeScript and would
 * break every consumer that treats these as JS millisecond timestamps. See
 * the same annotation on `BrowserBookmark::created_at` (PR #3293).
 */
export type AgentRegistration = { agent_id: string, block_id: string, tab_id?: string, 
/**
 * Identity M2: the agent's UID (`db_agents.id`) when the server knew it
 * at registration — the key the registry is now organised by. Absent
 * for blocks with no row (quick-launch panes, PTY shells), which are
 * reachable by name only. Same present-or-omitted treatment as `tab_id`.
 */
uid?: string, registered_at: number, last_seen: number, 
/**
 * Process-wide unique nonce of the persistent-controller spawn this
 * registration belongs to; 0 = not recorded (HTTP register handler,
 * PTY shell auto-register). Real nonces are always ≥ 1, drawn from a
 * single srv-wide counter (`persistent::next_registration_nonce`) —
 * NOT the controller-local spawn generation, which restarts at 1
 * for a replacement controller (`resync_controller`) and could
 * collide across controller instances for the same block (codex P1
 * on PR #2500). Lets the exit-handler's cleanup compare-and-remove
 * instead of blindly wiping a fallback respawn's (or replacement
 * controller's) fresh registration (issue #2363).
 */
registration_nonce: number, };
