// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `agentdefhide` / `agentdefunhide`. `ok = true` when a
 * row was updated; `false` when the id didn't match any row. (A row
 * that exists but isn't a template returns an RPC-level error, not
 * `ok: false` — the caller should never have been able to send that
 * id from the picker UI.)
 */
export type AgentDefHideResult = { ok: boolean, };
