// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An append-only session history entry for a agent definition.
 */
export type AgentHistory = { id: number, agent_id: string, 
/**
 * Local date the entry was appended, `YYYY-MM-DD`. Set by the server, not
 * by the caller -- `appendagenthistory` takes only `agent_id` + `entry`.
 */
session_date: string, entry: string, timestamp: number, };
