// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file to write as part of agent config.
 */
export type AgentConfigFile = { path: string, content: string, };
