// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSkillImport } from "./AgentSkillImport";

export type AgentDefinitionImport = { id: string, name: string, icon: string, description: string, provider: string, shell: string, working_directory: string, agent_bus_id: string, agent_type: string, environment: string, restart_on_crash: boolean, content: { [key in string]?: string }, skills: Array<AgentSkillImport>, };
