// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `getwaveairatelimit`.
 *
 * AgentMux does not rate-limit, so every field is a fixed placeholder and
 * `unknown` is always true. The shape exists because the renderer inherited a
 * rate-limit widget that expects it; generating it at least means the
 * placeholder and the type that describes it cannot drift apart.
 */
export type AiRateLimitResult = { req: number, reqlimit: number, preq: number, preqlimit: number, resetepoch: number, unknown: boolean, };
