// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of AskSideQuestionCommand. `request_id` is the correlator the
 * caller uses to scope its `EVENT_BTW_ANSWER_CHUNK` subscription:
 * `block:<block_id>:btw:<request_id>`.
 */
export type AskSideQuestionResult = { request_id: string, };
