// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A processed attachment. `id` is the hex SHA-256 of the original bytes.
 */
export type AttachmentInfo = { id: string, 
/**
 * Display name. Not part of the stored content — the same bytes can
 * arrive under different names — so it is empty from `attachments.info`.
 */
name: string, mime: string, bytes: number, width: number, height: number, 
/**
 * What the agent receives (downscaled, metadata stripped).
 */
send_mime: string, send_bytes: number, send_width: number, send_height: number, 
/**
 * Set when the original was an animated GIF (only the first frame is sent).
 */
first_frame_only: boolean, };
