// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `attachment:failed` event payload.
 */
export type AttachmentFailedEvent = { batch_id: string, index: number, 
/**
 * `unsupported` | `heic` | `too_large_dimensions` | `decode` | `io` | `cancelled`
 */
code: string, error: string, };
