// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentPending } from "./AttachmentPending";
import type { AttachmentRejected } from "./AttachmentRejected";

export type AttachmentsIngestResult = { batch_id: string, 
/**
 * Files accepted into the batch, in order. `index` keys every event.
 */
accepted: Array<AttachmentPending>, 
/**
 * Files refused before processing (limits, unreadable).
 */
rejected: Array<AttachmentRejected>, 
/**
 * Always empty since any file can be attached; kept so a frontend from
 * the images-only release still reads the result.
 */
non_images: Array<string>, 
/**
 * Sum of `accepted[].bytes`.
 */
total_bytes: number, 
/**
 * The limits applied, so the UI can show "N / max".
 */
max_files: number, max_total_bytes: number, };
