// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentInfo } from "./AttachmentInfo";

export type AttachmentsInfoResult = { 
/**
 * One entry per requested id that is still in the store. Ids that were
 * swept by retention are simply absent.
 */
items: Array<AttachmentInfo>, };
