// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentRejected = { path: string, name: string, 
/**
 * `too_many` | `too_large` | `not_found` | `unreadable`
 */
code: string, reason: string, };
