// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackgroundTaskView = { id: string, block_id: string, label: string, 
/**
 * Always present, carries null when unknown -- no skip_serializing_if.
 */
pid: number | null, started_at_ms: number, 
/**
 * A closed set the frontend branches on; ts-rs would emit a bare
 * `string` for a `&'static str` and drop the union the hand-written
 * declaration carried.
 */
status: "running" | "done" | "error" | "stopped", last_seen_ms: number, ended_at_ms: number | null, };
