// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime status of a block controller, sent to the UI.
 */
export type BlockControllerRuntimeStatus = { blockid: string, version: number, shellprocstatus?: string, shellprocconnname?: string, shellprocexitcode: number, 
/**
 * A durable SSH pane (`durable_ssh`): its shell lives on the host.
 */
durable?: boolean, 
/**
 * Unix timestamp (ms) when the process was spawned; None until first spawn.
 */
spawn_ts_ms?: number, 
/**
 * PID of the controller's own child process. Set by the shell
 * controller, which is the one the UI needs it for: the agent pane's
 * Shell drawer identifies its shell by PID (see
 * docs/specs/SPEC_AGENT_SHELL_DRAWER_INFO_PANEL_2026_09_19.md §4.1).
 * None before the first spawn, and for controllers that don't set it.
 */
shellprocpid?: number, 
/**
 * Program name of that child (`pwsh`, `bash`, …). The process tracker
 * can't supply it — it omits each block's root process by design, and
 * for a shell sub-block the root IS the shell.
 */
shellprocname?: string, 
/**
 * True if this pane is running an agent CLI (e.g. claude, codex, gemini, kimi, openclaw, pi).
 */
is_agent_pane?: boolean, 
/**
 * True if a turn is currently in flight (message sent, no terminating
 * `"result"` event observed yet). For `PersistentSubprocessController`
 * this is the only signal that distinguishes "actively generating a
 * turn" from "process alive, idle between turns" — `shellprocstatus`
 * stays `"running"` for the whole process lifetime either way. Backed
 * by `TurnActivityTracker.active_turn` (see `blockcontroller/health.rs`).
 * Frontend seeds `TurnPhase` from this at mount instead of always
 * defaulting to `Idle` — see
 * docs/specs/REPORT_AGENT_PANE_STATE_RECONCILIATION_2026_07_07.md
 * Finding 1.
 */
turn_active?: boolean, };
