// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from blockfile:read_state. `content` is the raw file bytes
 * as a UTF-8 string, or null if the sidecar does not exist.
 */
export type BlockfileReadStateResult = { content: string | null, };
