// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where `block.reveal` reveals a block — also the `block:reveal` payload.
 */
export type BlockRevealEvent = { block_id: string, tab_id: string, 
/**
 * The open window showing the block's workspace; only it acts.
 */
window_id: string, };
