// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from blockfile:line_count.
 */
export type BlockfileLineCountResult = { count: number, };
