// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Block (node) kinds for Phase 1. Phase 2 adds Function, Loop, Parallel,
 * Router, Subdrone. Stored as `kind` field on `FlowNode.data`.
 */
export type BlockKind = "agent" | "condition" | "api" | "response" | "variables";
