// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from blockfile:write_state.
 */
export type BlockfileWriteStateResult = { bytes_written: number, };
