// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlockRevealResult = { 
/**
 * The block exists and its workspace is open in a window, which was
 * told to reveal it (`block:reveal`).
 */
found: boolean, 
/**
 * That window (a connected frontend's `Window` oid) — the caller raises it.
 */
window_id?: string, };
