// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserBookmark } from "./BrowserBookmark";

/**
 * `bookmarks.list` / `bookmarks.set` response — both answer with the full
 * list, so they share one type. Was an anonymous `json!({"bookmarks": ..})`
 * before this existed to name it for the RPC bindings generator.
 */
export type BookmarksResult = { bookmarks: Array<BrowserBookmark>, };
