// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserProfile } from "./BrowserProfile";

/**
 * Every `browser_profiles.*` command answers with the whole list; `created`
 * is the new profile, from `browser_profiles.create`
 * (SPEC_BROWSER_PANE_PROFILES_MENU_2026_10_09.md §6).
 */
export type BrowserProfilesResult = { profiles: Array<BrowserProfile>, created?: BrowserProfile, };
