// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserProfile = { 
/**
 * Stable id, `[a-z0-9-]`, used in `browser:identity` (`profile:<id>`)
 * and the host's profile folder. Never reused.
 */
id: string, name: string, 
/**
 * `#rrggbb`: the profile's colour on its button and tabs.
 */
color: string, created_at: number, 
/**
 * "Agents may use it" (Settings → Browser): an agent's `OpenBrowser` may browse as
 * it. Off until the user switches it on.
 */
agents_allowed: boolean, };
