// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleImportUnresolvedRequirement } from "./BundleImportUnresolvedRequirement";
import type { BundleImportWidgetResult } from "./BundleImportWidgetResult";

/**
 * Response for `bundle.import.commit`.
 */
export type BundleImportCommitResponse = { 
/**
 * What became of each widget the commit was asked to install.
 */
widgets: Array<BundleImportWidgetResult>, bundle_id: string, imported_skill_ids: Array<string>, skipped_skills: Array<string>, resolved_requirement_ids: Array<string>, unresolved_requirements: Array<BundleImportUnresolvedRequirement>, warnings: Array<string>, warnings_truncated: boolean, };
