// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One in-memory file of an unpacked bundle, for the `files` input mode.
 */
export type BundleImportFileEntry = { path: string, content: string, };
