// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One skill directory offered for selection.
 */
export type BundleImportSkillPreview = { 
/**
 * Stable selection key — never the (possibly truncated) slug.
 */
source_dir: string, slug: string, description: string, 
/**
 * Produced by `classify_skill_collision`, which returns a
 * `&'static str` from a closed set. ts-rs emits a bare `string` for a
 * Rust `String`, which would silently drop the union the hand-written
 * declaration carried, so the override keeps it.
 */
collision: "none" | "name_conflict" | "duplicate_in_bundle", };
