// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One project-instruction snapshot (`CLAUDE.md` and friends) carried by the
 * bundle.
 *
 * NOTE: the preview response has always included this list, but the
 * hand-written `BundleImportPreviewResponse` in `srv-types.d.ts` did not
 * declare it and no frontend code reads it — so it has been shipping on the
 * wire, invisible to the client. Generating the response type surfaces it
 * rather than silently dropping it; whether the UI should use it is a
 * product question, not a refactor one.
 */
export type BundleImportProjectInstructionPreview = { 
/**
 * Working-directory-relative path on the SOURCE machine.
 */
path: string, 
/**
 * Where the snapshot lives inside the bundle.
 */
file: string, content_hash: string, 
/**
 * `"agentmux"` or `"foreign"`, verbatim from the manifest — deliberately
 * not narrowed to a union, because an unrecognized value from a
 * future/hand-written bundle must survive to the UI as-is.
 */
owner: string, content_preview: string, content_truncated: boolean, content_total_chars: number, };
