// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleImportMcpServerDisplay } from "./BundleImportMcpServerDisplay";

/**
 * One MCP server offered for selection. Carries only `display`, never the
 * full config — a bundle's server config can hold secrets.
 */
export type BundleImportMcpServerPreview = { 
/**
 * Stable selection key.
 */
source_path: string, display: BundleImportMcpServerDisplay, };
