// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Bundle — the agent's personality and capability stack.
 * Provider, model, instructions, and JSON-encoded arrays of context
 * files / MCP servers / skills. Agent definitions shadow-migrate into this
 * table during the v7 migration.
 */
export type Bundle = { id: string, name: string, description: string, is_blank: boolean, 
/**
 * Global bundles are injected into every agent's CLAUDE.md at launch,
 * regardless of per-agent memory selection. Managed in the Armory
 * (Identity & Bundle hamburger modal). Seeded from workspace-wide rule sets.
 */
is_global: boolean, 
/**
 * "claude" | "codex" | "gemini" | empty string
 */
provider: string, model: string, instructions: string, 
/**
 * JSON-encoded object of `{provider_id: content}` — additive,
 * harness-scoped instruction variants alongside the flat
 * `instructions` column above (which keeps meaning "default"). ABF v0.2
 * §2.2; see SPEC_ABF_V0_2_PROVIDER_AWARE_COMPONENTS_AND_NATIVE_MEMORY_2026_08_10.md.
 */
instructions_by_provider: string, 
/**
 * JSON-encoded array; the renderer types it as `[{path, content}]`.
 */
context_files: string, 
/**
 * JSON-encoded array of MCP server configs.
 */
mcp_servers: string, 
/**
 * JSON-encoded array of skill IDs.
 */
skills: string, 
/**
 * Explicit ordering within the Armory global bundles. Lower sorts
 * first; this is the order sections inject into CLAUDE.md at launch.
 * Only meaningful for `is_global` bundles; 0 for the rest. Owned by the
 * `reorderglobalbrain` RPC — `bundle_upsert` never overwrites it
 * on conflict, so editing a bundle via the regular form keeps its place.
 */
sort_order: number, 
/**
 * AgentMux-controlled, highest-priority Global Bundle tier — always
 * also `is_global`, injected first in `format_global_bundle_block`'s
 * output with explicit override wording. Writable ONLY through
 * `bundle_upsert_system`/`bundle_delete_system` — the
 * generic `bundle_upsert`/`_delete`/`_reorder` all refuse to
 * touch a row with this set. See
 * docs/specs/SPEC_GLOBAL_MEMORY_SYSTEM_TIER_2026_08_24.md.
 */
is_system: boolean, created_at: number, updated_at: number, };
