// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `*.md` context file offered for selection in the preview.
 */
export type BundleImportContextFilePreview = { 
/**
 * 0-based index within this parse — the stable selection key
 * `include_context_files` uses at commit. Never the display path, which
 * may be truncated.
 */
id: number, display_path: string, size_bytes: number, };
