// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One widget a bundle import was asked to install.
 */
export type BundleImportWidgetResult = { id: string, 
/**
 * `waiting` (installed, waiting for the user's approval), `unchanged`
 * (already installed at these files), or `failed`.
 */
status: string, error?: string, };
