// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The deliberately-narrow view of an MCP server config shown in the preview.
 * Both fields are genuinely nullable rather than optional: `mcp_server_display`
 * writes an explicit JSON `null` when the key is absent from the config, so
 * the key is always present on the wire.
 */
export type BundleImportMcpServerDisplay = { name: string | null, command: string | null, };
