// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One skill selected for import, optionally renamed to dodge a collision.
 */
export type BundleImportSkillSelection = { 
/**
 * Matches `BundleImportSkillPreview::source_dir` — the stable key, not
 * the slug.
 */
source_dir: string, import_as?: string, };
