// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One account requirement the bundle declares, with how many local accounts
 * match it. `resolved` is exactly `match_count == 1` — zero means nothing to
 * bind, more than one means the choice is ambiguous.
 */
export type BundleImportRequirementPreview = { id: string, provider: string, env: string, resolved: boolean, match_count: number, };
