// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the model dropdown. `id` is the concrete `--model` value the
 * CLI accepts (e.g. `claude-sonnet-5`); `display_name` is the label to show
 * (e.g. "Claude Sonnet 5"), taken verbatim from the API.
 */
export type CatalogModel = { id: string, display_name: string, };
