// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result from CheckCliAuthCommand
 */
export type CheckCliAuthResult = { authenticated: boolean, email: string | null, auth_method: string | null, 
/**
 * Raw stdout from auth check command
 */
raw_output: string, };
