// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resolved shared-provider-dir's `CLAUDE.md` path + content,
 * read-only. `claude_dir` is injected (not resolved internally) so this
 * is testable against a tempdir. `content: None, exists: false` for a
 * genuinely missing file (the common case — no AgentMux-spawned Claude
 * agent on this host has one today, confirmed 2026-08-24) — real I/O
 * errors (permission denied, etc.) still propagate as `Err`, not
 * silently folded into "missing."
 */
export type ClaudeGlobalConfig = { path: string, 
/**
 * Genuinely `string | null`, not an optional property: a plain
 * `Option<String>` with no `skip_serializing_if`, so the key is always
 * present and carries `null` when the file does not exist. That
 * distinction is load-bearing here — `exists: false` with
 * `content: null` is the meaningful "no file" answer, not an absent key.
 */
content: string | null, exists: boolean, };
