// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `browser_profiles.list`: no arguments (a struct, so `{}` deserializes).
 */
export type CommandBrowserProfilesListData = Record<string, never>;
