// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `browser_profiles.update`: rename, recolour, and/or switch "Agents may use
 * this profile".
 */
export type CommandBrowserProfileUpdateData = { id: string, name?: string, color?: string, agents_allowed?: boolean, };
