// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `containerimagecheck`. An empty `image` means the default image.
 */
export type CommandContainerImageCheckData = { image: string, };
