// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `agent:session:archive`. Snapshots `agent:<defId>:current`
 * into `agent:<defId>:archive:<now_ms>` then clears the current zone.
 * Returns the archive zoneid (empty if no-op).
 */
export type CommandAgentSessionArchiveData = { definition_id: string, };
