// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `listmemories`. The handler ignores its payload, but this must be
 * a struct rather than `()`: the stub defaults the argument to `{}`, and serde
 * deserializes `()` ONLY from JSON `null`, so a unit Req would reject every
 * real call at runtime while passing every CI gate (the `bookmarks.list` bug).
 */
export type CommandListBundlesData = Record<string, never>;
