// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `agent:session:list_archives`.
 */
export type CommandAgentSessionListArchivesData = { definition_id: string, limit: number, };
