// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for fleet.broadcast. `targets` are block ids (Swarm's native
 * per-agent selection unit) — resolved server-side to each block's
 * registered agent name before delivery.
 */
export type CommandFleetBroadcastData = { targets: Array<string>, message: string, };
