// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `globalmemory:import` — source `index` of the list `list_id` from
 * `globalmemory:import_sources`.
 */
export type CommandGlobalMemoryImportData = { list_id: string, index: number, };
