// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for session:next_prompt_suggestion — predict a plausible next
 * user message via Haiku, routed through the Ambient Model Call gateway
 * (same shape as CommandActivitySummaryData). See
 * docs/specs/SPEC_AMBIENT_GHOST_TEXT_NEXT_PROMPT_2026_07_03.md.
 */
export type CommandNextPromptSuggestionData = { block_id: string, 
/**
 * Caller's generation for this block — see CommandActivitySummaryData's
 * doc comment for the wall-clock-vs-remount rationale (identical here).
 */
generation: number, };
