// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `getclaudeglobalconfig`. Same reasoning as
 * `CommandListBundlesData` — read-only, no parameters, but still not `()`.
 */
export type CommandGetClaudeGlobalConfigData = Record<string, never>;
