// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for blockfile:write_state — atomically write a sidecar JSON
 * file for a block. Uses tmp + fsync + rename to guarantee partial
 * writes never surface to readers.
 */
export type CommandBlockfileWriteStateData = { block_id: string, filename: string, content: string, };
