// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandGlobalMemoryDiffData = { 
/**
 * Both versions must belong to this entry.
 */
id: string, from_version_id: string, to_version_id: string, };
