// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for session:archive — compress and archive a session's FileStore output.
 */
export type CommandSessionArchiveData = { block_id: string, };
