// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `remotehelperremove`: remove AgentMux's helper from the SSH host
 * `connection`, once the user confirms in the window of pane `blockid`
 * (SPEC_REMOTES_PANE_2026_10_05.md §4.9).
 */
export type CommandRemoteHelperRemoveData = { connection: string, blockid: string, };
