// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConfigFile } from "./AgentConfigFile";

/**
 * Data for WriteAgentConfigCommand — write config files atomically.
 */
export type CommandWriteAgentConfigData = { 
/**
 * Agent working directory where files are written.
 */
working_dir: string, 
/**
 * Files to write (path relative to working_dir, content).
 */
files: Array<AgentConfigFile>, 
/**
 * When true, treat `working_dir` as an auto-generated instance
 * path eligible for `<base>-N` collision resolution. When false
 * (user-specified `agent.working_directory` like `~/projects/X`),
 * write into the path as-is — no rewrite, no suffixing. The
 * frontend sets this based on whether it constructed the path
 * itself or pulled it from the agent definition.
 */
auto_allocate: boolean, 
/**
 * The agent's kind, as the block's `agentMode` carries it (`"host"`,
 * `"standalone"` or `"container"`). Decides which Operator Config
 * entries the startup file gets
 * (`operator_config_seed::global_bundles_for_agent`). Absent from an
 * older frontend: treated as a host agent, the default kind.
 */
agent_type?: string, };
