// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `bookmarks.list` request — no arguments, but deliberately a struct rather
 * than `()`. Serde deserializes `()` ONLY from JSON `null`, and the frontend
 * stub sends `{}`, so a unit Req makes every list call fail at runtime with
 * "invalid type: map, expected unit" — invisible to the compiler and to any
 * test that does not exercise the real payload (codex P1 on PR #3293). An
 * empty struct accepts `{}` and ignores unknown keys, matching the previous
 * untyped handler's behaviour of ignoring `data` entirely.
 */
export type CommandBookmarksListData = Record<string, never>;
