// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for AgentAnswerCommand — an AskUserQuestion answer delivered back to
 * the running agent CLI via the Agent SDK control protocol (a `control_response`
 * carrying `updatedInput.answers`). Spec:
 * docs/specs/SPEC_AGENT_CONTROL_PROTOCOL_2026_06_15.md.
 */
export type CommandAgentAnswerData = { blockid: string, 
/**
 * The `AskUserQuestion` tool_use id the answer responds to (correlates with
 * the parked `can_use_tool` control_request).
 */
tool_use_id: string, 
/**
 * The user's selections as a JSON object mapping each question's text to the
 * chosen option label (a `[labels]` array for multiSelect, or free-text for
 * "Other"). Becomes `updatedInput.answers` in the control_response.
 * `Value` in Rust because it is forwarded verbatim into the control
 * response, but the hand-written declaration knew the shape and keeping it
 * is not a downgrade: question text -> chosen label, an array for
 * multiSelect, or free text for "Other".
 */
answers: Record<string, string | string[]>, };
