// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for AgentStopCommand — stop the running subprocess.
 */
export type CommandAgentStopData = { blockid: string, force: boolean, };
