// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentRef } from "./AttachmentRef";

/**
 * Data for AgentInputCommand — send a follow-up message (re-spawns with --resume).
 */
export type CommandAgentInputData = { blockid: string, 
/**
 * The user's JSON message string.
 */
message: string, 
/**
 * Optional client-supplied id. Echoed back via the
 * `agent-message-accepted` event when this message transitions
 * from queued to running so the frontend can match its pending
 * `PendingMessage` entry and promote it into the conversation
 * document. Absent for pre-existing callers; treated as no-id.
 */
message_id?: string, 
/**
 * Set only by the hidden memory-reinjection turn (see
 * `memory-reinjection-controller.ts` / `crate::ambient::digest::set_hidden_reinjection_active`).
 * Marks the block as suppressed for ambient digest reads
 * (`extract_digest_text`'s next_prompt_suggestion / activity_summary /
 * activity_watcher callers) until the NEXT `AgentInputCommand` for the
 * same block, hidden or not. Authoritative and set at RPC-dispatch
 * time — unlike the marker-text detection inside `extract_digest_text`,
 * it doesn't depend on the reinjection marker line still being inside
 * that function's tail window, which large Personal
 * memory content routinely scrolls past.
 * SPEC_HIDDEN_MEMORY_REINJECTION_AFTER_COMPACTION_2026_09_22.md finding #8.
 */
hidden?: boolean, 
/**
 * A hidden memory re-delivery srv composed (`memorydelivery:compose`):
 * accepting the message, srv writes that delivery's card to the pane.
 */
delivery_id?: string, 
/**
 * Images from the composer's attachment tray, in tray order (ids from
 * `attachments.ingest` / the upload route). The backend appends a
 * numbered `<attached_images>` list of their send-copies to the
 * message, and gives Claude the first ones inline.
 * SPEC_AGENT_PANE_IMAGE_ATTACHMENTS_2026_09_26.md §6.6.
 */
attachments?: Array<AttachmentRef>, 
/**
 * The pane is sending a message it held while turn `joins_turn` (the
 * `agentturn` event's `turn_id`) ran: it joins that turn instead of
 * starting a new one. Set only for that flush, never for a fresh send.
 * SPEC_AGENT_TURN_MODEL_AND_LIVE_STATUS_2026_10_08.md §4.3 (J3).
 */
joins_turn?: number, };
