// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SPEC_PANE_TAB_STRIP_COMPACT_SIZING_AND_RENAME_2026_07_22.md §4 — renames
 * whichever field a fork tab's title actually resolves from.
 */
export type CommandRenameAgentDefinitionTitleData = { id: string, title: string, };
