// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `attachments.info` — look up processed attachments by id (transcript
 * replay, lightbox details).
 */
export type CommandAttachmentsInfoData = { ids: Array<string>, };
