// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for appendagenthistory
 */
export type CommandAppendAgentHistoryData = { agent_id: string, entry: string, };
