// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for SubprocessSpawnCommand — spawn agent CLI for a single turn.
 */
export type CommandSubprocessSpawnData = { blockid: string, tabid: string, cli_command: string, cli_args: Array<string>, working_dir: string, env_vars: { [key in string]?: string }, 
/**
 * The user's JSON message to write to subprocess stdin.
 */
message: string, };
