// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `listhiddentemplates`, which ignores its payload.
 *
 * A struct rather than `()`, and registered as `Option<Self>` rather than
 * `Self`, because the two no-argument encodings both reach the server and
 * serde accepts each from only one of them: the stub calls this with no
 * argument, which the RPC client sends as `{}` (`()` deserializes only from
 * `null`), while a client that omits `data` entirely arrives as `null` (a
 * struct deserializes only from an object). `Option<Self>` takes both.
 */
export type CommandListHiddenTemplatesData = Record<string, never>;
