// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandNativeMemoryRevertData = { agent_id: string, filename: string, target_version_id: string, };
