// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `agent:session:append_output`. Appends a single
 * NDJSON line to `output` in `agent:<definition_id>:current`.
 */
export type CommandAgentSessionAppendOutputData = { definition_id: string, line: string, };
