// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memorydelivery:claim_fallback` — the frontend's hidden memory reinjection
 * asks whether to deliver (SPEC_GLOBAL_MEMORY_DELIVERY_2026_09_27.md §7 P2).
 */
export type CommandMemoryDeliveryClaimFallbackData = { block_id: string, 
/**
 * The reinjection's reason: `compaction` or `fresh_session`.
 */
reason: string, 
/**
 * The compaction boundary's `uuid`: only the block whose own CLI wrote
 * that boundary can deliver; any other block stands down.
 */
boundary_uuid?: string, 
/**
 * A fresh session's time, ms since the epoch: its
 * `agentmux_session_outcome` frame's `timestamp`, which srv wrote. The
 * hook's delivery for that session then counts however late the claim
 * comes, as it does for a fallback deferred behind a long first turn.
 */
event_at_ms?: number, };
