// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for ShellExecCommand — run a shell command in the agent's working directory.
 */
export type CommandShellExecData = { blockid: string, command: string, working_dir: string, };
