// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Matches Go's `CommandBlockInputData`
 */
export type CommandBlockInputData = { blockid: string, inputdata64: string, signame: string, 
/**
 * `Option<Value>` in Rust because this handler forwards it to the PTY
 * layer without inspecting it, but the shape IS known and the hand-written
 * declaration said so. Spelled inline rather than as `TermSize` because
 * that name is still an ambient global -- `#[ts(type)]` bypasses ts-rs
 * dependency tracking, so a named reference would generate an import that
 * resolves to nothing (the `DroneRun.block_states` trap from #3329).
 */
termsize?: { rows: number, cols: number }, 
/**
 * Per-TermViewModel monotonic counter for seq-based input ordering (optional, shell only).
 *
 * The hand-written `CommandBlockInputData` OMITTED this field entirely,
 * so no TypeScript caller could pass it without casting -- the generated
 * type surfaces it.
 */
seq?: number, };
