// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `agentlastruntime`: read, or replace, the Runtime menu choices remembered
 * for agent `id`. Leave `runtime` out to only read; send `""` to forget.
 */
export type CommandAgentLastRuntimeData = { id: string, 
/**
 * A JSON object with any of `permissionMode`, `model`, `effort` (strings).
 */
runtime?: string, };
