// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserBookmark } from "./BrowserBookmark";

/**
 * `bookmarks.set` request — wholesale replace of the saved list.
 */
export type CommandBookmarksSetData = { bookmarks: Array<BrowserBookmark>, };
