// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for searchagenthistory
 */
export type CommandSearchAgentHistoryData = { agent_id: string, query: string, limit: number, };
