// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `gettoolstatus`. The handler ignores its payload, but this must
 * be a struct rather than `()`: the stub calls it with no argument, which the
 * RPC client sends as `{}`, and serde deserializes `()` only from JSON `null`.
 */
export type CommandGetToolStatusData = Record<string, never>;
