// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `agent:session:read`.
 */
export type CommandAgentSessionReadData = { definition_id: string, };
