// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read a layout file and describe what opening it would do, without
 * opening anything (spec §3.5 "Trust": the preview).
 */
export type CommandLayoutPreviewData = { 
/**
 * Absolute path to a `*.agentmux-layout.json` file.
 */
path: string, };
