// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for session:restore — decompress archive back into FileStore.
 */
export type CommandSessionRestoreData = { block_id: string, };
