// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `agent:memory:adoption_list` — the agent's memory folders under its
 * earlier accounts, offered for adoption
 * (SPEC_MEMORY_FOLLOWS_THE_AGENT_2026_09_24.md §2.1.4). Adopting one goes
 * through the host's confirmation window, not an RPC.
 */
export type CommandNativeMemoryAdoptionListData = { agent_id: string, };
