// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.catalog.upsert_for_bundle` — bundle-scoped. Same field rules.
 */
export type CommandMcpCatalogUpsertForBundleData = { bundle_id: string, id: string, name: string, transport: string, config: string, };
