// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Save one window's layout to a `*.agentmux-layout.json` file.
 */
export type CommandLayoutSaveData = { 
/**
 * The window whose tabs are saved.
 */
window_id: string, 
/**
 * The layout's display name, written into the file.
 */
name: string, 
/**
 * Absolute destination, normally from the host's Save dialog. Must end
 * in `.agentmux-layout.json`.
 */
path: string, 
/**
 * Write machine-local resume references (agent session ids). Off by
 * default — spec §3.3.
 */
include_resume?: boolean, };
