// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for AgentInputCommand — send a follow-up message (re-spawns with --resume).
 */
export type CommandAgentInputData = { blockid: string, 
/**
 * The user's JSON message string.
 */
message: string, 
/**
 * Optional client-supplied id. Echoed back via the
 * `agent-message-accepted` event when this message transitions
 * from queued to running so the frontend can match its pending
 * `PendingMessage` entry and promote it into the conversation
 * document. Absent for pre-existing callers; treated as no-id.
 */
message_id?: string, };
