// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for ShellStatusCommand — query a shell's current running state by id.
 */
export type CommandShellStatusData = { shell_id: string, };
