// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of WriteAgentConfigCommand. Returns the final working
 * directory used; callers should compare against the requested
 * `working_dir` and patch `cmd:cwd` (via SetMeta) when they differ
 * so the controller spawns the CLI in the actually-created dir.
 */
export type CommandWriteAgentConfigResult = { working_dir: string, };
