// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `agent:memory:claims` — the memory folders an agent has claimed, for
 * the human "release this folder" action. Releasing goes through the
 * host's confirmation window, not an RPC.
 */
export type CommandNativeMemoryClaimsData = { agent_id: string, };
