// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for blockfile:read_state — read a sidecar JSON file
 * (e.g. `output.state.json`) associated with a block.
 * Spec: docs/specs/SPEC_AGENT_PANE_STATE_PERSISTENCE_2026_05_15.md.
 */
export type CommandBlockfileReadStateData = { block_id: string, 
/**
 * Sidecar filename — e.g. "output.state.json". Resolved within the
 * block's filestore directory; must not contain path separators.
 */
filename: string, };
