// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandCreateAgentInstanceData = { definition_id: string, block_id: string, parent_instance_id: string, 
/**
 * Legacy Identity-bundle id column — `db_identity_bundles` was
 * dropped in Phase 4c of SPEC_PRESET_TO_BUNDLE_REFACTOR_2026_07_02.md.
 * The launch modal now writes an account_id here instead (see
 * agent-model.ts), and this value is used only for opaque
 * same-value filtering (`listrecentsessions`/`listnamedagents`'
 * `identity_id` param) — display names and credential resolution
 * both go through `db_agent_identity_links`/`db_accounts` now.
 * Empty = ambient creds (no env-var injection).
 */
identity_id: string, 
/**
 * FK to db_bundles. Empty = blank singleton. Set by the launch
 * modal's Bundle dropdown.
 */
memory_id: string, 
/**
 * User-chosen instance name (becomes `AGENTMUX_AGENT_ID` in the
 * spawn env). Powers the launch modal's "Continue agent"
 * dropdown. Empty = un-named, won't appear in the dropdown.
 */
instance_name: string, 
/**
 * Absolute working directory path resolved by
 * `allocate_agent_workdir` at spawn time. Stored on the instance
 * row so the continue flow can reuse it without re-deriving the
 * slug.
 */
working_directory: string, };
