// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `remoteadd`: append a `Host` block to the user's `~/.ssh/config`, once
 * the user confirms it in the window of pane `blockid`
 * (SPEC_REMOTES_PANE_2026_10_05.md §4.4). Only `alias` is required.
 */
export type CommandRemoteAddData = { alias: string, hostname: string, user: string, port: string, identityfile: string, proxyjump: string, blockid: string, };
