// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional filter input for `listagents`. When `is_seeded` is set,
 * only definitions whose `is_seeded` column matches are returned
 * (`Some(1)` → templates only; `Some(0)` → user-owned agents only).
 * Absent / `None` = no filter — backward-compatible with callers
 * that pass `{}` or `null`. Phase 1 of the two-tier picker
 * (SPEC_AGENT_PICKER_TWO_TIER_2026_05_24.md).
 *
 * `include_hidden` (Phase 2 — Q2 Decision Y): when `false` (default),
 * templates with `user_hidden = 1` are filtered out. The settings
 * "Hidden templates" surface passes `true` so it can render rows for
 * unhiding; the picker proper omits the flag and gets the filtered
 * default. `include_hidden` only affects templates — user-owned rows
 * never set `user_hidden`, so the flag is a no-op for them.
 */
export type CommandListAgentDefinitionsData = { is_seeded: number | null, include_hidden: boolean, };
