// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `browser_profiles.delete`: the profile, its open tabs and its saved data.
 */
export type CommandBrowserProfileDeleteData = { id: string, };
