// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.upsert` — agent-scoped create-or-update.
 *
 * Every field except `agent_id` and `name` is `#[serde(default)]`, so all of
 * them are omittable on the wire. ts-rs generates them as **required**,
 * because it cannot express an optional property for a non-`Option` field.
 * That is not papered over here: the frontend derives the accurate shape from
 * this generated type with
 * `Pick<…, "agent_id" | "name"> & Partial<Omit<…, "agent_id" | "name">>`,
 * the same approach `BundleUpsertInput` uses. Deriving it rather than
 * hand-listing the optional fields means a new field added below flows
 * through automatically.
 *
 * Changing these to `Option<String>` instead would alter handler behaviour —
 * `default_skill_type` exists so an omitted `skill_type` becomes `"prompt"`,
 * and the rest treat `""` as "not provided".
 */
export type CommandSkillUpsertData = { agent_id: string, id: string, name: string, trigger: string, skill_type: string, description: string, content: string, };
