// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memorydelivery:compose` — srv composes the hidden memory re-delivery the
 * frontend's fallback sends, and keeps its item list (SPEC_CONTEXT_DELIVERY_
 * 2026_09_30.md §3.4 step 2, CD2b).
 */
export type CommandMemoryDeliveryComposeData = { block_id: string, 
/**
 * `compaction` or `fresh_session`.
 */
reason: string, };
