// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandForkAgentDefinitionData = { source_id: string, 
/**
 * When non-empty this becomes the fork's display name directly.
 * When empty, the handler auto-generates "Name #N".
 */
branch_label: string, };
