// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `agentdefhide` / `agentdefunhide`. Phase 2 of the
 * two-tier picker (Q2 Decision Y). The two RPCs share the same shape
 * — the action is encoded in the command name, not the payload.
 */
export type CommandAgentDefHideData = { 
/**
 * id of a seeded definition (must have `is_seeded = 1`).
 */
definition_id: string, };
