// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.upsert` — agent-scoped create-or-update.
 *
 * `id`, `transport` and `config` are all defaulted, so they are omittable on
 * the wire, and ts-rs generates them as **required** (it cannot express an
 * optional property for a non-`Option` field). The frontend derives the
 * accurate shape from this type rather than hand-listing the optional fields;
 * see `McpUpsertInput` in `rpc-api/mcp.ts`.
 *
 * The defaults are load-bearing and are why these cannot become
 * `Option<String>`: an omitted `transport` is `"stdio"` and an omitted
 * `config` is `"{}"`, not `null` — and `config` is parsed as JSON downstream,
 * so a null would be a different failure.
 */
export type CommandMcpUpsertData = { agent_id: string, id: string, name: string, transport: string, config: string, };
