// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for createagent
 */
export type CommandCreateAgentDefinitionData = { name: string, icon: string, provider: string, description: string, working_directory: string, shell: string, provider_flags: string, auto_start: number, restart_on_crash: number, idle_timeout_minutes: number, agent_type: string, environment: string, agent_bus_id: string, };
