// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDefinitionImport } from "./AgentDefinitionImport";

/**
 * Input for importagents
 */
export type CommandImportAgentDefinitionsData = { agents: Array<AgentDefinitionImport>, };
