// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for ShellStopCommand — stop a running persistent shell node by id.
 */
export type CommandShellStopData = { shell_id: string, };
