// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Open a layout file's tabs in an existing window (added as new tabs —
 * nothing that's open is replaced).
 */
export type CommandLayoutOpenData = { path: string, window_id: string, 
/**
 * Start the file's terminal commands. Defaults to whether the file is
 * trusted (see `LayoutPreviewResult::trusted`).
 */
run_commands?: boolean, };
