// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for blockfile:read_range — read a range of lines from a blockfile.
 */
export type CommandBlockfileReadRangeData = { block_id: string, filename: string, offset: number, limit: number, };
