// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandReorderGlobalBundlesData = { 
/**
 * Full ordered list of global bundle ids. Each id's `sort_order`
 * becomes its position in this list.
 */
ids: Array<string>, };
