// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.catalog.upsert_for_bundle` — bundle-scoped. Same field rules again.
 */
export type CommandSkillCatalogUpsertForBundleData = { bundle_id: string, id: string, name: string, trigger: string, skill_type: string, description: string, content: string, };
