// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests for the three payload-ignoring agent commands
 * (`containerruntimeavailable`, `reseedagents`, `exportagents`).
 *
 * Structs rather than `()`: the stub calls each with no argument, which the
 * RPC client sends as `{}`, and serde deserializes `()` only from JSON
 * `null` -- a unit Req would reject every real call while compiling and
 * passing every CI gate (the `bookmarks.list` bug).
 */
export type CommandContainerRuntimeAvailableData = Record<string, never>;
