// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `globalmemory:sections` — no arguments.
 */
export type CommandGlobalMemorySectionsData = Record<string, never>;
