// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for AgentShutdownKeepCommand — the pending-shutdown banner's "Keep
 * running" (docs/specs/SPEC_AGENT_SELF_QUIT_2026_09_24.md §6.5, §12.3).
 */
export type CommandAgentShutdownKeepData = { blockid: string, 
/**
 * From the `agent:shutdown-pending` event being answered.
 */
request_id: string, };
