// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `setagentbundles`: the whole list, in order. Blank ids, repeats
 * and the agent's own bundle are dropped.
 */
export type CommandSetAgentBundlesData = { agent_id: string, bundle_ids: Array<string>, };
