// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for ResolveCliCommand — detect or install a CLI tool.
 */
export type CommandResolveCliData = { 
/**
 * Provider ID (e.g. "claude", "codex", "gemini")
 */
provider_id: string, 
/**
 * CLI command name (e.g. "claude")
 */
cli_command: string, 
/**
 * npm package name for fallback install (e.g. "@anthropic-ai/claude-code")
 */
npm_package: string, 
/**
 * Version to install ("latest" or specific version)
 */
pinned_version: string, 
/**
 * Windows install command (e.g. "irm https://claude.ai/install.ps1 | iex")
 */
windows_install_command: string, 
/**
 * Unix install command (e.g. "curl -fsSL https://claude.ai/install.sh | bash")
 */
unix_install_command: string, 
/**
 * Block ID to stream install output into (optional — if empty, no streaming)
 */
block_id: string, 
/**
 * The pane this resolve launches into, for its CLI notices
 * (`backend::cli_notice`). A quick fork resolves from its source pane
 * (`block_id`) but launches into a new one. Absent: `block_id`.
 */
notice_block_id?: string, 
/**
 * The agent the CLI is resolved for, whose last-run version is
 * recorded. A new picker pane resolves before its `agentId` meta is
 * written, so the caller says. Absent: the notice pane's `agentId`.
 */
agent_id?: string, };
