// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `globalmemory:sections`.
 */
export type CommandGlobalMemorySectionsData = { 
/**
 * The agent pane the sections are for. Its `agentMode` decides which
 * Operator Config entries are included, as for its startup file
 * (`operator_config_seed::global_bundles_for_agent`). Absent: every
 * entry, as a host agent gets them.
 */
block_id?: string, };
