// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `writeeditorfile`.
 *
 * The three encoding fields ARE optional here, and for a real reason rather
 * than back-compat hedging: omitting them means "write UTF-8/no BOM/LF",
 * which is what a caller that never read the file back wants. They are
 * `Option<T>` in Rust, so ts-rs marks them optional without help.
 */
export type CommandWriteEditorFileData = { path: string, content: string, encoding?: string, bom?: string, line_ending?: string, };
