// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `remotetest`: log in to a remote AgentMux already lists and run `true`,
 * ssh's prompts going to the user in the window of pane `blockid`.
 */
export type CommandRemoteTestData = { connection: string, blockid: string, };
