// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `listallagentidentities`. The handler ignores its payload, but
 * this must be a struct rather than `()`: the stub calls it with `{}`, and
 * serde deserializes `()` only from JSON `null`, so a unit Req would reject
 * every real call at runtime while passing every CI gate.
 */
export type CommandListAllAgentIdentitiesData = Record<string, never>;
