// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `remoteforget`: remove `connection` from the recent list.
 */
export type CommandRemoteForgetData = { connection: string, };
