// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for `tooldecision` — frontend's reply to a per-tool-call
 * permission gate. Today the backend validates the outcome and
 * logs the decision; actual delivery to the agent CLI is deferred
 * to PR-3b/PR-4 (rules persistence vs. interactive subprocess
 * path). Spec:
 * docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §9.1.
 */
export type CommandToolDecisionData = { blockid: string, 
/**
 * Opaque id matched against a `PermissionRequestEvent`. Echoed
 * in the audit log so the audit trail can be cross-referenced.
 */
request_id: string, 
/**
 * "allow" or "deny". Anything else returns an error.
 */
outcome: "allow" | "deny", 
/**
 * "once" / "session" / "project" / "global". Captured so the
 * rules-persistence layer (PR-3b) can write a matching rule
 * without re-asking the user.
 */
scope: "once" | "session" | "project" | "global", 
/**
 * User-typed denial reason. Optional. Future PR will relay
 * this verbatim into the agent's next prompt.
 */
feedback?: string, };
