// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for `COMMAND_BACKGROUND_TASK_PID` — a declared-background task's
 * real OS pid, relayed from `agentmux-bashwrap`'s own MPS `"pid"` chunk.
 * `node_id` is the originating tool call's node_id/tool_use_id, same join
 * key as `CommandBackgroundTaskCompletionData` above. See
 * docs/specs/SPEC_BACKGROUND_TASK_PID_CAPTURE_2026_08_20.md.
 */
export type CommandBackgroundTaskPidData = { blockid: string, node_id: string, pid: number, };
