// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.catalog.upsert` — window-scoped. Same field rules.
 */
export type CommandMcpCatalogUpsertData = { id: string, name: string, transport: string, config: string, };
