// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.catalog.upsert` — window-scoped, so no agent key. Same field rules as
 * `CommandSkillUpsertData`.
 */
export type CommandSkillCatalogUpsertData = { id: string, name: string, trigger: string, skill_type: string, description: string, content: string, };
