// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `attachments.copy-to-workdir` — copy a stored attachment into the pane's
 * working folder (`cmd:cwd`). Container panes use this for pasted files:
 * their agents can't see the store.
 */
export type CommandAttachmentsCopyToWorkdirData = { block_id: string, id: string, 
/**
 * The user's file name; de-conflicted in the folder.
 */
name: string, };
