// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `agent:session:write_state`. Writes `output.state.json`
 * into `agent:<definition_id>:current` (creates the zone if missing).
 */
export type CommandAgentSessionWriteStateData = { definition_id: string, content: string, };
