// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `readeditorfile`.
 */
export type CommandReadEditorFileData = { path: string, 
/**
 * An SSH connection the file is on (`fs_ops::remote`); absent, local or
 * WSL: this machine, as before.
 */
connection?: string, 
/**
 * The pane asking, whose window shows any ssh prompt for `connection`.
 */
block_id?: string, };
