// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `globalmemory:import_sources` — no arguments.
 */
export type CommandGlobalMemoryImportSourcesData = Record<string, never>;
