// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Open a layout file's tabs: added as new tabs to an existing window
 * (nothing that's open is replaced), or into a new workspace for a new
 * window to show.
 */
export type CommandLayoutOpenData = { path: string, 
/**
 * The window to add the tabs to. Not used with `new_window`.
 */
window_id: string, 
/**
 * Start the file's terminal commands. Defaults to whether the file is
 * trusted (see `LayoutPreviewResult::trusted`).
 */
run_commands?: boolean, 
/**
 * Build the tabs in a new workspace of their own instead; the caller
 * then opens a window onto `LayoutOpenResult::workspace_id`.
 */
new_window?: boolean, };
