// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for session:export — read session output and return as base64 JSONL.
 */
export type CommandSessionExportData = { block_id: string, };
