// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for AskSideQuestionCommand — the `/btw` slash command's one-shot,
 * tool-less side question. `context_snapshot` is a frontend-supplied
 * compact rendering of the asking pane's currently-visible transcript,
 * prepended to `question` as the prompt sent to the CLI (there is no
 * `--resume`/live session context on this path — see
 * `server/agent_handlers/side_question.rs`'s module doc comment for why).
 */
export type CommandAskSideQuestionData = { block_id: string, question: string, context_snapshot: string, };
