// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for updateagentskill.
 *
 * Full replace, not a patch: the handler builds a whole `AgentSkill` out of
 * these fields and writes it, keeping only `agent_id` and `created_at` from
 * the existing row. So an omitted `description` does not mean "leave it
 * alone", it means "set it to empty" -- and `skill_type` is worse, because
 * `createagentskill` defaults it to "prompt" while this defaults it to "",
 * so a create-then-update round trip that omits the field silently blanks a
 * value the create had filled in.
 *
 * The `serde(default)`s are kept (dropping them would reject payloads the
 * server accepts today), but the generated TS deliberately does NOT restate
 * them as optional the way `CommandCreateAgentSkillData` does. Full-replace
 * semantics make every field semantically required, and there is no caller to
 * break: nothing in the frontend calls `updateagentskill` today.
 */
export type CommandUpdateAgentSkillData = { id: string, name: string, trigger: string, skill_type: string, description: string, content: string, };
