// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandNativeMemoryDiffData = { 
/**
 * reagent P1: required so the handler can verify BOTH versions belong
 * to this agent before returning their content — unlike list/read/
 * write/history/revert (all of which take an agent_id and scope to
 * it), diff originally took bare version ids with no ownership check
 * at all. Since every caller shares one instance-wide X-AuthKey, that
 * let any caller read any other agent's memory content by version id.
 */
agent_id: string, from_version_id: string, to_version_id: string, };
