// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for `COMMAND_LIST_BACKGROUND_TASKS` — request/response, returns
 * this block's current `db_background_tasks` rows (as
 * `muxspect_handlers::BackgroundTaskView`s). See
 * docs/specs/SPEC_BACKGROUND_TASK_DASHBOARD_INTELLIGENCE_2026_08_20.md §3.1.
 */
export type CommandListBackgroundTasksData = { blockid: string, };
