// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for listagenthistory
 */
export type CommandListAgentHistoryData = { agent_id: string, session_date?: string, 
/**
 * `serde(default)` -> 50, which ts-rs cannot express on a non-`Option`
 * field; the stub derives `ListAgentHistoryInput` to restore it.
 */
limit: number, offset: number, };
