// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleImportFileEntry } from "./BundleImportFileEntry";
import type { BundleImportSkillSelection } from "./BundleImportSkillSelection";

/**
 * Request for `bundle.import.commit`. Same three-way input as preview, plus
 * the selections and the digest that proves the source has not changed since.
 *
 * Every field is `#[serde(default)]`, so all of them are omittable on the
 * wire. The non-`Option` ones (`expected_content_digest`,
 * `include_instructions`, the three `include_*` lists) are generated as
 * REQUIRED because ts-rs cannot express an optional property for a
 * non-`Option` field — which is fine and arguably better here: silently
 * defaulting `expected_content_digest` to `""` on a commit would skip the
 * staleness check the digest exists to enforce, so callers should be made to
 * pass it.
 */
export type CommandBundleImportCommitData = { file_path?: string, zip_base64?: string, files?: Array<BundleImportFileEntry>, expected_content_digest: string, bundle_name?: string, include_instructions: boolean, 
/**
 * Indices into the preview's `context_files`, by `id`.
 */
include_context_files: number[], include_skills: Array<BundleImportSkillSelection>, 
/**
 * `source_path` values from the preview's `mcp_servers`.
 */
include_mcp_servers: Array<string>, };
