// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for RunCliLoginCommand — spawns the CLI login flow and extracts the OAuth URL
 */
export type CommandRunCliLoginData = { cli_path: string, login_args: Array<string>, auth_env: { [key in string]?: string }, };
