// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Matches Go's `CommandEventReadHistoryData`
 */
export type CommandEventReadHistoryData = { event: string, scope: string, maxitems: number, };
