// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for importagentfromclaw
 */
export type CommandImportAgentFromClawData = { workspace_path: string, agent_name: string, };
