// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for setagentcontent
 */
export type CommandSetAgentContentData = { agent_id: string, content_type: string, content: string, };
