// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for AgentCancelCommand — a real protocol-level decline of a pending
 * AskUserQuestion (Cancel button / Escape), delivered as a control_response
 * carrying `behavior: "deny"` rather than the allow+answers shape above. No
 * `answers` field: there is nothing to carry, the deny message is a fixed
 * server-owned string (see `ASK_USER_QUESTION_DENY_MESSAGE` in
 * blockcontroller/persistent.rs). Spec:
 * docs/specs/SPEC_AGENT_CONTROL_PROTOCOL_2026_06_15.md.
 */
export type CommandAgentCancelData = { blockid: string, 
/**
 * The `AskUserQuestion` tool_use id being declined (correlates with the
 * parked `can_use_tool` control_request).
 */
tool_use_id: string, };
