// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `readeditorfile`.
 *
 * The four encoding fields are NOT optional, though the hand-written
 * declaration marked them `?:` "for back-compat; absent ⇒ treat as UTF-8".
 * `decode_file` returns all four unconditionally and the handler writes all
 * four every time, so the server has never omitted them — the optionality was
 * only ever true of a client reading a response from a build that predates
 * SPEC_EDITOR_FILE_ENCODINGS, which is not a thing the binding describes.
 */
export type CommandReadEditorFileResult = { content: string, 
/**
 * Encoding label (WHATWG / `encoding_rs` name, e.g. "windows-1252").
 */
encoding: string, 
/**
 * The BOM that was present: "none" | "utf-8" | "utf-16le" | "utf-16be".
 */
bom: string, 
/**
 * "crlf" if any CRLF was present, else "lf".
 */
line_ending: string, 
/**
 * True when decoding inserted U+FFFD replacements, i.e. the detected
 * encoding is probably wrong.
 */
had_decode_errors: boolean, read_only: boolean, };
