// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for session:activity_summary — maintain a stable, session-goal
 * title via Haiku, routed through the Ambient Model Call gateway
 * (`crate::ambient`). See
 * docs/specs/SPEC_AMBIENT_MODEL_CALLS_FRAMEWORK_2026_07_03.md and
 * docs/specs/SPEC_AMBIENT_PANE_TITLE_OVERALL_GOAL_TRACKING_2026_08_17.md.
 */
export type CommandActivitySummaryData = { block_id: string, 
/**
 * Target word count, derived from pane width. Defaults to 7.
 */
word_target?: number, 
/**
 * Caller's monotonic turn counter for this block (bumped on every new
 * turn). Used by the ambient gateway to cancel a stale in-flight call
 * for the same block and reject a request that arrives out of order.
 */
generation: number, 
/**
 * The user's newest message, verbatim (the frontend's
 * `TurnPhase.Submitting.pendingContent`) — what the title-maintaining
 * Haiku call evaluates against the current title. Falls back to a
 * FileStore output-tail digest server-side when absent (e.g. an older
 * frontend build) so the endpoint degrades gracefully instead of going
 * silent.
 */
user_message?: string, };
