// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for updateagent
 */
export type CommandUpdateAgentDefinitionData = { id: string, name: string, icon: string, provider: string, description: string, working_directory: string, shell: string, provider_flags: string, auto_start: number, restart_on_crash: number, idle_timeout_minutes: number, agent_type: string, environment: string, agent_bus_id: string, 
/**
 * JSON-encoded per-provider account assignments (see
 * `AgentDefinition.accounts`). Written by the Agent pane's Identity tab.
 */
accounts: string, 
/**
 * Docker image for container-type agents. Empty string for host agents.
 */
container_image: string, 
/**
 * JSON array of volume mount specs. Empty array (`"[]"`) for host agents.
 */
container_volumes: string, 
/**
 * Explicit per-agent opt-in to the CLI's global (ambient) login when no
 * oauth-class account resolves at spawn (0/1). `None` (omitted) preserves
 * the stored value — callers that only edit name/icon/accounts don't
 * carry it. SPEC_ACCOUNT_DELETE_DEAUTH_LAYERS_2_4_2026_07_14.md §2.3.
 */
use_ambient_login: number | null, 
/**
 * Per-agent opt-in letting a Warden Supervisor watcher agent
 * auto-continue this agent's session on turn-end (0/1). `None`
 * (omitted) preserves the stored value — callers that only edit
 * name/icon/accounts don't carry it. Toggled from the Warden
 * Supervisor panel. See
 * docs/analysis/ANALYSIS_WARDEN_AUTO_CONTROLLER_CONTINUATION_WATCHER_2026_08_12.md.
 */
auto_continue_enabled: number | null, 
/**
 * Custom model vendor base URL override — see
 * `AgentDefinition.model_vendor_base_url`. `None` (omitted) preserves
 * the stored value, same "None = don't touch" idiom as
 * `use_ambient_login`/`auto_continue_enabled` above. `Some("")`
 * explicitly clears an existing override back to the harness's
 * default vendor endpoint. Validated the same way `agent.define`
 * does — see `agent_define::validate_vendor_base_url`.
 */
model_vendor_base_url: string | null, };
