// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `attachments.cancel` — stop processing the rest of a batch.
 */
export type CommandAttachmentsCancelData = { batch_id: string, };
