// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for `ambientnarrate` — ask the backend to generate a short
 * user-facing line describing something AgentMux just did on its own.
 *
 * Best-effort: the caller does not await a reply and must not gate any UI
 * state change on one. If narration is capped, cancelled, or fails, the thing
 * being narrated still happened and the UI must already show it.
 */
export type CommandAmbientNarrateData = { blockid: string, 
/**
 * Selects the prompt. Unknown kinds are a deliberate no-op rather than an
 * unconstrained prompt — see `narration_prompt`.
 */
kind: string, 
/**
 * What to narrate, in the caller's own words (e.g. the command line of the
 * call that just went background).
 */
context: string, 
/**
 * De-duplication key, unique per narrated event (the `node_id` for a
 * background launch). A node can be re-observed; narrating twice for one
 * event would be both noisy and a wasted model call.
 */
dedupe_key: string, };
