// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `voice.checkPath` request — the whisper.cpp CLI/model path the Settings →
 * Recording section wants an existence check for.
 *
 * Named (rather than an inline `serde_json::from_value` struct in the
 * handler) so the RPC bindings generator can emit it — see
 * `docs/specs/SPEC_RPC_BINDINGS_CODEGEN_2026_09_07.md` §3.1.
 */
export type CommandVoiceCheckPathData = { path: string, };
