// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `viewer.agent-hidden`: read an agent's "hide from paired devices" flag, or
 * set it when `hidden` is given. `agent_id` is the definition id.
 */
export type CommandViewerAgentHiddenData = { agent_id: string, hidden?: boolean, };
