// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `remoteagentrevoke`: forget "always allow" for `agent` on `connection`
 * (SPEC_REMOTES_PANE_2026_10_05.md §4.10).
 */
export type CommandRemoteAgentRevokeData = { connection: string, agent: string, };
