// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memorydelivery:claim_fallback` — the frontend's hidden memory reinjection
 * asks whether to deliver (SPEC_GLOBAL_MEMORY_DELIVERY_2026_09_27.md §7 P2).
 */
export type CommandMemoryDeliveryClaimFallbackData = { block_id: string, 
/**
 * The reinjection's reason: `compaction` or `fresh_session`.
 */
reason: string, 
/**
 * The compaction boundary's `uuid`: a second claim for the same boundary
 * (a re-read, another pane of the agent) stands down.
 */
boundary_uuid?: string, };
