// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `attachments.ingest` — hand the backend OS paths (from a drop or a native
 * clipboard read) to copy into the attachment store and process.
 */
export type CommandAttachmentsIngestData = { 
/**
 * The agent pane asking. Progress events are scoped `block:<id>`.
 */
block_id: string, 
/**
 * Client-chosen id for this batch; echoed in every event.
 */
batch_id: string, paths: Array<string>, 
/**
 * Only classify and apply the limits; copy and process nothing.
 * Used by the drop overlay to describe a drag before it lands.
 */
dry_run: boolean, 
/**
 * Attachments already in the draft, so the limits cover the whole prompt.
 */
existing_count: number, existing_bytes: number, };
