// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `containerruntimeavailable`. Was an inline
 * `json!({ "available": .. })`.
 */
export type ContainerRuntimeAvailableResult = { available: boolean, };
