// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerImageAccess } from "./ContainerImageAccess";

/**
 * Result of `containerimagecheck`.
 */
export type ContainerImageCheckResult = { status: ContainerImageAccess, };
