// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a container image can be had on this machine.
 */
export type ContainerImageAccess = "local" | "public" | "denied" | "not_found" | "unknown";
