// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `createscratchfile`.
 */
export type CreateScratchFileResult = { scratch_id: string, file_path: string, 
/**
 * The name actually assigned, which is not necessarily the requested
 * `display_name` — collisions get a suffix.
 */
display_name: string, };
