// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `createeditorfile`. `name` is a plain filename (see
 * `RenameEditorFileReq`).
 */
export type CreateEditorFileReq = { parent_path: string, name: string, };
