// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `createeditorfile`.
 */
export type CreateEditorFileResult = { file_path: string, };
