// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `createscratchfile`. Both fields are genuinely optional —
 * `Option<T>` in Rust, so ts-rs can say so without help.
 */
export type CreateScratchFileReq = { display_name?: string, 
/**
 * Ids the caller already has open, so the generated "Untitled-N" name
 * does not collide with a buffer that exists only in the renderer.
 */
exclude_scratch_ids?: Array<string>, };
