// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `deleteagentinstance`. Was an anonymous `json!({"deleted": ..})`
 * before this type existed to name it for the RPC bindings generator.
 */
export type DeleteAgentInstanceResult = { deleted: boolean, };
