// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `deleteeditorfile`.
 *
 * `recursive` has no `serde(default)` on purpose: defaulting it would make a
 * caller that forgot the field delete a directory tree it never asked to,
 * or fail confusingly on a non-empty one. Requiring it keeps the destructive
 * choice explicit, and the hand-written stub already typed it as required.
 */
export type DeleteEditorFileReq = { path: string, recursive: boolean, };
