// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `deletememory` and `deletesystemmemory` — both take the
 * same request (`CommandDeleteBundleData`, above) and answer with the
 * same shape, so they share this response type too. Was an anonymous
 * `json!({"deleted": ..})` before this type existed to name it for the
 * RPC bindings generator.
 */
export type DeleteBundleResult = { deleted: boolean, };
