// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One editor file-tree row.
 *
 * `size` and `mtime` are genuinely absent rather than zero: directories have
 * no meaningful size, and `modified()` is not available on every platform or
 * filesystem. Sending `0` would be indistinguishable from a real empty file
 * or a real epoch timestamp, so they stay omitted.
 */
export type DirEntry = { name: string, 
/**
 * Follows symlinks, so a symlink to a directory reads as a directory —
 * which is what VS Code does and what the tree renders.
 */
is_dir: boolean, 
/**
 * Does NOT follow symlinks; this is the entry's own type.
 */
is_symlink: boolean, size?: number, 
/**
 * Unix millis.
 */
mtime?: number, };
