// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DroneBlockState = { 
/**
 * A `String` in Rust so a row written by a newer build still reads back,
 * but the closed set on the TS side is real and the frontend branches on
 * it -- a bare `string` here would be a downgrade. Keep the union and let
 * `block_status_union_covers_every_value_the_executor_writes` fail if the
 * executor ever starts writing something outside it.
 */
status: "pending" | "running" | "done" | "error" | "skipped", output?: unknown, error?: string, started_at?: number, completed_at?: number, };
