// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DroneBlockState } from "./DroneBlockState";

/**
 * One row in `db_drone_runs`. Append-only history of executions.
 */
export type DroneRun = { id: string, drone_id: string, 
/**
 * Deliberately not the `RunStatus` union: rows written by older builds
 * are read back through this field, so it has to stay open.
 */
status: string, started_at: number, ended_at: number, 
/**
 * Map of block_id → BlockState snapshot at run completion.
 */
block_states: { [key in string]?: DroneBlockState }, 
/**
 * Final output captured by the Response block (stringified JSON).
 */
output: string, 
/**
 * Top-level error message if the run failed before reaching Response.
 */
error: string, };
