// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DroneFlowEdge } from "./DroneFlowEdge";
import type { DroneFlowNode } from "./DroneFlowNode";

/**
 * Top-level graph payload — what the canvas saves and the executor reads.
 */
export type DroneGraph = { nodes: Array<DroneFlowNode>, edges: Array<DroneFlowEdge>, };
