// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DroneNodePosition } from "./DroneNodePosition";

/**
 * Position-and-data shape of a node on the canvas. Mirrors xyflow's
 * `Node` — id, position, data, type are the fields the canvas reads.
 * Anything inside `data` is block-specific config.
 */
export type DroneFlowNode = { id: string, 
/**
 * xyflow position. Saved as-is.
 */
position: DroneNodePosition, 
/**
 * Block kind + per-kind config (`task`, `url`, `expr`, etc.).
 *
 * `serde_json::Value` says nothing about the one field every block
 * actually has, and the hand-written declaration did: keep the narrower
 * TS. A `Value` here is not a promise that the contents are arbitrary,
 * it is the absence of a per-kind Rust enum (Phase 2).
 */
data: Record<string, unknown> & { kind: string }, 
/**
 * Optional xyflow node type — keeps the canvas configurable.
 *
 * `Option<String>`, not `String`: the server omits the key entirely
 * when it is blank, so a required `type: string` in the generated TS
 * would be wrong in the read direction -- which is the direction the
 * canvas uses. `is_blank` rather than `Option::is_none` keeps the
 * pre-existing wire behaviour exactly, where an empty string is also
 * omitted.
 */
type?: string, };
