// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `geteditorhome` / `geteditorroots`, which ignore their payload.
 *
 * A struct rather than `()`, registered as `Option<Self>`: the stub sends
 * `{}` and a client that omits `data` sends `null`, and serde accepts each of
 * those from only one of `()` and a struct.
 */
export type EditorRootsReq = Record<string, never>;
