// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnsureAccountDirResp = { accountId: string, 
/**
 * `None` when the provider isn't oauth-class or the dir couldn't be
 * resolved/created — same soft-failure contract as `auth.start`'s
 * internal use of `compute_and_ensure_account_dir`.
 */
dir?: string, };
