// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `provider.ensureauthdir`.
 */
export type EnsureProviderAuthDirReq = { 
/**
 * Provider id or alias (e.g. "claude").
 */
provider_id: string, };
