// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `provider.ensureauthdir`.
 */
export type EnsureProviderAuthDirResult = { 
/**
 * Absolute path of the provider's default auth dir, created and
 * isolation-prepared (e.g. Claude's CLAUDE.md placeholder).
 */
path: string, };
