// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnsureAccountDirReq = { providerId: string, 
/**
 * Non-empty to resolve an already-minted account's own dir
 * (reconnect-in-place); empty mints a fresh account id.
 */
existingAccountId: string, };
