// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetActionFailure } from "./FleetActionFailure";

/**
 * One outcome bucket per bulk action, mirroring `ImportAgentDefinitionsResult`'s
 * partial-success shape — the spec's §3 finding that silent partial failure
 * is the single most commonly-cited fleet-ops pitfall means this must never
 * collapse to a single bool/count.
 */
export type FleetActionResult = { succeeded: Array<string>, failed: Array<FleetActionFailure>, 
/**
 * True only when a staged run's `max_fail_percentage` was crossed and
 * remaining batches were skipped — lets the frontend show "aborted
 * early" distinctly from "ran to completion, some failed."
 */
aborted_early: boolean, };
