// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `fleet.group.delete`. Previously an ad-hoc
 * `json!({ "ok": deleted })` built inline in the handler — the kind of
 * untyped literal that cannot be checked against the frontend at all.
 */
export type FleetGroupDeleteResult = { 
/**
 * False when no group with that id existed — the delete is idempotent,
 * so this is "was something actually removed", not an error flag.
 */
ok: boolean, };
