// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsCreateKind } from "./FsCreateKind";

/**
 * Request for `fs.create`: a new empty file or folder. Fails if the name is
 * taken.
 */
export type FsCreateReq = { parent: string, name: string, kind: FsCreateKind, };
