// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of an `fs.list` page.
 *
 * `size` and `mtime` are absent rather than zero when unknown, for the same
 * reason as `DirEntry`'s: `0` would read as a real empty file or a real epoch
 * timestamp. A directory never has a `size`.
 */
export type FsEntry = { name: string, 
/**
 * Follows symlinks: a link to a directory reads as a directory.
 */
is_dir: boolean, 
/**
 * The entry's own type, not followed. Windows junctions count as links.
 */
is_symlink: boolean, size?: number, 
/**
 * Unix millis.
 */
mtime?: number, 
/**
 * A dot-prefixed name, or (Windows) the hidden or system attribute.
 */
hidden: boolean, 
/**
 * The read-only permission/attribute. Always false for a folder on
 * Windows, which ignores the attribute on folders.
 */
readonly: boolean, 
/**
 * Where a symlink points, as stored in the link (not resolved).
 */
link_target?: string, 
/**
 * Why this entry's details couldn't be read (a dangling link, a file
 * that vanished mid-listing, access denied). The row is still listed;
 * `size`/`mtime` are then absent.
 */
error?: string, };
