// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a listing could not be produced.
 */
export type FsErrorKind = "not_found" | "permission_denied" | "os_blocked" | "not_a_directory" | "expired" | "other";
