// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsGitEntry } from "./FsGitEntry";

/**
 * Response for `fs.git_status`: the repository the folder is in, if any,
 * and the state of each of its direct children that isn't clean.
 */
export type FsGitStatus = { 
/**
 * False when the folder isn't in a repository (or git isn't installed).
 */
in_repo: boolean, branch?: string, ahead?: number, behind?: number, entries: Array<FsGitEntry>, 
/**
 * Changed (not ignored) paths under this folder, at any depth.
 */
changes: number, 
/**
 * Set when git ran but failed or timed out; the pane shows no markers.
 */
error?: string, };
