// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsGitState } from "./FsGitState";

/**
 * One entry of the listed folder that git has something to say about.
 */
export type FsGitEntry = { 
/**
 * The entry's name in the listed folder (a direct child).
 */
name: string, state: FsGitState, };
