// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What git says about one entry of the listed folder. A folder takes the
 * most pressing state of anything inside it.
 */
export type FsGitState = "ignored" | "untracked" | "added" | "renamed" | "deleted" | "modified" | "conflicted";
