// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.list`.
 *
 * The first page names the directory (`path`, which may start with `~`).
 * Later pages pass the `cursor` the previous page returned; `path` is then
 * only used to label an `expired` answer.
 */
export type FsListReq = { path: string, cursor?: string, 
/**
 * Entries per page. Default 1000, capped at 5000.
 */
limit?: number, };
