// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsEntry } from "./FsEntry";
import type { FsError } from "./FsError";

/**
 * Response for `fs.list`.
 *
 * Failing to open the directory is not an RPC error: the answer is `Ok` with
 * no entries, no cursor, and `error` set, so the pane can show a distinct
 * state (spec §9: errors are per entry or per folder, never a failed pane).
 */
export type FsListResult = { 
/**
 * The canonical directory, in display form, on every page.
 */
path: string, 
/**
 * Unsorted; the frontend sorts.
 */
entries: Array<FsEntry>, 
/**
 * Absent once the listing is complete.
 */
cursor?: string, error?: FsError, };
