// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.list`.
 *
 * The first page names the directory (`path`, which may start with `~`).
 * Later pages pass the `cursor` the previous page returned; `path` is then
 * only used to label an `expired` answer.
 */
export type FsListReq = { path: string, cursor?: string, 
/**
 * Entries per page. Default 1000, capped at 5000.
 */
limit?: number, 
/**
 * An SSH connection to run this on (its helper, `fs_ops::remote`);
 * absent, local, or WSL: this machine, as before.
 */
connection?: string, 
/**
 * The pane asking, whose window shows any ssh prompt for `connection`.
 */
block_id?: string, };
