// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsOpKind } from "./FsOpKind";

/**
 * Request for `fs.op.start`: copy or move `sources` into `dest_dir`.
 *
 * Validated before the answer: the destination is a folder, every source
 * exists, no folder goes into itself, and nothing protected is touched.
 * The work then runs in the background and reports as `files:op` events.
 */
export type FsOpStartReq = { kind: FsOpKind, sources: Array<string>, dest_dir: string, 
/**
 * Scopes the `files:op` events to `block:<block_id>`.
 */
block_id: string, 
/**
 * The SSH connection `sources` are on; absent, local or WSL: this
 * machine (`fs_ops::host_jobs`).
 */
source_connection?: string, 
/**
 * The SSH connection `dest_dir` is on; absent, local or WSL: this
 * machine.
 */
connection?: string, };
