// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two sides of a conflict, for the Replace / Skip / Keep both prompt.
 */
export type FsOpConflict = { source: string, dest: string, 
/**
 * Each side's own type, not followed: a link to a folder is not a
 * folder.
 */
source_is_dir: boolean, dest_is_dir: boolean, 
/**
 * Files only.
 */
source_size?: number, dest_size?: number, 
/**
 * Unix millis.
 */
source_mtime?: number, dest_mtime?: number, };
