// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an op is. `done`, `failed` and `canceled` are final: no event
 * follows them.
 */
export type FsOpEventState = "running" | "conflict" | "done" | "failed" | "canceled";
