// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `fs.op.start`. Events for the op may arrive before it.
 */
export type FsOpStartResult = { op_id: string, };
