// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsOpResult } from "./FsOpResult";

/**
 * Response for `fs.trash`, `fs.restore` and `fs.delete`: one result per
 * requested path, in request order. One path failing never stops the rest.
 */
export type FsOpResults = { results: Array<FsOpResult>, };
