// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.op.cancel`. An unknown or finished op is not an error.
 */
export type FsOpCancelReq = { op_id: string, };
