// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One path's outcome in a batch operation.
 */
export type FsOpResult = { 
/**
 * The path as the request named it.
 */
path: string, ok: boolean, 
/**
 * A sentence fit to show the user. Absent when `ok`.
 */
error?: string, };
