// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An answer to a conflict (spec §7.2).
 */
export type FsOpChoice = "replace" | "skip" | "keep_both";
