// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsOpChoice } from "./FsOpChoice";

/**
 * Request for `fs.op.resolve`: answer the conflict an op is waiting on.
 */
export type FsOpResolveReq = { op_id: string, choice: FsOpChoice, 
/**
 * Use the same answer for every later conflict of this op.
 */
apply_to_all: boolean, };
