// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsOpConflict } from "./FsOpConflict";
import type { FsOpEventState } from "./FsOpEventState";
import type { FsOpKind } from "./FsOpKind";
import type { FsOpResult } from "./FsOpResult";

/**
 * Payload of the `files:op` event, scoped to `block:<block_id>`.
 *
 * `running` events come at most every 100 ms; every other state is sent
 * as it happens. Counts cover files, links and folders alike; bytes count
 * file contents only.
 */
export type FsOpEvent = { op_id: string, kind: FsOpKind, state: FsOpEventState, done_items: number, 
/**
 * Zero until the sources have been measured.
 */
total_items: number, done_bytes: number, total_bytes: number, 
/**
 * The source path being worked on.
 */
current?: string, 
/**
 * Set in the `conflict` state.
 */
conflict?: FsOpConflict, 
/**
 * Set in the `failed` state, and on `canceled` when the op stopped by
 * itself (an unanswered conflict). A sentence fit to show the user.
 */
error?: string, 
/**
 * Per-item failures, by source path, on a final event. Absent when
 * none failed.
 */
failures?: Array<FsOpResult>, };
