// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.open` (the OS default application) and `fs.reveal` (select
 * in the OS file manager).
 */
export type FsPathReq = { path: string, };
