// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsPlaceKind } from "./FsPlaceKind";

export type FsPlace = { 
/**
 * Stable within one answer: `home`, `desktop`, `documents`,
 * `downloads`, `pictures`, or `drive:<path>`.
 */
id: string, label: string, path: string, kind: FsPlaceKind, };
