// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.places`, which takes no argument.
 *
 * A struct registered as `Option<Self>`, like `EditorRootsReq`: the stub
 * sends `{}` and a client that omits `data` sends `null`.
 */
export type FsPlacesReq = Record<string, never>;
