// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.rename`: a new name in the same folder.
 */
export type FsRenameReq = { path: string, 
/**
 * A plain name: no separators, not `.` or `..`, and on Windows none of
 * the names or characters Windows refuses or silently alters.
 */
new_name: string, };
