// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.restore`: put each path, trashed earlier, back where it
 * was. The paths are the ORIGINAL locations, as `fs.trash` was given them.
 */
export type FsRestoreReq = { paths: Array<string>, };
