// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.trash`: move each path to the OS Trash / Recycle Bin.
 */
export type FsTrashReq = { paths: Array<string>, };
