// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `fs.watch`. Pass `watch_id` to `fs.unwatch`.
 */
export type FsWatchResult = { watch_id: string, };
