// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `fs.watch`.
 */
export type FsWatchReq = { path: string, 
/**
 * Scopes the `files:changed` event to `block:<block_id>`.
 */
block_id: string, };
