// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorDrive } from "./EditorDrive";

/**
 * Response for `geteditorroots`.
 */
export type GetEditorRootsResult = { home: string, drives: Array<EditorDrive>, };
