// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatusEntry } from "./ToolStatusEntry";

export type GetToolStatusResult = { tools: Array<ToolStatusEntry>, };
