// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalMemoryVersionMeta } from "./GlobalMemoryVersionMeta";

export type GlobalMemoryRevertResult = { 
/**
 * The new `source: "revert"` version. `null` only for a system-tier
 * entry whose revert target is byte-identical to what's stored — that
 * path deliberately records no version for a no-op (see
 * `Store::bundle_upsert_system_if_changed`).
 */
version: GlobalMemoryVersionMeta | null, };
