// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalMemoryImportEntry } from "./GlobalMemoryImportEntry";

/**
 * Another scope whose record holds entries this channel lacks.
 */
export type GlobalMemoryImportSource = { index: number, 
/**
 * `shared`, or `channel:<id>`.
 */
scope: string, 
/**
 * Its live, non-system entries this channel doesn't have, in its order.
 */
missing: Array<GlobalMemoryImportEntry>, };
