// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One section of the Global Memory block: one global bundle with
 * instructions, rendered as the startup file carries it.
 */
export type GlobalMemorySection = { 
/**
 * The Global Memory entry's id (the bundle id).
 */
id: string, name: string, is_system: boolean, 
/**
 * `# [AgentMux System] <name>` or `# [Workspace] <name>`, a blank line,
 * then the instructions. The first system section also opens with the
 * override preamble.
 */
text: string, 
/**
 * `text`'s length in bytes: what this section adds to an injection.
 */
size_bytes: number, };
