// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalMemoryImportReport = { added: number, 
/**
 * Added under a new name: another entry here already had theirs.
 */
renamed: number, };
