// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalMemoryImportSource } from "./GlobalMemoryImportSource";

export type GlobalMemoryImportSources = { list_id: string, 
/**
 * This channel's scope. Sources are offered only to an isolated one.
 */
scope: string, sources: Array<GlobalMemoryImportSource>, };
