// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `db_bundle_versions` row's metadata, no `name`/`instructions` —
 * the same fields `bundle_version_meta_json` (app_api) puts on the MCP wire.
 */
export type GlobalMemoryVersionMeta = { id: string, content_hash: string, parent_version_id: string | null, source: string, source_detail: string, 
/**
 * The trusted writer: an agent's own id, or `"armory-ui"`.
 */
written_by: string, written_by_uid: string, created_at: number, };
