// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `hidenamedagent`. Was an anonymous `json!({"hidden": ..})`
 * before this type existed to name it for the RPC bindings generator.
 */
export type HideNamedAgentResult = { hidden: boolean, };
