// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretRef } from "./SecretRef";

/**
 * An identity account (reusable credential, linked to agents via the
 * `db_agent_identity_links` junction). Replaces the browser
 * localStorage identity store.
 */
export type IdentityAccount = { id: string, name: string, provider: string, kind: string, display_name: string, secret_ref: SecretRef, 
/**
 * Free-form JSON context (username, scopes, role ARN, etc.). Stored
 * verbatim; frontend types it by `provider`.
 * ts-rs has no `TS` impl for `serde_json::Value`, so this needs an
 * explicit type. `Record<string, unknown>` rather than bare `unknown`:
 * `default_context_json` is `{}` and every writer stores an object, so
 * the hand-written declaration's narrower type was accurate and emitting
 * `unknown` would lose real information (the same mistake a bare
 * `string` would be for a closed-set field).
 */
context: Record<string, unknown>, status: string, created_at: number, updated_at: number, };
