// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `install.cancel`.
 *
 * `error` is genuinely `string | null`, NOT an optional property: the handler
 * writes an explicit `Value::Null` on success, so the key is always present.
 * The hand-written stub declared it `error?: string`, which said the key could
 * be absent — it never is. Generating the type corrects that.
 */
export type InstallCancelResult = { success: boolean, error: string | null, };
