// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallCheckReq = { providerId: string, cliCommand: string, 
/**
 * npm package name, so the check can also report which version is
 * installed (read from that package's `package.json` in the per-version
 * cache). Optional: callers that only care about presence may omit it,
 * and every provider whose catalog entry has no `npmPackage` never had a
 * managed install to inspect in the first place.
 */
npmPackage: string | null, };
