// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutPreviewTab } from "./LayoutPreviewTab";

export type LayoutPreviewResult = { name: string, 
/**
 * Saved by this install and in its layouts folder: its terminal commands
 * may run without asking. Anything else asks first.
 */
trusted: boolean, tabs: Array<LayoutPreviewTab>, 
/**
 * Terminal commands in the file.
 */
commands: Array<string>, 
/**
 * What can't be reproduced here, or was left out.
 */
notes: Array<string>, };
