// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayoutOpenResult = { 
/**
 * The tabs that were created, in order.
 */
tab_ids: Array<string>, 
/**
 * What couldn't be reproduced, including agents that didn't start.
 */
notes: Array<string>, };
