// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

/**
 * Response for `listeditordir`. `path` is the canonicalized directory, which
 * is not necessarily the `path` the caller sent — `~` and symlinks are
 * resolved.
 */
export type ListEditorDirResult = { path: string, entries: Array<DirEntry>, };
