// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListRunsReq = { drone_id: string, 
/**
 * `serde(default)`, so a caller may omit it -- which ts-rs cannot express
 * on a non-`Option` field. The stub derives `ListDroneRunsInput` from the
 * generated type to restore that; see the comment there.
 */
limit: number, };
