// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `lspstop`. Refcount-decrement; the server exits at zero.
 */
export type LspStopReq = { server_id: string, };
