// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `lspstart`. The backend resolves the workspace root from
 * `file_path` rather than trusting the client to send one.
 */
export type LspStartReq = { language: string, file_path: string, };
