// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `lspsend`.
 */
export type LspSendReq = { server_id: string, 
/**
 * An arbitrary LSP JSON-RPC message. The backend is a dumb proxy here —
 * it re-serializes this and writes it to the server's stdin without
 * inspecting it — so `unknown` is the honest TS type, and the
 * hand-written stub already said so. `serde_json::Value` would generate
 * as the crate's JSON alias, which is wider and less accurate about the
 * fact that nothing may be assumed about the contents.
 */
message: unknown, };
