// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.get`, `mcp.delete`, `mcp.probe` — one server row within an agent.
 */
export type McpAgentItemData = { agent_id: string, id: string, };
