// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.list`, `mcp.catalog.list_for_agent`.
 */
export type McpAgentScopeData = { agent_id: string, };
