// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.bind`, `mcp.unbind`, `mcp.catalog.bind`, `mcp.catalog.unbind`.
 * `mcp_id`, not `id`: the row being addressed is the server, not the binding.
 */
export type McpAgentBindingData = { agent_id: string, mcp_id: string, };
