// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.catalog.bind_to_bundle`, `mcp.catalog.unbind_from_bundle`.
 */
export type McpBundleBindingData = { bundle_id: string, mcp_id: string, };
