// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the three bind commands. Was an inline `json!({ "bound": true })`
 * — a literal, never computed, because binding is idempotent and any real
 * failure returns `Err`.
 */
export type McpBindResult = { bound: boolean, };
