// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.catalog.delete`, `mcp.catalog.probe` — window-scoped, so no agent key.
 */
export type McpCatalogItemData = { id: string, };
