// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.catalog.list` — window-scoped with no parameters. A struct rather than
 * `()`, because the stub calls it with `{}` and serde deserializes `()` only
 * from JSON `null`.
 */
export type McpCatalogListData = Record<string, never>;
