// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `mcp.delete` and `mcp.catalog.delete`. Both were inline
 * `json!({ "deleted": .. })`. False means no row with that id existed — the
 * delete is idempotent, so this is "was something removed", not an error.
 */
export type McpDeleteResult = { deleted: boolean, };
