// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the three unbind commands. Unlike `bound`, this one IS computed:
 * false means there was no binding to remove.
 */
export type McpUnbindResult = { unbound: boolean, };
