// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reply to `memorydelivery:claim_fallback`: `false` when Claude Code's
 * `SessionStart` hook already delivered this event.
 */
export type MemoryDeliveryClaimFallbackResult = { deliver: boolean, };
