// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of the most recent `identity-mismatch` audit entry for this
 * agent_id, if any (see #2695's `Handler::inject_message_inner` check) —
 * narrowed from `AuditLogEntry` to what the Stash badge needs.
 */
export type MismatchAuditSummary = { timestamp: number, block_id: string, error_message: string | null, };
