// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `movescratchfile`. The canonical destination, which differs
 * from the requested `destination_path` whenever that path went through a
 * symlink or `~`.
 */
export type MoveScratchFileResult = { file_path: string, };
