// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MuxBusStatusResp = { connected: boolean, email: string, cognitoDomain: string, expiresAt: number, valid: boolean, };
