// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MuxBusDeliveryState } from "./MuxBusDeliveryState";

/**
 * `muxbus.status`'s `delivery`, and the payload of the `muxbus:status`
 * event sent whenever it changes. Times are this computer's clock (unix ms).
 */
export type MuxBusDeliveryStatus = { state: MuxBusDeliveryState, 
/**
 * When `state` began.
 */
since_ms: number, 
/**
 * When the relay last answered this channel.
 */
last_ok_ms?: number, 
/**
 * Why messages aren't arriving, in a few words.
 */
last_error?: string, 
/**
 * The account this channel is (or was last) signed in as.
 */
account_email?: string, };
