// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where `muxbus.cloudconfig`'s settings came from.
 */
export type MuxBusCloudConfigSource = "discovered" | "default";
