// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `muxbus.disconnect`. Was an inline `json!({})`; the stub already
 * typed it `Record<string, never>`, which is exactly what an empty struct
 * generates.
 */
export type MuxBusDisconnectResp = Record<string, never>;
