// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty request shapes for `muxbus.login.cancel`, `muxbus.status` and
 * `muxbus.disconnect`. The handlers ignore their payload, but these must be
 * structs rather than `()`: the stub calls all three with `{}`, and serde
 * deserializes `()` only from JSON `null`, so a unit Req would reject every
 * real call at runtime while compiling and passing every CI gate -- the
 * `bookmarks.list` bug.
 */
export type MuxBusLoginCancelReq = Record<string, never>;
