// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MuxBusDeliveryStatus } from "./MuxBusDeliveryStatus";

export type MuxBusStatusResp = { connected: boolean, email: string, cognitoDomain: string, expiresAt: number, valid: boolean, 
/**
 * The stored sign-in can't work anymore and only a new sign-in helps:
 * the refresh was refused, or it was issued by a client the cloud no
 * longer publishes (SPEC_CLOUD_SETTINGS_DISCOVERY_2026_09_27.md §3.3).
 * The UI shows "Sign in again" with `email`.
 */
needsReauth: boolean, 
/**
 * Whether cloud messages are reaching this channel's agents
 * (`muxbus::delivery_status`); live changes arrive as the
 * `muxbus:status` event. Always present from this srv.
 */
delivery?: MuxBusDeliveryStatus, };
