// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MuxBusCloudConfigSource } from "./MuxBusCloudConfigSource";

/**
 * Result of `muxbus.cloudconfig`: the AgentMux Cloud settings srv resolved
 * (SPEC_CLOUD_SETTINGS_DISCOVERY_2026_09_27.md §3.2). A build compiled
 * without a Cognito client id asks this whether sign-in is possible anyway.
 */
export type MuxBusCloudConfigResp = { source: MuxBusCloudConfigSource, 
/**
 * The relay REST base srv uses. Always `relay::rest_base_url()`, the
 * root of trust the document is fetched from, whatever the document says.
 */
api: string, 
/**
 * The relay WebSocket URL the cloud subscriber connects to.
 */
ws: string, 
/**
 * The Cloud Console URL; empty when none is published.
 */
console: string, 
/**
 * The Cognito hosted-UI domain and desktop client id `muxbus.login`
 * prefers over the ones in its request. Empty with `source: "default"`:
 * srv has no compiled sign-in settings, only the frontend build does.
 */
cognitoDomain: string, clientId: string, region: string, userPoolId: string, };
