// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where cloud delivery stands.
 */
export type MuxBusDeliveryState = "signed_out" | "connected" | "reconnecting" | "needs_sign_in";
