// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MuxBusLoginResp = { success: boolean, email: string, 
/**
 * skip_serializing_if, so the key is OMITTED on success rather than
 * carrying null -- `error?: string`, which is what the hand-written
 * inline type already said.
 */
error?: string, };
