// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MuxBusLoginCancelResp = { 
/**
 * False when there was no in-flight login to cancel (already resolved,
 * or never started) — not an error, just nothing to do.
 */
cancelled: boolean, };
