// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeMemoryAdoptionList } from "./NativeMemoryAdoptionList";

export type NativeMemoryAdoptionListResult = { 
/**
 * `None` until the agent has a verified memory folder (its first spawn,
 * or a working directory).
 */
list: NativeMemoryAdoptionList | null, };
