// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeMemoryVersionMeta } from "./NativeMemoryVersionMeta";

export type NativeMemoryRevertResult = { 
/**
 * The newly created version (source `"revert"`) whose content now
 * matches `target_version_id` — the prior latest version is left
 * untouched, per the version chain's append-only guarantee.
 */
version: NativeMemoryVersionMeta, };
