// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NativeMemoryAdoptionFile = { name: string, size: number, modified_ms: number, sha256: string, };
