// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NativeMemoryDiffResult = { 
/**
 * A minimal line-based diff: one line per input line, prefixed `"  "`
 * (context), `"- "` (removed, present in `from` only), or `"+ "`
 * (added, present in `to` only). No `@@` hunk headers in v1.
 */
diff: string, };
