// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeMemoryAdoptionFile } from "./NativeMemoryAdoptionFile";

/**
 * One folder offered for adoption. No path: the client refers to it by
 * `index` and `dir_hash`.
 */
export type NativeMemoryAdoptionCandidate = { index: number, 
/**
 * The account the folder belongs to (its identity folder), `default`
 * for the unlinked default home, or `held` for files in the agent's own
 * folder held at first sighting because another agent's record has
 * the same content (§2.1.2).
 */
account: string, 
/**
 * Changes whenever a file in the folder is added, removed or changed.
 */
dir_hash: string, files: Array<NativeMemoryAdoptionFile>, };
