// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NativeMemoryClaimedFolder = { index: number, 
/**
 * The folder, when the claim recorded it.
 */
dir: string | null, claimed_at_ms: number, 
/**
 * Other agents claiming it too (it is shared while they do).
 */
others: number, };
