// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeMemoryAdoptionCandidate } from "./NativeMemoryAdoptionCandidate";

export type NativeMemoryAdoptionList = { list_id: string, agent_uid: string, candidates: Array<NativeMemoryAdoptionCandidate>, };
