// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NativeMemoryAdoptReport = { 
/**
 * Files the record didn't have, now adopted.
 */
files_added: number, 
/**
 * Other bodies kept as history.
 */
versions_kept: number, 
/**
 * Lines added to MEMORY.md.
 */
index_lines_added: number, };
