// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for one `*.md` file in the agent's native memory folder.
 */
export type NativeMemoryFileMeta = { filename: string, 
/**
 * True only for `MEMORY.md` (the Claude Code index file).
 */
is_index: boolean, 
/**
 * Parsed from YAML frontmatter `type:` field. Null when absent.
 */
metadata_type: string | null, size_bytes: number, 
/**
 * Unix timestamp in milliseconds.
 */
modified_at: number, };
