// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeMemoryVersionMeta } from "./NativeMemoryVersionMeta";

export type NativeMemoryHistoryResult = { 
/**
 * Newest first — matches `agent_native_memory_version_list`'s own
 * ordering.
 */
versions: Array<NativeMemoryVersionMeta>, };
