// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeMemoryFileMeta } from "./NativeMemoryFileMeta";

export type NativeMemoryListResult = { files: Array<NativeMemoryFileMeta>, 
/**
 * The folder was found by a guess (a blank working directory and no
 * spawn on record), not from the agent's own launch: shown read-only
 * until the agent launches (SPEC_MEMORY_FOLLOWS_THE_AGENT_2026_09_24.md
 * §2.1.2).
 */
unverified: boolean, };
