// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCounts } from "./TokenCounts";

/**
 * Response from session:next_prompt_suggestion. The FRONTEND writes
 * `term:next_prompt_suggestion` to block meta after receiving this response
 * (useNextPromptSuggestion.ts) — the handler itself never touches block
 * meta, same as session:activity_summary's handler (see the inline comment
 * at its call site in `register_session_activity_summary`). `tokens` is
 * `None` under the same conditions as ActivitySummaryResult.tokens.
 */
export type NextPromptSuggestionResult = { suggestion: string, tokens?: TokenCounts, };
