// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for the four commands that ignore their payload: `appinfo`,
 * `getwaveairatelimit`, `eventunsuball` and `getfullconfig`.
 *
 * One type for all four rather than four identical empty structs: there is
 * nothing to diverge, and three names for "no arguments" is noise. Registered
 * as `Option<Self>`, which is what makes both encodings of "no argument"
 * deserialize — the stub sends `{}`, a client that omits `data` sends `null`,
 * and serde accepts each from only one of `()` and a struct.
 */
export type NoArgsReq = Record<string, never>;
