// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotifyAttentionItem } from "./NotifyAttentionItem";

/**
 * Snapshot the tray renders (§4.2).
 */
export type NotifyTrayState = { attention: Array<NotifyAttentionItem>, paused_until_ms: number, };
