// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotifyKind } from "./NotifyKind";

/**
 * One shown Attention item, for the tray's "needs you" submenu. Titles are
 * app-controlled templates, so they are safe to show in a native menu.
 */
export type NotifyAttentionItem = { id: string, block_id: string, title: string, 
/**
 * Lets surfaces treat kinds differently — e.g. only `InputWaiting`
 * flashes the taskbar (spec Phase 4).
 */
kind: NotifyKind, };
