// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotifyTakeActivationParams = { 
/**
 * The asking window's workspace; only a click for that workspace is
 * handed over.
 */
workspace_id?: string, };
