// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `notify.attention`: the calls to action srv holds open now
 * (`backend/user_attention.rs`), each as its `userattention` event's data.
 */
export type NotifyAttentionResult = { attention: Array<unknown>, };
