// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotifyAckResult = { 
/**
 * False when the click's window isn't open — an older launcher opens a
 * window; the new one picks the pane up via `notify.takeactivation`.
 */
has_window: boolean, 
/**
 * The acked id named a live notification.
 */
known: boolean, 
/**
 * Raise this window (a connected frontend's `Window` oid).
 */
window_id?: string, 
/**
 * No window shows the pane: open one on this workspace.
 */
workspace_id?: string, };
