// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of notification kinds. A source cannot invent a new visual
 * treatment — every kind has an app-controlled title template (§9.1).
 */
export type NotifyKind = "input_waiting" | "turn_completed" | "turn_errored" | "agent_crashed" | "message_needs_review" | "summary" | "test";
