// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotifyFocusParams = { window_focused: boolean, block_id?: string, 
/**
 * This window's own `Window` oid, so srv knows which windows are open.
 */
window_id?: string, };
