// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `openinshell`. Reveals a path in the OS file manager.
 */
export type OpenInShellReq = { path: string, };
