// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool's resolution in `resolve.prereqs`.
 */
export type PrereqToolResolution = { tool: string, found: boolean, 
/**
 * Always present, null when the tool was not found.
 */
path: string | null, };
