// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `presence.publish-now`.
 */
export type PresencePublishNowResult = { 
/**
 * False when the publisher isn't running on this install.
 */
started: boolean, };
