// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the publisher stands.
 */
export type PresenceState = "signed_out" | "publishing" | "retrying" | "unsupported" | "rejected";
