// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an install doesn't publish (`PresenceState::Off`).
 */
export type PresenceOffReason = "setting" | "dev_build" | "headless" | "isolated_home" | "test_harness";
