// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceOffReason } from "./PresenceOffReason";
import type { PresenceState } from "./PresenceState";

/**
 * `presence.status`. Times are this computer's clock (unix ms).
 */
export type PresenceStatusResult = { state: PresenceState, 
/**
 * When the publisher entered `state`.
 */
since_ms: number, 
/**
 * When a record was last stored.
 */
last_ok_ms?: number, 
/**
 * Why the last try failed, in a few words.
 */
last_error?: string, 
/**
 * When the next try is due; absent while signed out.
 */
next_try_ms?: number, 
/**
 * The relay's version, from its health check.
 */
relay_version?: string, 
/**
 * The relay's clock minus this computer's, from its last answer.
 */
offset_ms?: number, 
/**
 * The record version the publisher sends: 2, or 1 for an older relay.
 */
record_version: number, 
/**
 * Something worth showing beside the state: a clock that differs from
 * the relay's, or an older relay that gets no agent states.
 */
note?: string, 
/**
 * Why nothing is published, while `off`.
 */
off_reason?: PresenceOffReason, };
