// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModel } from "./CatalogModel";

export type ProvidersModelsResult = { 
/**
 * `CatalogModel` serializes to `{ id, display_name }`.
 */
models: Array<CatalogModel>, };
