// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One cross-instance/channel entry from the host-global shared registry
 * (`backend::reactive::registry::AgentEntry`), narrowed to what the
 * frontend actually needs to render a "registered elsewhere too" badge —
 * deliberately excludes `local_url`/`auth_key`, which are internal
 * forwarding plumbing, not UI-relevant.
 */
export type RemoteRegistrationEntry = { channel: string, pid: number, updated_at: number, };
