// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemotePlatform = { 
/**
 * `linux`, `macos`, or the lowercased `uname -s` for anything else.
 */
os: string, 
/**
 * `x86_64` or `arm64` for the common machines; otherwise as printed.
 */
arch: string, };
