// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteHelper = { 
/**
 * `installed`, `absent`, `never` (the user said never), `unsupported` (no
 * build for the platform), or `none` (WSL has no helper).
 */
state: string, 
/**
 * The AgentMux version whose helper last answered (when installed).
 */
version: string, };
