// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteHelper } from "./RemoteHelper";
import type { RemotePlatform } from "./RemotePlatform";
import type { RemoteStatus } from "./RemoteStatus";

/**
 * One remote machine, as the Remotes pane shows it.
 */
export type RemoteRecord = { 
/**
 * The connection name, as a pane's `connection` meta takes it.
 */
name: string, 
/**
 * `ssh` or `wsl`.
 */
kind: string, 
/**
 * Where AgentMux knows it from: `ssh_config`, `settings`, `recent`, `wsl`.
 */
sources: Array<string>, status: RemoteStatus, 
/**
 * From the host's `uname -sm`, once AgentMux has seen it.
 */
platform: RemotePlatform | null, helper: RemoteHelper, 
/**
 * Durable sessions on the host when last listed; `null` if never listed.
 */
sessions: number | null, 
/**
 * Agents the user has always allowed on this host.
 */
agents: Array<string>, 
/**
 * Its `connections.<name>` settings, as stored.
 */
settings: Record<string, unknown>, 
/**
 * When it last reached `connected` (recent connections only), Unix ms.
 */
last_used_ms: number | null, };
