// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `remotetest` found.
 */
export type RemoteTestResult = { ok: boolean, 
/**
 * ssh's own message when it failed.
 */
message: string, };
