// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `renameeditorfile`. The resolved absolute path, which is not
 * simply `old_path`'s parent joined with `new_name`: `old_path` is
 * canonicalized first, so symlinks are already resolved here.
 */
export type RenameEditorFileResult = { new_path: string, };
