// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `reseedagents`. Was an inline
 * `json!({ "deleted": .., "created": .., "skipped": .. })`.
 *
 * The hand-written stub typed this command `Promise<void>`, so the counts the
 * server already returns were invisible to the frontend. Surfacing them rather
 * than dropping them: whether the UI uses them is a product question, but the
 * binding should say what the wire carries.
 */
export type ReseedAgentsResult = { deleted: number, created: number, skipped: number, };
