// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result from ResolveCliCommand
 */
export type ResolveCliResult = { 
/**
 * Absolute path to the CLI binary
 */
cli_path: string, 
/**
 * CLI version string
 */
version: string, 
/**
 * How it was resolved: "path", "local_install", "installed"
 */
source: string, };
