// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `resolve.prereqs`. Was a function-local anonymous struct.
 */
export type ResolvePrereqsReq = { tools: Array<string>, };
