// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the pane's progress list while the preflight runs — same shape as
 * the launcher splash's stage rows.
 */
export type ResumePreflightStep = { id: string, label: string, 
/**
 * `false` is normal — it's how the sequence narrows, not an error.
 */
ok: boolean, detail: string, duration_ms: number, };
