// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result from RunCliLoginCommand
 */
export type RunCliLoginResult = { 
/**
 * OAuth URL extracted from the CLI's output (open in browser)
 */
auth_url: string | null, raw_output: string, };
