// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-specific credential reference. Stored as JSON in
 * `db_accounts.secret_ref`. `backend` is the discriminator.
 * The actual secret value is NEVER stored in the DB — only how to
 * look it up at launch time (env var, secrets-manager path, etc.).
 * `PlaintextDev` exists for local dev convenience and must never be
 * the default path in production builds.
 */
export type SecretRef = { "backend": "env", env_var: string, } | { "backend": "secrets_manager", sm_path: string, sm_json_path?: string, } | { "backend": "plaintext_dev", plaintext_dev: string, } | { "backend": "oauth_config_dir", 
/**
 * Absolute path to the per-bundle, per-provider config
 * directory — e.g. `~/.agentmux/shared/identities/<id>/claude/`,
 * or the legacy `~/.claude/` for the Default migration bundle
 * (PR E).
 */
dir: string, } | { "backend": "keychain", 
/**
 * Keychain service string — always `"agentmux"`.
 */
service: string, 
/**
 * Keychain account string — `"acct:<account_id>"`.
 */
account: string, };
