// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResumePreflightStep } from "./ResumePreflightStep";

/**
 * Response from session:resume_preflight.
 */
export type SessionResumePreflightResult = { block_id: string, 
/**
 * `"resume" | "recover" | "fresh" | "unknown"`.
 */
verdict: "resume" | "recover" | "fresh" | "unknown", 
/**
 * The session that would actually load, when one would.
 */
session_id?: string, 
/**
 * A real session on disk that the next spawn will NOT reach for — set
 * only alongside `"fresh"`, as evidence that history exists even though
 * nothing will load it.
 */
recoverable_session_id?: string, steps: Array<ResumePreflightStep>, duration_ms: number, };
