// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from session:export.
 */
export type SessionExportResult = { 
/**
 * base64-encoded JSONL content (the raw output file bytes).
 */
content: string, line_count: number, byte_count: number, };
