// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from session:restore.
 */
export type SessionRestoreResult = { block_id: string, restored_bytes: number, };
