// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `shellstop`. Was an inline `json!({ "stopped": .. })`.
 *
 * `false` means "no live registry entry for that id", which covers both
 * "already exited" and "never existed" -- the caller cannot tell them apart,
 * and does not need to: either way there is nothing left to stop.
 */
export type ShellStopResult = { stopped: boolean, };
