// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.catalog.list_for_bundle`.
 */
export type SkillBundleScopeData = { bundle_id: string, };
