// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `skill.delete` and `skill.catalog.delete`. Both were an inline
 * `json!({ "deleted": .. })`.
 *
 * `deleted` is false when no row with that id existed — the delete is
 * idempotent, so this is "was something actually removed", not an error flag.
 */
export type SkillDeleteResult = { deleted: boolean, };
