// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.catalog.bind_to_bundle`, `skill.catalog.unbind_from_bundle`.
 */
export type SkillBundleBindingData = { bundle_id: string, skill_id: string, };
