// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.get`, `skill.delete` — one skill row addressed within an agent.
 */
export type SkillAgentItemData = { agent_id: string, id: string, };
