// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.catalog.delete` — window-scoped, so no agent or bundle key.
 */
export type SkillCatalogItemData = { id: string, };
