// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.bind`, `skill.unbind`, `skill.catalog.bind`, `skill.catalog.unbind` —
 * attach/detach a catalog skill to an agent. `skill_id` rather than `id`
 * because the row being addressed is the skill, not the binding.
 */
export type SkillAgentBindingData = { agent_id: string, skill_id: string, };
