// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `skill.catalog.list` — window-scoped with no parameters. Still a struct
 * rather than `()`: the stub calls it with `{}` and serde deserializes `()`
 * only from JSON `null`, so a unit Req would reject every real call while
 * compiling and passing every CI gate (the `bookmarks.list` bug).
 */
export type SkillCatalogListData = Record<string, never>;
