// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Caps blast radius on a bulk-stop: targets are stopped in batches of
 * `batch_size`; if the failure rate within a completed batch exceeds
 * `max_fail_percentage`, remaining batches are skipped. A simplified,
 * fixed-batch-size take on Ansible's `serial` + `max_fail_percentage`
 * (spec §3/§5.3) — not the full canary-then-widen ladder, which is more
 * generality than a first version needs.
 */
export type StagePlanInput = { batch_size: number, max_fail_percentage: number, };
