// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartProviderAuthReq = { providerId: string, 
/**
 * Vestigial — bundle mode (a successful auth adding an account to
 * an Identity bundle) was retired in Phase 4c of
 * SPEC_PRESET_TO_BUNDLE_REFACTOR_2026_07_02.md. Kept on the wire
 * shape only; `direct_account` is always true in practice.
 */
intoBundleId?: string, 
/**
 * Always `true` in practice — `AuthFlowController` (the sole
 * frontend caller) hardcodes `directAccount: true`. A successful
 * auth persists a standalone `IdentityAccount`; the actual
 * agent<->account link is written later, once the agent exists, by
 * the launch-flow reconcile.
 */
directAccount: boolean, 
/**
 * Direct-account reconnect: non-empty to refresh an already-
 * linked account's tokens in place (same isolation dir, same
 * account row updated). Empty mints a fresh account id. Ignored
 * unless `direct_account` is set.
 */
existingAccountId: string, 
/**
 * Resolved CLI path. The frontend calls `resolvecli` first to
 * install / locate the provider's CLI; the resulting path is
 * passed here. Keeps the provider table single-sourced in the
 * frontend.
 */
cliPath: string, 
/**
 * e.g. `["auth", "login"]` from the provider definition's
 * `authLoginCommand` field.
 */
authLoginArgs: Array<string>, 
/**
 * e.g. `["auth", "status", "--json"]` — used to confirm
 * authentication after the CLI emits its success line.
 */
authCheckArgs: Array<string>, 
/**
 * Env vars to inject at spawn time. Per-provider auth
 * isolation env vars come here (CLAUDE_CONFIG_DIR, CODEX_HOME,
 * GEMINI_CLI_HOME, etc.).
 */
authEnv: { [key in string]?: string }, 
/**
 * Spawn the auth login subprocess under a PTY (instead of plain
 * piped stdio). Required by providers whose auth subcommand
 * checks `isatty()` and refuses to run otherwise (currently
 * OpenClaw's `models auth login --provider <id>`). The flag is
 * forwarded down to the CEF host's `run_cli_login` which picks
 * the PTY branch when set.
 */
requiresTty: boolean, };
