// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmitAuthCallbackReq = { sessionId: string, 
/**
 * The redirect URL the user pasted back (browser-didn't-open
 * fallback). The handler writes it to the spawned CLI's stdin.
 */
callbackUrl: string, };
