// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmitProviderApiKeyReq = { providerId: string, 
/**
 * Optional — same semantics as StartProviderAuth.into_bundle_id.
 */
intoBundleId?: string, 
/**
 * The API key the user pasted. Will be validated by running the
 * provider's authCheckCommand against it, then persisted as a
 * `SecretRef::PlaintextDev` (PR 1 of the storage spec) or
 * encrypted variant (PR 2).
 */
apiKey: string, accountName: string, };
