// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

export type ToolStatusEntry = { id: string, display: string, description: string, tier: number, status: ToolStatus, version: string | null, path: string | null, };
