// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in `toolchain.versions`' request.
 */
export type ToolchainPackage = { 
/**
 * Caller-chosen key. The response is keyed by this, not by `package`, so
 * a caller asking about the same npm package under two ids gets two
 * answers.
 */
id: string, 
/**
 * npm package name.
 */
package: string, };
