// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `toolchain.prune`: find, and optionally remove, installed provider
 * CLIs that nothing has used for a long time and nothing is running.
 */
export type ToolchainPruneReq = { 
/**
 * Omitted or `true`: only report what WOULD be removed. Deleting needs an
 * explicit `false`, so a call that forgot the field cannot delete anything.
 */
dry_run?: boolean, };
