// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directory left alone at removal time, and why.
 */
export type ToolchainPruneSkip = { dir: string, reason: string, };
