// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `toolchain.prune`: find, and optionally remove, installed provider
 * CLIs that nothing has used for a long time and nothing is running.
 */
export type ToolchainPruneReq = { 
/**
 * Omitted or `true`: only report what WOULD be removed. Deleting needs an
 * explicit `false`, so a call that forgot the field cannot delete anything.
 */
dry_run?: boolean, 
/**
 * With `dry_run: false`: remove only these directories (as listed by an
 * earlier dry run), and only those that are STILL removable. Anything that
 * became removable since is not touched, so a removal is exactly the list
 * the user saw. Omitted: everything removable now.
 */
only?: Array<string>, };
