// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One installed CLI directory.
 */
export type ToolchainPruneItem = { dir: string, provider: string, 
/**
 * The pinned CLI version of a shared install, or the AgentMux version of a legacy one.
 */
version: string, 
/**
 * A pre-2026-09-27 per-AgentMux-version install (`instances/v<version>/cli`).
 */
legacy: boolean, bytes: number, 
/**
 * Whole days since the install was last used (or installed).
 */
idle_days: number, };
