// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The whole machine's totals, without its process list: what lets the
 * Agents view's rail add up to the machine ("Everything else" is the machine
 * less every task). SPEC_TOWER_AGENT_CENTRIC_VIEWS_2026_10_08.md §3.1.
 */
export type TowerMachine = { 
/**
 * All processes' CPU, fraction of one core; absent on a first sample.
 */
cpu?: number, 
/**
 * All processes' private memory, bytes.
 */
mem: number, processes: number, };
