// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TowerHost } from "./TowerHost";
import type { TowerMachine } from "./TowerMachine";
import type { TowerTask } from "./TowerTask";

/**
 * `tower.sample`.
 */
export type TowerSnapshot = { ts_ms: number, hostname: string, 
/**
 * `windows`, `macos` or `linux`.
 */
os: string, 
/**
 * Logical CPUs on the machine.
 */
cpu_count: number, 
/**
 * What `mem` measures here ("private working set", …).
 */
memory_metric: string, 
/**
 * How often to ask again while the pane is visible.
 */
interval_ms: number, 
/**
 * Another machine's (`TowerSampleReq::connection`): no tasks, no
 * command lines.
 */
remote: boolean, tasks: Array<TowerTask>, 
/**
 * This computer's (or a paired one's) totals, on every sample.
 */
machine?: TowerMachine, 
/**
 * Present when the request asked for it.
 */
host?: TowerHost, };
