// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TowerProcessRole } from "./TowerProcessRole";

/**
 * One process. CPU is a fraction of one core since the previous sample
 * (1.0 = one core fully busy); the pane divides by `cpu_count` for "percent
 * of the machine". Absent values are ones the OS wouldn't give without
 * elevation, never zeros.
 */
export type TowerProcess = { 
/**
 * `pid:start`, unique across PID reuse.
 */
id: string, pid: number, ppid?: number, name: string, started_at_ms?: number, cpu?: number, 
/**
 * Private memory, bytes (`TowerSnapshot::memory_metric`).
 */
mem?: number, 
/**
 * Working set / resident set, shared pages included.
 */
mem_resident?: number, 
/**
 * Committed private bytes (Windows).
 */
mem_commit?: number, 
/**
 * In a task's list: its part in the task.
 */
role?: TowerProcessRole, 
/**
 * In the host list: the task it belongs to (`TowerTask::id`), if any.
 */
task?: string, 
/**
 * One of AgentMux's own processes: what it is ("GPU", "Renderer",
 * "Network service", "Server", "Launcher", …). Absent for any other
 * process, and for one of AgentMux's the backend can't place.
 */
detail?: string, 
/**
 * CPU time used so far (user + kernel), nanoseconds: for an exited
 * process, all it used.
 */
cpu_time_ns?: number, 
/**
 * The most private memory seen while it was sampled, bytes.
 */
peak_mem?: number, 
/**
 * In a task's `exited` list: when it was first seen gone, unix ms.
 */
exited_ms?: number, 
/**
 * The agent tool call this process runs, as the agent described it
 * ("Run the srv tests"): set on the wrapper at the root of the call's
 * process tree (`backend::tool_calls`).
 */
started_by?: string, };
