// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tower.forget`: a `TowerPeerInfo::connection`.
 */
export type TowerForgetReq = { connection: string, };
