// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TowerProcessRole } from "./TowerProcessRole";

/**
 * One process. CPU is a fraction of one core since the previous sample
 * (1.0 = one core fully busy); the pane divides by `cpu_count` for "percent
 * of the machine". Absent values are ones the OS wouldn't give without
 * elevation, never zeros.
 */
export type TowerProcess = { 
/**
 * `pid:start`, unique across PID reuse; what `tower.command-line` takes.
 */
id: string, pid: number, ppid?: number, name: string, started_at_ms?: number, cpu?: number, 
/**
 * Private memory, bytes (`TowerSnapshot::memory_metric`).
 */
mem?: number, 
/**
 * Working set / resident set, shared pages included.
 */
mem_resident?: number, 
/**
 * Committed private bytes (Windows).
 */
mem_commit?: number, 
/**
 * In a task's list: its part in the task.
 */
role?: TowerProcessRole, 
/**
 * In the host list: the task it belongs to (`TowerTask::id`), if any.
 */
task?: string, };
