// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Another AgentMux computer this one is paired with (`tower.peers`).
 */
export type TowerPeerInfo = { 
/**
 * What `TowerSampleReq::connection` takes: `peer:<id>`.
 */
connection: string, hostname: string, 
/**
 * Where it was last reached, `address:port`.
 */
address: string, paired_ms: number, };
