// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tower.sample`'s request.
 */
export type TowerSampleReq = { 
/**
 * Also list every process on the machine (the Host view).
 */
host?: boolean, };
