// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TowerProcess } from "./TowerProcess";
import type { TowerTaskKind } from "./TowerTaskKind";

/**
 * A pane and every process it started, or AgentMux itself.
 */
export type TowerTask = { 
/**
 * The block id, or `agentmux`.
 */
id: string, kind: TowerTaskKind, 
/**
 * The agent's name, or what the pane runs.
 */
label: string, 
/**
 * How its processes were found: `high` (a Job Object or cgroup nothing
 * escapes), `best_effort` (a process scan; a detached child may be
 * missed) or `tree` (descendants of the pane's process).
 */
tracking: string, 
/**
 * Fraction of one core. Where `cpu_account` is set it includes members
 * that exited since the previous sample.
 */
cpu?: number, cpu_account: boolean, 
/**
 * Summed private memory of the processes the OS measured, bytes.
 */
mem: number, processes: Array<TowerProcess>, };
