// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tower.command-line`. Absent when the process has exited (or a new one has
 * its PID) or the OS won't say.
 */
export type TowerCommandLineResult = { command_line?: string, };
