// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing started, or joined, a turn (turn-model spec §5.2).
 * Display data next to [`TurnOrigin`], which stays the security class.
 */
export type TriggerKind = "user" | "broadcast" | "agent" | "service" | "schedule" | "task" | "system";
