// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnEnd } from "./TurnEnd";
import type { TurnOrigin } from "./TurnOrigin";
import type { TurnTrigger } from "./TurnTrigger";

/**
 * The turn as the user sees it: from leaving idle to returning to it with
 * nothing queued, over however many CLI passes that took (turn-model spec
 * §3.1, §4.3). Published as `agentturn` on every change; the pane's parser is
 * typed against the generated `frontend/types/rpc/TurnLedger.ts`.
 */
export type TurnLedger = { 
/**
 * Unique per block: the start time in ms, bumped past the previous id.
 */
turn_id: number, 
/**
 * Bumped on every change, under the tracker's lock. Publishes run after
 * the lock is released, so two can land out of order; the pane keeps the
 * highest `seq` (#4492).
 */
seq: number, 
/**
 * What started the turn; `None` when its first pass was unlabelled.
 */
origin?: TurnOrigin, 
/**
 * The same, for display: what kind of thing, and who.
 */
trigger?: TurnTrigger, 
/**
 * The labelled inputs that arrived after the turn started, in order,
 * up to [`ABSORBED_CAP`].
 */
absorbed: Array<TurnTrigger>, started_at_ms: number, 
/**
 * CLI passes so far, the running one included.
 */
passes: number, 
/**
 * A pass is running now.
 */
active: boolean, 
/**
 * Inputs that arrived after the turn started (mid-pass, or starting a
 * pass that joined).
 */
inputs: number, 
/**
 * Passes whose `result` figures are in the sums below. The pane adds
 * its live count for the running pass only while that pass isn't
 * counted yet, so a pass is never counted twice.
 */
counted_passes: number, 
/**
 * Summed over the counted passes' `result` frames.
 */
output_tokens: number, cost_usd: number, 
/**
 * Model calls (`result.num_turns`, which counts steps, not turns).
 */
steps: number, duration_api_ms: number, last_pass_ended_at_ms?: number, 
/**
 * Between passes, while a next pass is expected: the turn is over if
 * none starts by then.
 */
settle_until_ms?: number, ended_at_ms?: number, end?: TurnEnd, };
