// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who delivered input to an agent (SPEC_AGENT_SELF_QUIT_2026_09_24.md §6.3).
 */
export type TurnOrigin = "user" | "automated" | "system";
