// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerKind } from "./TriggerKind";

/**
 * What started, or joined, a turn: its kind, and who or what, for display.
 * Built by srv from what it wrote itself (the jekt marker it composed, the
 * CLI's task notification), never from message body text.
 */
export type TurnTrigger = { kind: TriggerKind, 
/**
 * The sender (a jekt's `FROM`), or the task's summary. Absent for the user.
 */
from?: string, 
/**
 * `kind.is_external()`, carried so readers don't keep their own list.
 */
external: boolean, };
