// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `unlinkagentidentity`. Was an inline `json!({ "unlinked": .. })`.
 * False means there was no link to remove — the unlink is idempotent, so this
 * is "was something actually removed", not an error flag.
 */
export type UnlinkAgentIdentityResult = { unlinked: boolean, };
