// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `unwatchmediadir`.
 *
 * Separate from `WatchMediaDirReq` rather than shared, because unwatching
 * really does take fewer fields: the registration is keyed on
 * (path, block_id) and the extension filter is not part of the key.
 */
export type UnwatchMediaDirReq = { path: string, block_id: string, };
