// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationIssue } from "./ValidationIssue";

export type ValidationReport = { 
/**
 * True when `issues` contains no `Error`-severity entries. Warnings
 * alone do not affect this — they're surfaced but non-blocking.
 */
is_valid: boolean, issues: Array<ValidationIssue>, };
