// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSeverity } from "./IssueSeverity";

export type ValidationIssue = { severity: IssueSeverity, 
/**
 * Which bundle field/component this issue is about — one of
 * "instructions_by_provider", "context_files", "mcp_servers", "skills".
 */
field: string, message: string, };
