// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSeverity } from "./IssueSeverity";

export type ValidationIssue = { severity: IssueSeverity, 
/**
 * Which bundle field/component this issue is about:
 * "instructions_by_provider" or "context_files".
 */
field: string, message: string, };
