// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `viewer.pair-start`: the `agentmux://pair` URL the QR carries, and when its
 * code stops working (unix ms).
 */
export type ViewerPairStartResult = { url: string, expires_ms: number, };
