// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewerDeviceInfo } from "./ViewerDeviceInfo";

export type ViewerDevicesResult = { devices: Array<ViewerDeviceInfo>, };
