// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One paired device in `viewer.devices`.
 */
export type ViewerDeviceInfo = { device_id: string, device_name: string, created_ms: number, 
/**
 * 0 until the device's first request after pairing.
 */
last_seen_ms: number, };
