// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `voice.checkPath` response. Was an anonymous `json!({"exists": ..})`
 * before this type existed to name it for the generator.
 */
export type VoiceCheckPathResult = { exists: boolean, };
