// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `watchmediadir`.
 */
export type WatchMediaDirReq = { path: string, block_id: string, 
/**
 * Lowercase, no leading dot. Only files matching one of these raise
 * `media:file_changed`.
 */
extensions: Array<string>, };
