// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for `watcheditorfile` AND `unwatcheditorfile`.
 *
 * Deliberately one type for both, unlike `CreateEditorFileReq` /
 * `CreateEditorDirReq` which are separate despite having identical fields.
 * The difference is that these two must address the SAME thing: an unwatch
 * that does not name exactly what the watch named leaks a watcher. Sharing
 * the type makes that a compile error rather than a leak.
 */
export type WatchEditorFileReq = { path: string, 
/**
 * Scopes the `editor:file_changed` event to `block:<block_id>`, and is
 * half of the watch key -- two panes watching one path each hold their
 * own registration.
 */
block_id: string, };
