// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetPackageInfo } from "./WidgetPackageInfo";
import type { WidgetPublisherPin } from "./WidgetPublisherPin";

export type WidgetPackagesResult = { packages: Array<WidgetPackageInfo>, 
/**
 * Publishers pinned to a key here (SPEC_WIDGET_SHARING_2026_10_10.md §2.2).
 */
publishers: Array<WidgetPublisherPin>, };
