// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `widget.api`.
 *
 * `ok` is about the HTTP exchange completing, NOT about the status code: a
 * 500 is `ok: true` with `status_code: 500`. `ok: false` means transport
 * failure or a rejected port/path, and then `error` is set.
 */
export type WidgetApiResult = { ok: boolean, status_code: number | null, body: string | null, error?: string, };
