// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WidgetPaneInfo = { 
/**
 * `ext:<id>/<name>` (or a v1 widget's own `ext:<name>`).
 */
view: string, name: string, label: string, icon: string, entry: string, singleton: boolean, default_meta: Record<string, unknown>, };
