// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WidgetInstallReq = { 
/**
 * A package folder, its `widget.json`, or a `.zip`.
 */
path: string, 
/**
 * Replace an installed package with the same id.
 */
replace: boolean, };
