// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetKind } from "./WidgetKind";

export type WidgetInstallRequest = { id: string, hash: string, name: string, version: string, description: string | null, kind: WidgetKind, permissions: Array<string>, 
/**
 * The agent that asked.
 */
agent: string, requested_ms: number, };
