// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetCommandInfo } from "./WidgetCommandInfo";
import type { WidgetKind } from "./WidgetKind";
import type { WidgetPaneInfo } from "./WidgetPaneInfo";
import type { WidgetState } from "./WidgetState";
import type { WidgetStatusItemInfo } from "./WidgetStatusItemInfo";

export type WidgetPackageInfo = { id: string, name: string, version: string, description: string | null, author: string | null, homepage: string | null, icon: string, default_hue: number | null, kind: WidgetKind, permissions: Array<string>, 
/**
 * Permissions the user granted, when approved (an update that asks for
 * more is `changed` until approved again).
 */
granted: Array<string>, state: WidgetState, error: string | null, 
/**
 * The current content hash (empty when the files couldn't be read).
 */
hash: string, panes: Array<WidgetPaneInfo>, commands: Array<WidgetCommandInfo>, status_items: Array<WidgetStatusItemInfo>, 
/**
 * Where its files are served, ending in `/`, while it is approved and
 * enabled; relative to srv's web endpoint.
 */
files_url: string | null, 
/**
 * A v1 `widgets.json` module entry, shown as an implied package.
 */
implied: boolean, folder: string, };
