// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A publisher pinned to a key, for Settings.
 */
export type WidgetPublisherPin = { publisher: string, fingerprint: string, };
