// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetInstallRequest } from "./WidgetInstallRequest";

export type WidgetRequestsResult = { requests: Array<WidgetInstallRequest>, };
