// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetCatalogEntry } from "./WidgetCatalogEntry";
import type { WidgetState } from "./WidgetState";

/**
 * An entry as Settings shows it: the entry, its publisher's fingerprint,
 * and what is installed here.
 */
export type WidgetCatalogItem = { entry: WidgetCatalogEntry, fingerprint: string, installed_version: string | null, installed_state: WidgetState | null, 
/**
 * Installed here at exactly the catalog's files.
 */
current: boolean, };
