// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `widget.health`.
 *
 * `healthy: false` is a normal answer, not an error: connection-refused and
 * timeout both land here rather than failing the RPC, because "is this widget
 * up" has a legitimate negative answer.
 *
 * The REQUEST stays a `serde_json::Value` read field-by-field. That is not an
 * oversight: the handler clamps a bad port and a bad path into
 * `healthy: false` answers instead of rejecting them, and a typed request
 * would turn those into deserialize errors. Registering `Value` as the request
 * type keeps that tolerance exactly while still recording this response type —
 * which `register_handler` could not do.
 */
export type WidgetHealthResult = { healthy: boolean, 
/**
 * Null when the exchange never produced one (refused, timed out, or the
 * port/path was rejected before any request was made).
 */
status_code: number | null, };
