// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusAlignment } from "./StatusAlignment";

/**
 * A status bar item, before any pane of the widget updates it.
 */
export type WidgetStatusItemInfo = { id: string, text: string, icon: string, tooltip: string | null, command: string | null, alignment: StatusAlignment, };
