// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A palette command, as the UI registers it (spec §6.8).
 */
export type WidgetCommandInfo = { id: string, title: string, icon: string, 
/**
 * The view of the pane it runs in.
 */
view: string, keywords: string, };
