// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetCatalogItem } from "./WidgetCatalogItem";

/**
 * The widget catalog, checked, with what is installed here
 * (SPEC_WIDGET_SHARING_2026_10_10.md §4.5).
 */
export type WidgetCatalogResult = { url: string, items: Array<WidgetCatalogItem>, };
