// Copyright 2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

//! Auto-start-at-login registration — issue #2977 Workstream 2,
//! `docs/specs/SPEC_TRAY_OPTIONAL_BACKGROUND_SERVICE_2026_09_04.md` §4.
//!
//! ## Opt-in, off by default, and separate from "close to tray"
//!
//! Nothing here runs unless the user explicitly asks for it. The issue is
//! emphatic that these are two different decisions: "a user can have
//! 'close-to-tray keeps it running for this session' without 'starts
//! automatically at every login' being bundled into the same toggle". So
//! auto-start has its own state, its own enable/disable, and is never
//! implied by `AGENTMUX_TRAY` or `AGENTMUX_BACKGROUND_SERVICE`.
//!
//! ## Mechanism per platform, and what was rejected
//!
//! - **Windows — Scheduled Task, `LogonType=InteractiveToken`.** Not a
//!   Windows Service (needs admin to register, and Session-0 isolation means
//!   it structurally cannot show a tray icon), and not a bare `Run` registry
//!   key (no crash supervision, no delay control).
//! - **macOS — LaunchAgent plist.** `SMAppService` is the modern API but is
//!   only callable from inside a signed, bundled app via its ObjC/Swift
//!   interface; the launcher writes the LaunchAgent directly so the same code
//!   path works for the portable build too. Both land in the same place from
//!   `launchd`'s point of view.
//! - **Linux — XDG autostart `.desktop`.** `systemd --user` is deliberately
//!   NOT the default: surviving logout needs `loginctl enable-linger`, which
//!   is a separate, consequential decision the issue says must never be
//!   silently enabled.
//!
//! ## Uninstall is a first-class operation (Workstream 4)
//!
//! WS4 requires "one complete, independently-testable uninstall path that
//! actually removes the LaunchAgent/Scheduled-Task/autostart artifact — not
//! just closes the window". `disable()` is that path, and `is_enabled()`
//! makes it independently checkable: the pair is the whole contract, and
//! `disable()` is idempotent so an uninstaller can call it unconditionally.
//!
//! ## Structure
//!
//! The artifact *content* (Task Scheduler XML, plist, desktop entry) is
//! generated by pure functions that take an exe path and return a string.
//! That keeps the part most likely to be subtly wrong — escaping, schema
//! fields, the `InteractiveToken` logon type — unit-testable without
//! touching the machine's real login configuration.

use std::path::Path;

/// Identifier used for the artifact on every platform: the Scheduled Task
/// name, the LaunchAgent label's suffix, and the `.desktop` filename stem.
/// Stable, because `disable()` has to find what `enable()` created —
/// including across upgrades, so it deliberately carries no version.
pub const AUTOSTART_ID: &str = "AgentMux";

/// Reverse-DNS label for the macOS LaunchAgent, which requires that form.
pub const MACOS_LABEL: &str = "com.agentmux.launcher";

/// Windows Task Scheduler registration XML.
///
/// `LogonType=InteractiveToken` is the load-bearing detail (issue WS2): it
/// runs the task as the logged-in user *in their interactive session*, which
/// is what lets the process own a tray icon and later spawn visible windows.
/// `RunLevel=LeastPrivilege` keeps it out of elevation prompts — auto-start
/// must not require admin.
///
/// `<Delay>PT30S</Delay>` staggers startup behind the desktop's own login
/// work; a background service racing Explorer for disk on every boot is a
/// bad citizen, and 30s is invisible for something meant to run all day.
///
/// `DisallowStartIfOnBatteries`/`StopIfGoingOnBatteries` are both false
/// deliberately: the defaults are *true*, which would make a laptop user's
/// background service silently not start, or die mid-turn on unplug — the
/// exact "is it actually running?" unreliability WS4 warns about.
pub fn scheduled_task_xml(exe: &Path) -> String {
    let exe = xml_escape(&exe.display().to_string());
    format!(
        r#"<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Starts AgentMux in the background at logon. Created by AgentMux; remove it by turning off auto-start in AgentMux, or with: schtasks /Delete /TN "{id}" /F</Description>
    <URI>\{id}</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT30S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>"{exe}"</Command>
      <Arguments>--background</Arguments>
    </Exec>
  </Actions>
</Task>
"#,
        id = AUTOSTART_ID,
        exe = exe
    )
}

/// macOS LaunchAgent plist.
///
/// `RunAtLoad` starts it at login. `KeepAlive` is deliberately **false**: the
/// launcher already supervises `srv`/`host` and owns its own restart policy,
/// so letting `launchd` also restart it would give two supervisors fighting
/// over the same process — and would make a user-requested Quit from the tray
/// come straight back, which is worse than useless.
pub fn launch_agent_plist(exe: &Path) -> String {
    let exe = xml_escape(&exe.display().to_string());
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{exe}</string>
        <string>--background</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>ProcessType</key>
    <string>Interactive</string>
</dict>
</plist>
"#,
        label = MACOS_LABEL,
        exe = exe
    )
}

/// Linux XDG autostart desktop entry.
///
/// `X-GNOME-Autostart-enabled=true` is included because some desktops treat a
/// missing value as disabled. `Terminal=false` keeps it from spawning a
/// console window on desktops that honor it.
pub fn xdg_desktop_entry(exe: &Path) -> String {
    // Desktop-entry values are newline-delimited; a newline in the path would
    // otherwise inject a second key. Paths containing newlines are pathological
    // but cheap to neutralize.
    let exe = exe.display().to_string().replace(['\n', '\r'], "");
    format!(
        "[Desktop Entry]\n\
         Type=Application\n\
         Name=AgentMux\n\
         Comment=Starts AgentMux in the background at login\n\
         Exec=\"{exe}\" --background\n\
         Terminal=false\n\
         X-GNOME-Autostart-enabled=true\n"
    )
}

/// Minimal XML text escaping for the two generated XML documents.
///
/// Only the five predefined entities matter here, and the only untrusted-ish
/// input is a filesystem path (which can legitimately contain `&` and, on
/// Unix, `<`/`>`/quotes). Hand-rolled rather than pulling an XML crate into a
/// binary the codebase deliberately keeps tiny — the same reasoning
/// `second_instance.rs` gives for hand-rolling its HTTP request.
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(c),
        }
    }
    out
}

/// Where the artifact lives, for the platforms that use a plain file.
/// `None` on Windows, whose artifact lives in the Task Scheduler store rather
/// than a path we own.
pub fn artifact_path() -> Option<std::path::PathBuf> {
    #[cfg(target_os = "macos")]
    {
        let home = std::env::var("HOME").ok()?;
        Some(
            Path::new(&home)
                .join("Library/LaunchAgents")
                .join(format!("{}.plist", MACOS_LABEL)),
        )
    }
    #[cfg(target_os = "linux")]
    {
        // Honor XDG_CONFIG_HOME; fall back to the spec's default.
        let base = std::env::var("XDG_CONFIG_HOME")
            .ok()
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| format!("{}/.config", std::env::var("HOME").unwrap_or_default()));
        Some(
            Path::new(&base)
                .join("autostart")
                .join(format!("{}.desktop", AUTOSTART_ID.to_lowercase())),
        )
    }
    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        None
    }
}

/// Is auto-start currently registered?
///
/// Half of the WS4 uninstall contract: an uninstall path is only
/// "independently testable" if something can answer this without trusting
/// whatever wrote it. So this inspects the real system state (the Task
/// Scheduler store, or the artifact file) rather than any bookkeeping of our
/// own.
pub fn is_enabled() -> bool {
    #[cfg(target_os = "windows")]
    {
        // `schtasks /Query` exits non-zero when the task does not exist.
        std::process::Command::new("schtasks")
            .args(["/Query", "/TN", AUTOSTART_ID])
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    }
    #[cfg(not(target_os = "windows"))]
    {
        artifact_path().map(|p| p.exists()).unwrap_or(false)
    }
}

/// Register auto-start for `exe`. Idempotent: re-registering an existing
/// entry replaces it, which is also how an upgrade repoints the artifact at a
/// new install path.
pub fn enable(exe: &Path) -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        // Register from XML — the only way to set LogonType/battery settings;
        // the flag-based `schtasks /Create /SC ONLOGON` form cannot express
        // them. The XML must be UTF-16 per the Task Scheduler schema
        // declaration, so it is written as UTF-16LE with a BOM.
        let xml = scheduled_task_xml(exe);
        let dir = std::env::temp_dir();
        let path = dir.join(format!("agentmux-autostart-{}.xml", std::process::id()));
        let mut bytes: Vec<u8> = vec![0xFF, 0xFE]; // UTF-16LE BOM
        for unit in xml.encode_utf16() {
            bytes.extend_from_slice(&unit.to_le_bytes());
        }
        std::fs::write(&path, &bytes).map_err(|e| format!("write task xml: {}", e))?;

        // Capture output rather than discarding it: schtasks reports schema
        // and permission problems on stderr, and an autostart registration
        // that fails with only "exit code 1" is undiagnosable for a user or
        // in a bug report.
        let out = std::process::Command::new("schtasks")
            .args(["/Create", "/TN", AUTOSTART_ID, "/XML"])
            .arg(&path)
            .arg("/F") // replace an existing registration
            .output();
        // Best-effort cleanup; the temp file is harmless if it survives.
        let _ = std::fs::remove_file(&path);

        match out {
            Ok(o) if o.status.success() => Ok(()),
            Ok(o) => Err(format!(
                "schtasks /Create failed ({}): {}{}",
                o.status,
                String::from_utf8_lossy(&o.stderr).trim(),
                String::from_utf8_lossy(&o.stdout).trim()
            )),
            Err(e) => Err(format!("run schtasks: {}", e)),
        }
    }
    #[cfg(not(target_os = "windows"))]
    {
        let path = artifact_path().ok_or_else(|| "unsupported platform".to_string())?;
        let contents = if cfg!(target_os = "macos") {
            launch_agent_plist(exe)
        } else {
            xdg_desktop_entry(exe)
        };
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create {}: {}", parent.display(), e))?;
        }
        std::fs::write(&path, contents).map_err(|e| format!("write {}: {}", path.display(), e))
    }
}

/// Remove auto-start registration. **Idempotent** — succeeds when nothing was
/// registered, so an uninstaller can call it unconditionally without first
/// asking whether the feature was ever turned on.
///
/// This is the WS4 "complete uninstall path": it removes the actual
/// Scheduled Task / LaunchAgent / desktop entry, not merely some internal
/// flag. `is_enabled()` afterwards is the independent check that it worked.
pub fn disable() -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        if !is_enabled() {
            return Ok(());
        }
        match std::process::Command::new("schtasks")
            .args(["/Delete", "/TN", AUTOSTART_ID, "/F"])
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
        {
            Ok(s) if s.success() => Ok(()),
            Ok(s) => Err(format!("schtasks /Delete failed: {}", s)),
            Err(e) => Err(format!("run schtasks: {}", e)),
        }
    }
    #[cfg(not(target_os = "windows"))]
    {
        let Some(path) = artifact_path() else {
            return Ok(());
        };
        match std::fs::remove_file(&path) {
            Ok(()) => Ok(()),
            // Already gone is success, not an error — that is what makes this
            // safe to call unconditionally from an uninstaller.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(format!("remove {}: {}", path.display(), e)),
        }
    }
}

#[cfg(test)]
mod autostart_tests {
    use super::*;
    use std::path::PathBuf;

    fn exe() -> PathBuf {
        PathBuf::from(r"C:\Program Files\AgentMux\agentmux.exe")
    }

    #[test]
    fn scheduled_task_uses_interactive_token_not_a_service_account() {
        // The whole reason WS2 specifies a Scheduled Task over a Windows
        // Service: Session-0 isolation means a service can never own a tray
        // icon or show a window. InteractiveToken is what puts it in the
        // user's own session.
        let xml = scheduled_task_xml(&exe());
        assert!(xml.contains("<LogonType>InteractiveToken</LogonType>"));
        assert!(
            xml.contains("<RunLevel>LeastPrivilege</RunLevel>"),
            "auto-start must never require elevation"
        );
    }

    #[test]
    fn scheduled_task_survives_battery_power() {
        // Task Scheduler defaults BOTH of these to true, which would make a
        // laptop user's "background service" silently fail to start on
        // battery, or die mid-turn on unplug — the unreliable-indicator
        // failure WS4 exists to prevent.
        let xml = scheduled_task_xml(&exe());
        assert!(xml.contains("<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>"));
        assert!(xml.contains("<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>"));
    }

    #[test]
    fn scheduled_task_has_no_execution_time_limit() {
        // PT0S = unlimited. The default is 72 hours, after which Task
        // Scheduler would terminate a long-running background service.
        let xml = scheduled_task_xml(&exe());
        assert!(xml.contains("<ExecutionTimeLimit>PT0S</ExecutionTimeLimit>"));
    }

    #[test]
    fn generated_xml_escapes_paths() {
        // Install paths can contain `&` (and on Unix, quotes/angle brackets).
        // Unescaped, that produces XML that Task Scheduler rejects — or worse,
        // silently misparses.
        let xml = scheduled_task_xml(Path::new(r"C:\Tools & Apps\<agentmux>.exe"));
        assert!(xml.contains("Tools &amp; Apps"));
        assert!(xml.contains("&lt;agentmux&gt;"));
        assert!(
            !xml.contains("Tools & Apps"),
            "raw ampersand would make the document invalid"
        );
    }

    #[test]
    fn launch_agent_does_not_let_launchd_resurrect_a_user_quit() {
        // KeepAlive=false is deliberate: the launcher owns its own restart
        // policy, and a tray Quit that launchd immediately undid would be
        // worse than having no Quit at all.
        let plist = launch_agent_plist(Path::new("/Applications/AgentMux.app/Contents/MacOS/agentmux"));
        assert!(plist.contains("<key>RunAtLoad</key>\n    <true/>"));
        assert!(plist.contains("<key>KeepAlive</key>\n    <false/>"));
        assert!(plist.contains(MACOS_LABEL));
    }

    #[test]
    fn xdg_entry_is_a_valid_autostart_desktop_file() {
        let d = xdg_desktop_entry(Path::new("/opt/agentmux/agentmux"));
        assert!(d.starts_with("[Desktop Entry]\n"));
        assert!(d.contains("Type=Application\n"));
        assert!(d.contains("X-GNOME-Autostart-enabled=true\n"));
        assert!(
            d.contains("Exec=\"/opt/agentmux/agentmux\" --background\n"),
            "Exec must quote the path so spaces don't split the command"
        );
    }

    #[test]
    fn xdg_entry_cannot_be_injected_with_extra_keys_via_the_path() {
        // A newline in the path would otherwise terminate the Exec= line and
        // let the rest be parsed as further desktop-entry keys.
        let d = xdg_desktop_entry(Path::new("/opt/x\nHidden=true"));
        assert!(!d.contains("\nHidden=true\n"), "newline must not survive into the file");
    }

    /// Full enable → is_enabled → disable → is_enabled round trip against the
    /// REAL platform registry (Task Scheduler / LaunchAgents / XDG autostart).
    ///
    /// `#[ignore]` on purpose: it mutates the machine's actual login
    /// configuration, which is not something a plain `cargo test` — least of
    /// all one on a shared CI runner — should ever do as a side effect. Run it
    /// deliberately:
    ///
    /// ```text
    /// cargo test -p agentmux-launcher --release -- --ignored autostart_round_trip
    /// ```
    ///
    /// This is the WS4 "independently-testable uninstall path" made literal:
    /// it verifies removal by asking the platform, not by trusting our own
    /// bookkeeping. Self-cleaning — it disables at the end, and asserts the
    /// artifact is actually gone.
    #[test]
    #[ignore = "mutates real login configuration; run explicitly with --ignored"]
    fn autostart_round_trip_against_the_real_platform_registry() {
        // Refuse to run if the user already has autostart configured, rather
        // than clobbering (and then deleting) their real registration.
        assert!(
            !is_enabled(),
            "autostart already enabled on this machine — refusing to overwrite a real registration"
        );

        let exe = std::env::current_exe().expect("current_exe");
        enable(&exe).expect("enable should succeed");
        assert!(is_enabled(), "enable() must be observable through the platform");

        // Idempotent re-enable (the upgrade path: repoint at a new exe).
        enable(&exe).expect("re-enable should replace, not fail");
        assert!(is_enabled());

        disable().expect("disable should succeed");
        assert!(!is_enabled(), "disable() must actually remove the artifact");

        // Safe to call unconditionally — the property an uninstaller needs.
        disable().expect("disable must be idempotent");
    }

    #[test]
    fn every_platform_artifact_launches_with_the_background_flag() {
        // All three must start the app in background mode; a plain launch
        // would pop a window in the user's face at every login, which is the
        // opposite of what auto-start is for.
        assert!(scheduled_task_xml(&exe()).contains("--background"));
        assert!(launch_agent_plist(&exe()).contains("<string>--background</string>"));
        assert!(xdg_desktop_entry(&exe()).contains("--background"));
    }
}
