// Copyright 2025-2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

//! Native pre-splash for Windows: a borderless layered popup showing the
//! AgentMux brain logo (pulsing) while startup runs, with a live startup
//! telemetry panel below the logo.
//!
//! ## Layout
//!
//! ```
//! ┌─ SPLASH_W × SPLASH_H ────────────────────────────────┐
//! │  solid BG_COLOR                                       │
//! │   ┌─ BRAIN_W × BRAIN_H ─┐  ← brain region            │
//! │   │ brain (pulsing)     │                             │
//! │   └─────────────────────┘                             │
//! │                                                       │
//! │  Saga recovery          23ms                          │
//! │  Migrations          2,341ms                          │
//! │    0001 Legacy data      147ms +                      │
//! │    0009 Transcript     2,187ms +                      │
//! │  Channel pruner          89ms  freed 612 MB           │
//! │  Backend startup        134ms                         │
//! │  CEF init               312ms                         │
//! │  Frontend init    >  0.4s                             │
//! │  ─────────────────────────────────────────────────── │
//! │  area54@DESKTOP-XYZ · v0.49.3                        │  ← footer
//! └──────────────────────────────────────────────────────┘
//! ```
//!
//! Startup telemetry events are delivered via a `std::sync::mpsc::Receiver`
//! passed to `spawn_splash`.  Each animation frame (~60 fps) drains the
//! receiver and updates the stage list.  When the CEF host signals the
//! dismiss Win32 event (from `on_load_end`), the splash freezes, holds for
//! `AGENTMUX_SPLASH_HOLD_MS` ms (default 2000), then fades out.

#![cfg(target_os = "windows")]

use std::thread;
use std::time::Instant;
use windows_sys::Win32::Foundation::*;
use windows_sys::Win32::Graphics::Gdi::*;
use windows_sys::Win32::System::LibraryLoader::GetModuleHandleW;
use windows_sys::Win32::System::Threading::*;
use windows_sys::Win32::UI::WindowsAndMessaging::*;

use crate::startup_events::{StartupEvent, StartupStatus};

// Brain bitmap dimensions generated by build.rs (BRAIN_W = BRAIN_H = 256).
include!(concat!(env!("OUT_DIR"), "/brain_dims.rs"));

const SPLASH_PADDING: i32 = 12;
// Vertical size of the brain-logo region only (280px) — was also the
// window's WIDTH until the fix below (SPLASH_W was `= SPLASH_SIZE`), which
// left only ~28 monospace characters per stage-telemetry row with no
// word-wrap (`splash_text.rs` clips silently past the DIB edge). A staged
// "still starting, first run can take longer" message for the
// suspend->host-registration wait (see tracking issue #2940 — Windows
// Defender's on-execution cloud reputation check for newly-extracted
// binaries can hold this gap open 20+ seconds on a genuinely fresh
// machine) didn't fit. BRAIN_AREA_H keeps the old value for everything
// that used to read SPLASH_SIZE as a *height*; SPLASH_W below is now
// independent and wider.
const BRAIN_AREA_H: i32 = BRAIN_H + SPLASH_PADDING * 2;
// Brain logo is centered horizontally in the now-wider window rather than
// pinned at SPLASH_PADDING — it stays visually centered instead of
// drifting to the left edge.
const BRAIN_X: i32 = (SPLASH_W - BRAIN_W) / 2;
const BRAIN_Y: i32 = SPLASH_PADDING;

// ── Footer ──────────────────────────────────────────────────────────────────
const FOOTER_COLOR: [u8; 3] = [0x8A, 0x8A, 0x93];
const FOOTER_PAD_TOP: i32 = 10;
const FOOTER_LINE_GAP: i32 = 3;
const FOOTER_PAD_BOTTOM: i32 = 12;
const FOOTER_H: i32 = FOOTER_PAD_TOP
    + 2 * crate::splash_font::GLYPH_H as i32
    + FOOTER_LINE_GAP
    + FOOTER_PAD_BOTTOM;

// ── Stage telemetry area (between brain and footer) ─────────────────────────
const STAGE_MARGIN_L: i32 = 14;
const STAGE_MARGIN_R: i32 = 8;
/// Pixel height of a single stage or sub-item row.
const STAGE_ROW_H: i32 = crate::splash_font::GLYPH_H as i32 + 2;
const STAGE_PAD_TOP: i32 = 10;
const STAGE_PAD_BOTTOM: i32 = 6;
/// Maximum rows rendered (6 stages + 6 sub-items).
const MAX_STAGE_ROWS: usize = 12;
const STAGE_AREA_H: i32 =
    STAGE_PAD_TOP + MAX_STAGE_ROWS as i32 * STAGE_ROW_H + STAGE_PAD_BOTTOM;

// Stage label character budget (truncated if longer).
const LABEL_MAX_CHARS: usize = 16;
const SUB_LABEL_MAX_CHARS: usize = 14;

// Colors
const STAGE_COLOR: [u8; 3] = [0xC0, 0xC0, 0xCC];
const TIME_DONE_COLOR: [u8; 3] = [0x60, 0xCC, 0x80];
const TIME_RUN_COLOR: [u8; 3] = [0x70, 0x90, 0xFF];
const SUB_COLOR: [u8; 3] = [0x7A, 0x7A, 0x82];
const STATUS_OK_COLOR: [u8; 3] = [0x44, 0xBB, 0x44];
const STATUS_ERR_COLOR: [u8; 3] = [0xCC, 0x44, 0x44];
const STATUS_WARN_COLOR: [u8; 3] = [0xCC, 0xAA, 0x33];
const SEP_B: u8 = 0x36;
const SEP_G: u8 = 0x36;
const SEP_R: u8 = 0x36;

// ── Window geometry ─────────────────────────────────────────────────────────
// Widened from the old `= SPLASH_SIZE` (280px, ~28 chars/row) to comfortably
// fit a one-line staged status message (~43 chars/row) without word-wrap.
// See BRAIN_AREA_H's comment above for why.
const SPLASH_W: i32 = 460;
const SPLASH_H: i32 = BRAIN_AREA_H + STAGE_AREA_H + FOOTER_H;

const BG_B: u8 = 0x1F;
const BG_G: u8 = 0x1A;
const BG_R: u8 = 0x1A;

// Darkened window-edge border — SPEC_SPLASH_SCREEN_BORDER_2026_08_25.md.
// Roughly half BG's RGB values, a straightforward "darker than the
// backdrop" reading; not yet confirmed against a real display.
const BORDER_B: u8 = 0x10;
const BORDER_G: u8 = 0x0D;
const BORDER_R: u8 = 0x0D;
const BORDER_WIDTH: i32 = 2;

static BRAIN_BGRA: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/brain_bgra.bin"));

struct SendHandle(HANDLE);
unsafe impl Send for SendHandle {}
impl SendHandle {
    fn take(self) -> HANDLE { self.0 }
}

// ── Stage list state ─────────────────────────────────────────────────────────

struct SubRow {
    id: String,
    label: String,
    started_at: Instant,
    /// (duration_ms, status, detail) when complete.
    done: Option<(u64, StartupStatus, Option<String>)>,
}

struct StageRow {
    stage: &'static str,
    label: &'static str,
    started_at: Instant,
    done: Option<(u64, StartupStatus, Option<String>)>,
    subs: Vec<SubRow>,
}

fn apply_event(stages: &mut Vec<StageRow>, ev: StartupEvent) {
    match ev {
        StartupEvent::StageBegin { stage, label } => {
            stages.push(StageRow {
                stage,
                label,
                started_at: Instant::now(),
                done: None,
                subs: Vec::new(),
            });
        }
        StartupEvent::StageEnd { stage, duration_ms, status, detail } => {
            if let Some(row) = stages.iter_mut().rev().find(|r| r.stage == stage) {
                row.done = Some((duration_ms, status, detail));
            }
        }
        StartupEvent::SubBegin { stage, id, label } => {
            if let Some(row) = stages.iter_mut().rev().find(|r| r.stage == stage) {
                row.subs.push(SubRow {
                    id,
                    label,
                    started_at: Instant::now(),
                    done: None,
                });
            }
        }
        StartupEvent::SubEnd { stage, id, duration_ms, status, detail } => {
            if let Some(row) = stages.iter_mut().rev().find(|r| r.stage == stage) {
                if let Some(sub) = row.subs.iter_mut().rev().find(|s| s.id == id) {
                    sub.done = Some((duration_ms, status, detail));
                }
            }
        }
    }
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Spawn the pre-splash thread.  Returns the named Win32 event name to pass
/// to the CEF host as `AGENTMUX_SPLASH_EVENT` (host signals it from
/// `on_load_end` to trigger hold → fade-out).
///
/// `events_rx` delivers `StartupEvent` messages from the launcher startup
/// path; the splash thread consumes them each frame.
///
/// SPEC_PILLAR1_STEP4 Phase 4 — `restoring` draws a "Restoring session…"
/// headline (a fresh concept, distinct from the stage-telemetry rows) in
/// place of stage row 0. Set by crash-restart call sites
/// (`supervisor/windows.rs`), which call this again — a brand-new Win32
/// event object plus a brand-new consumer thread — rather than reusing the
/// original cold-start splash's already-exited one (see that module for why
/// the original design silently produced no visible splash on restart: the
/// event name was re-passed to the host, but nothing was listening on it
/// anymore once the first splash's thread had already exited).
pub fn spawn_splash(
    dir_hash: &str,
    events_rx: std::sync::mpsc::Receiver<StartupEvent>,
    restoring: bool,
) -> Option<String> {
    let event_name = format!("AgentMuxSplash-{}", dir_hash);
    let nul_name: Vec<u16> = format!("{}\0", event_name).encode_utf16().collect();

    let ev = unsafe {
        CreateEventW(std::ptr::null(), 1, 0, nul_name.as_ptr())
    };
    if ev.is_null() {
        crate::log("splash: CreateEventW failed — skipping splash");
        return None;
    }

    let class_name = format!("AgentMuxSplash-{}", dir_hash);
    let handle = SendHandle(ev);
    thread::spawn(move || unsafe { run_splash(handle.take(), class_name, events_rx, restoring) });
    Some(event_name)
}

/// Signal an existing splash's dismiss event by name, same mechanism the CEF
/// host uses from `on_load_end` (`agentmux-cef/src/client/navigation.rs`).
/// Used by the crash-restart path (`supervisor/windows.rs`) to tear down the
/// PREVIOUS restart's splash before spawning a new one — otherwise that
/// thread stays blocked in `run_splash`'s `WaitForSingleObject` loop forever
/// (the host that was supposed to dismiss it crashed before ever calling
/// `on_load_end`), leaking its thread/HWND/GDI objects and, since each
/// restart now gets its own uniquely-named event (reagent P1, PR #2032,
/// 2026-07-08), stacking a visible duplicate splash window on screen.
/// Fire-and-forget: a missing/already-signaled event is not an error.
pub fn dismiss_splash(event_name: &str) {
    let nul_name: Vec<u16> = format!("{}\0", event_name).encode_utf16().collect();
    unsafe {
        let ev = OpenEventW(EVENT_MODIFY_STATE, 0, nul_name.as_ptr());
        if !ev.is_null() {
            SetEvent(ev);
            CloseHandle(ev);
        }
    }
}

// ── Internals ────────────────────────────────────────────────────────────────

unsafe fn run_splash(
    dismiss_ev: HANDLE,
    class_name: String,
    events_rx: std::sync::mpsc::Receiver<StartupEvent>,
    restoring: bool,
) {
    let class: Vec<u16> = format!("{}\0", class_name).encode_utf16().collect();
    let hinst = GetModuleHandleW(std::ptr::null());

    let wc = WNDCLASSEXW {
        cbSize: std::mem::size_of::<WNDCLASSEXW>() as u32,
        style: 0,
        lpfnWndProc: Some(DefWindowProcW),
        cbClsExtra: 0,
        cbWndExtra: 0,
        hInstance: hinst,
        hIcon: std::ptr::null_mut(),
        hCursor: std::ptr::null_mut(),
        hbrBackground: std::ptr::null_mut(),
        lpszMenuName: std::ptr::null(),
        lpszClassName: class.as_ptr(),
        hIconSm: std::ptr::null_mut(),
    };
    RegisterClassExW(&wc);

    let sw = GetSystemMetrics(SM_CXSCREEN);
    let sh = GetSystemMetrics(SM_CYSCREEN);
    let x = (sw - SPLASH_W) / 2;
    let y = (sh - SPLASH_H) / 2;

    let hwnd = CreateWindowExW(
        WS_EX_LAYERED | WS_EX_TOPMOST | WS_EX_TOOLWINDOW | WS_EX_NOACTIVATE,
        class.as_ptr(),
        std::ptr::null(),
        WS_POPUP,
        x, y, SPLASH_W, SPLASH_H,
        std::ptr::null_mut(),
        std::ptr::null_mut(),
        hinst,
        std::ptr::null(),
    );
    if hwnd.is_null() {
        CloseHandle(dismiss_ev);
        return;
    }

    let screen_dc = GetDC(std::ptr::null_mut());
    let mem_dc = CreateCompatibleDC(screen_dc);
    let mut bmi: BITMAPINFO = std::mem::zeroed();
    bmi.bmiHeader.biSize = std::mem::size_of::<BITMAPINFOHEADER>() as u32;
    bmi.bmiHeader.biWidth = SPLASH_W;
    bmi.bmiHeader.biHeight = -SPLASH_H; // top-down
    bmi.bmiHeader.biPlanes = 1;
    bmi.bmiHeader.biBitCount = 32;
    bmi.bmiHeader.biCompression = BI_RGB as u32;

    let mut dib_pixels_raw: *mut core::ffi::c_void = std::ptr::null_mut();
    let dib = CreateDIBSection(
        mem_dc, &bmi, DIB_RGB_COLORS,
        &mut dib_pixels_raw, std::ptr::null_mut(), 0,
    );
    if dib.is_null() || dib_pixels_raw.is_null() {
        ReleaseDC(std::ptr::null_mut(), screen_dc);
        DeleteDC(mem_dc);
        DestroyWindow(hwnd);
        CloseHandle(dismiss_ev);
        return;
    }
    let old_obj = SelectObject(mem_dc, dib as _);

    let dib_pixels = std::slice::from_raw_parts_mut(
        dib_pixels_raw as *mut u8,
        (SPLASH_W * SPLASH_H * 4) as usize,
    );

    ShowWindow(hwnd, SW_SHOWNOACTIVATE);

    let info = crate::splash_info::SplashInfo::gather();
    let max_chars = ((SPLASH_W - 24) / crate::splash_font::GLYPH_W as i32).max(8) as usize;
    let footer = info.footer_lines(max_chars);

    let start = Instant::now();
    let splash_start = Instant::now();
    let mut stages: Vec<StageRow> = Vec::new();

    loop {
        // Drain all pending startup events (non-blocking).
        loop {
            match events_rx.try_recv() {
                Ok(ev) => apply_event(&mut stages, ev),
                Err(_) => break,
            }
        }

        // Check for dismiss signal from CEF host's on_load_end.
        if WaitForSingleObject(dismiss_ev, 0) == WAIT_OBJECT_0 {
            // Drain any final events that arrived at the same time. The
            // dismiss signal (a synchronous Win32 SetEvent) and the last
            // stage-end command (an async message queued on the CEF host
            // side and drained over the launcher IPC pipe by a background
            // task) are sent moments apart on the same call path — SetEvent
            // can win that race, in which case a single non-blocking
            // try_recv() pass here would miss the trailing stage-end and
            // freeze the summary showing that row as still in progress for
            // the whole hold. Keep polling briefly, but only while some row
            // is genuinely still open (`done.is_none()`) — the common case
            // (every stage already resolved) exits immediately, same as
            // before. Reagent PR #2968 review.
            let drain_deadline = Instant::now() + std::time::Duration::from_millis(150);
            loop {
                match events_rx.try_recv() {
                    Ok(ev) => apply_event(&mut stages, ev),
                    Err(_) => {
                        let still_open = stages.iter().any(|s| s.done.is_none());
                        if !still_open || Instant::now() >= drain_deadline {
                            break;
                        }
                        std::thread::sleep(std::time::Duration::from_millis(10));
                    }
                }
            }

            let total_ms = splash_start.elapsed().as_millis() as u64;

            // Freeze: render final state with brain steady.
            composite(dib_pixels, 200u8, &stages, Some(total_ms), &footer, restoring);
            push_layered(hwnd, mem_dc, 255);

            // Summary hold — 2 s default, shortened for very fast starts.
            let hold_ms = std::env::var("AGENTMUX_SPLASH_HOLD_MS")
                .ok()
                .and_then(|v| v.parse::<u64>().ok())
                .unwrap_or(2000);
            let hold_ms = if total_ms < 500 { hold_ms.min(1000) } else { hold_ms };
            if hold_ms > 0 {
                std::thread::sleep(std::time::Duration::from_millis(hold_ms));
            }

            fade_out(hwnd, mem_dc, dib_pixels);
            break;
        }

        // Animate brain alpha: fade-in over 200 ms, then sine pulse.
        let t = start.elapsed().as_secs_f32();
        let brain_alpha: u8 = if t < 0.2 {
            (t / 0.2 * 220.0) as u8
        } else {
            let pulse = (((t - 0.2) * std::f32::consts::TAU * 1.1).sin() + 1.0) * 0.5;
            (160.0 + pulse * 60.0) as u8
        };

        composite(dib_pixels, brain_alpha, &stages, None, &footer, restoring);
        push_layered(hwnd, mem_dc, 255);

        std::thread::sleep(std::time::Duration::from_millis(16)); // ~60 fps
    }

    SelectObject(mem_dc, old_obj);
    DeleteObject(dib as _);
    DeleteDC(mem_dc);
    ReleaseDC(std::ptr::null_mut(), screen_dc);
    DestroyWindow(hwnd);
    CloseHandle(dismiss_ev);
}

/// Compose one frame into the DIB: BG fill → brain → stage list → separator → footer.
fn composite(
    dib: &mut [u8],
    brain_alpha: u8,
    stages: &[StageRow],
    total_ms: Option<u64>,
    footer: &[String],
    restoring: bool,
) {
    // Opaque BG fill.
    for px in dib.chunks_exact_mut(4) {
        px[0] = BG_B;
        px[1] = BG_G;
        px[2] = BG_R;
        px[3] = 0xFF;
    }

    // Brain glyph (pre-multiplied OVER onto BG).
    let ba = brain_alpha as u16;
    for y in 0..BRAIN_H {
        let dib_row = ((BRAIN_Y + y) * SPLASH_W * 4) as usize;
        let src_row = (y * BRAIN_W * 4) as usize;
        for x in 0..BRAIN_W {
            let di = dib_row + ((BRAIN_X + x) * 4) as usize;
            let si = src_row + (x * 4) as usize;
            let sa = BRAIN_BGRA[si + 3] as u16;
            if sa == 0 { continue; }
            let mb = (BRAIN_BGRA[si] as u16 * ba + 127) / 255;
            let mg = (BRAIN_BGRA[si + 1] as u16 * ba + 127) / 255;
            let mr = (BRAIN_BGRA[si + 2] as u16 * ba + 127) / 255;
            let ma = (sa * ba + 127) / 255;
            let inv = 255u16 - ma;
            dib[di]     = ((dib[di] as u16 * inv / 255) + mb).min(255) as u8;
            dib[di + 1] = ((dib[di + 1] as u16 * inv / 255) + mg).min(255) as u8;
            dib[di + 2] = ((dib[di + 2] as u16 * inv / 255) + mr).min(255) as u8;
        }
    }

    // Stage telemetry list.
    draw_stages(dib, stages, total_ms, restoring);

    // Separator line between stage area and footer.
    let sep_y = BRAIN_AREA_H + STAGE_AREA_H - STAGE_PAD_BOTTOM / 2;
    let sep_x0 = STAGE_MARGIN_L;
    let sep_x1 = SPLASH_W - STAGE_MARGIN_R;
    if sep_y >= 0 && sep_y < SPLASH_H {
        for sx in sep_x0..sep_x1 {
            let di = ((sep_y * SPLASH_W + sx) * 4) as usize;
            if di + 3 < dib.len() {
                dib[di] = SEP_B; dib[di + 1] = SEP_G; dib[di + 2] = SEP_R; dib[di + 3] = 0xFF;
            }
        }
    }

    // Footer identity lines.
    let footer_top = SPLASH_H - FOOTER_H + FOOTER_PAD_TOP;
    for (i, line) in footer.iter().enumerate() {
        let y = footer_top + i as i32 * (crate::splash_font::GLYPH_H as i32 + FOOTER_LINE_GAP);
        crate::splash_text::draw_text_centered(dib, SPLASH_W, SPLASH_H, y, line, FOOTER_COLOR, 1.0, true);
    }

    // Darkened window-edge border — drawn last so nothing else (brain,
    // stage list, separator, footer) ever overdraws it. All of that content
    // already keeps its own margin well clear of the outer BORDER_WIDTH
    // pixels (BRAIN_X/Y = SPLASH_PADDING = 12, STAGE_MARGIN_L/R = 14/8), so
    // ordering here is a defensive "last wins" guarantee, not a fix for an
    // otherwise-real overlap. SPEC_SPLASH_SCREEN_BORDER_2026_08_25.md.
    draw_border(dib);
}

fn set_px(dib: &mut [u8], x: i32, y: i32, rgb: (u8, u8, u8)) {
    if x < 0 || x >= SPLASH_W || y < 0 || y >= SPLASH_H {
        return;
    }
    let di = ((y * SPLASH_W + x) * 4) as usize;
    dib[di] = rgb.2; // B
    dib[di + 1] = rgb.1; // G
    dib[di + 2] = rgb.0; // R
    dib[di + 3] = 0xFF;
}

/// Draws a BORDER_WIDTH-thick ring around the window edge. Iterates only
/// the border bands (top/bottom full-width, left/right for the remaining
/// height) rather than the whole SPLASH_W×SPLASH_H frame — this runs every
/// composited frame (~60 fps), so it's worth not scanning interior pixels
/// that never change here.
fn draw_border(dib: &mut [u8]) {
    let rgb = (BORDER_R, BORDER_G, BORDER_B);
    for y in 0..BORDER_WIDTH {
        for x in 0..SPLASH_W {
            set_px(dib, x, y, rgb);
            set_px(dib, x, SPLASH_H - 1 - y, rgb);
        }
    }
    for x in 0..BORDER_WIDTH {
        for y in BORDER_WIDTH..(SPLASH_H - BORDER_WIDTH) {
            set_px(dib, x, y, rgb);
            set_px(dib, SPLASH_W - 1 - x, y, rgb);
        }
    }
}

fn draw_stages(dib: &mut [u8], stages: &[StageRow], total_ms: Option<u64>, restoring: bool) {
    use crate::splash_text::{draw_text, text_width};

    let y0 = BRAIN_AREA_H + STAGE_PAD_TOP;
    let x_label = STAGE_MARGIN_L;
    // Right edge for right-aligned time column.
    let x_time_right = SPLASH_W - STAGE_MARGIN_R;

    let mut row = 0usize;

    // SPEC_PILLAR1_STEP4 Phase 4 — a crash-restart splash has no stage
    // events at all (nothing re-emits "Saga recovery"/"Migrations"/etc. for
    // a restart — see `spawn_splash`'s doc comment), so this headline is
    // the only thing telling the user anything is happening. Takes row 0's
    // slot rather than growing `SPLASH_H`/`MAX_STAGE_ROWS` — the restart
    // splash never has more than one or two real rows anyway (if any).
    if restoring {
        // ASCII only — the bitmap font (`splash_font::FIRST..=LAST`) only
        // covers 0x20-0x7E, so a real ellipsis (U+2026) would render as '?'.
        draw_text(dib, SPLASH_W, SPLASH_H, x_label, y0, "Restoring session...", TIME_RUN_COLOR, 1.0, true);
        row += 1;
    }

    for stage in stages {
        if row >= MAX_STAGE_ROWS { break; }
        let y = y0 + row as i32 * STAGE_ROW_H;

        // Stage label (left-aligned, truncated).
        let label = trunc(stage.label, LABEL_MAX_CHARS);
        draw_text(dib, SPLASH_W, SPLASH_H, x_label, y, &label, STAGE_COLOR, 1.0, true);

        // Time (right-aligned).
        if let Some((ms, _status, _detail)) = &stage.done {
            let t = format_ms(*ms);
            let tx = x_time_right - text_width(&t);
            draw_text(dib, SPLASH_W, SPLASH_H, tx, y, &t, TIME_DONE_COLOR, 1.0, true);
        } else {
            let t = format_running(stage.started_at);
            let tx = x_time_right - text_width(&t);
            draw_text(dib, SPLASH_W, SPLASH_H, tx, y, &t, TIME_RUN_COLOR, 1.0, true);
        }

        row += 1;

        // Sub-rows (indented).
        for sub in &stage.subs {
            if row >= MAX_STAGE_ROWS { break; }
            let y = y0 + row as i32 * STAGE_ROW_H;
            let sub_x = x_label + 2 * crate::splash_font::GLYPH_W as i32;

            let lbl = trunc(&sub.label, SUB_LABEL_MAX_CHARS);
            draw_text(dib, SPLASH_W, SPLASH_H, sub_x, y, &lbl, SUB_COLOR, 1.0, true);

            if let Some((ms, status, _detail)) = &sub.done {
                let t = format_ms(*ms);
                // Status char right of time.
                let status_char = match status {
                    StartupStatus::Ok => "+",
                    StartupStatus::Warn => "!",
                    StartupStatus::Error => "X",
                };
                let sc = x_time_right;
                let tx = sc - crate::splash_font::GLYPH_W as i32 - 2 - text_width(&t);
                draw_text(dib, SPLASH_W, SPLASH_H, tx, y, &t, SUB_COLOR, 1.0, true);
                let sc_color = match status {
                    StartupStatus::Ok => STATUS_OK_COLOR,
                    StartupStatus::Warn => STATUS_WARN_COLOR,
                    StartupStatus::Error => STATUS_ERR_COLOR,
                };
                draw_text(dib, SPLASH_W, SPLASH_H, sc - crate::splash_font::GLYPH_W as i32, y, status_char, sc_color, 1.0, true);
            } else {
                let t = format_running(sub.started_at);
                let tx = x_time_right - text_width(&t);
                draw_text(dib, SPLASH_W, SPLASH_H, tx, y, &t, TIME_RUN_COLOR, 1.0, true);
            }

            row += 1;
        }
    }

    // "total: X.Xs" dim annotation — shown only in hold phase.
    if let Some(ms) = total_ms {
        if row < MAX_STAGE_ROWS {
            let y = y0 + row as i32 * STAGE_ROW_H;
            let total_str = format!("total: {}", format_ms(ms));
            let tx = x_time_right - text_width(&total_str);
            draw_text(dib, SPLASH_W, SPLASH_H, tx, y, &total_str, SUB_COLOR, 1.0, true);
        }
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn trunc(s: &str, max: usize) -> String {
    let chars: Vec<char> = s.chars().collect();
    if chars.len() <= max {
        s.to_string()
    } else {
        chars[..max].iter().collect::<String>() + ".."
    }
}

fn format_ms(ms: u64) -> String {
    if ms >= 10_000 {
        format!("{:.0}s", ms as f64 / 1000.0)
    } else if ms >= 1_000 {
        format!("{:.1}s", ms as f64 / 1000.0)
    } else {
        format!("{}ms", ms)
    }
}

fn format_running(started_at: Instant) -> String {
    let s = started_at.elapsed().as_secs_f32();
    if s >= 10.0 {
        format!("> {:.0}s", s)
    } else {
        format!("> {:.1}s", s)
    }
}

unsafe fn push_layered(hwnd: HWND, mem_dc: HDC, source_alpha: u8) {
    let mut sz = SIZE { cx: SPLASH_W, cy: SPLASH_H };
    let mut src_pt = POINT { x: 0, y: 0 };
    let blend = BLENDFUNCTION {
        BlendOp: AC_SRC_OVER as u8,
        BlendFlags: 0,
        SourceConstantAlpha: source_alpha,
        AlphaFormat: AC_SRC_ALPHA as u8,
    };
    UpdateLayeredWindow(
        hwnd, std::ptr::null_mut(), std::ptr::null(),
        &mut sz, mem_dc, &mut src_pt, 0, &blend, ULW_ALPHA,
    );
}

unsafe fn fade_out(hwnd: HWND, mem_dc: HDC, _dib: &mut [u8]) {
    let mut alpha: i32 = 255;
    while alpha > 0 {
        alpha -= 25;
        if alpha < 0 { alpha = 0; }
        push_layered(hwnd, mem_dc, alpha as u8);
        std::thread::sleep(std::time::Duration::from_millis(16));
    }
}
