// Copyright 2025-2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import { RpcClient } from "./rpc-client";

// WshServerCommandToDeclMap
class RpcApiType {
    // command "activity" [call]
    ActivityCommand(client: RpcClient, data: ActivityUpdate, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("activity", data, opts);
    }

    // command "aisendmessage" [call]
    AiSendMessageCommand(client: RpcClient, data: AiMessageData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("aisendmessage", data, opts);
    }

    // command "authenticate" [call]
    AuthenticateCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        return client.rpcCall("authenticate", data, opts);
    }

    // command "authenticatetoken" [call]
    AuthenticateTokenCommand(client: RpcClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        return client.rpcCall("authenticatetoken", data, opts);
    }

    // command "blockinfo" [call]
    BlockInfoCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<BlockInfoData> {
        return client.rpcCall("blockinfo", data, opts);
    }

    // command "blockslist" [call]
    BlocksListCommand(client: RpcClient, data: BlocksListRequest, opts?: RpcOpts): Promise<BlocksListEntry[]> {
        return client.rpcCall("blockslist", data, opts);
    }

    // command "captureblockscreenshot" [call]
    CaptureBlockScreenshotCommand(client: RpcClient, data: CommandCaptureBlockScreenshotData, opts?: RpcOpts): Promise<string> {
        return client.rpcCall("captureblockscreenshot", data, opts);
    }

    // command "connconnect" [call]
    ConnConnectCommand(client: RpcClient, data: ConnRequest, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("connconnect", data, opts);
    }

    // command "conndisconnect" [call]
    ConnDisconnectCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("conndisconnect", data, opts);
    }

    // command "connensure" [call]
    ConnEnsureCommand(client: RpcClient, data: ConnExtData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("connensure", data, opts);
    }

    // command "connlist" [call]
    ConnListCommand(client: RpcClient, opts?: RpcOpts): Promise<string[]> {
        return client.rpcCall("connlist", null, opts);
    }

    // command "connlistaws" [call]
    ConnListAWSCommand(client: RpcClient, opts?: RpcOpts): Promise<string[]> {
        return client.rpcCall("connlistaws", null, opts);
    }

    // command "connstatus" [call]
    ConnStatusCommand(client: RpcClient, opts?: RpcOpts): Promise<ConnStatus[]> {
        return client.rpcCall("connstatus", null, opts);
    }

    // command "controllerappendoutput" [call]
    ControllerAppendOutputCommand(client: RpcClient, data: CommandControllerAppendOutputData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("controllerappendoutput", data, opts);
    }

    // command "controllerinput" [call]
    ControllerInputCommand(client: RpcClient, data: CommandBlockInputData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("controllerinput", data, opts);
    }

    // command "controllerresync" [call]
    ControllerResyncCommand(client: RpcClient, data: CommandControllerResyncData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("controllerresync", data, opts);
    }

    // command "controllerstop" [call]
    ControllerStopCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("controllerstop", data, opts);
    }

    // command "createblock" [call]
    CreateBlockCommand(client: RpcClient, data: CommandCreateBlockData, opts?: RpcOpts): Promise<ORef> {
        return client.rpcCall("createblock", data, opts);
    }

    // command "createsubblock" [call]
    CreateSubBlockCommand(client: RpcClient, data: CommandCreateSubBlockData, opts?: RpcOpts): Promise<ORef> {
        return client.rpcCall("createsubblock", data, opts);
    }

    // command "deleteblock" [call]
    DeleteBlockCommand(client: RpcClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("deleteblock", data, opts);
    }

    // command "deletesubblock" [call]
    DeleteSubBlockCommand(client: RpcClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("deletesubblock", data, opts);
    }


    // command "dispose" [call]
    DisposeCommand(client: RpcClient, data: CommandDisposeData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("dispose", data, opts);
    }

    // command "disposesuggestions" [call]
    DisposeSuggestionsCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("disposesuggestions", data, opts);
    }

    // command "eventpublish" [call]
    EventPublishCommand(client: RpcClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("eventpublish", data, opts);
    }

    // command "eventreadhistory" [call]
    EventReadHistoryCommand(client: RpcClient, data: CommandEventReadHistoryData, opts?: RpcOpts): Promise<WaveEvent[]> {
        return client.rpcCall("eventreadhistory", data, opts);
    }

    // command "eventrecv" [call]
    EventRecvCommand(client: RpcClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("eventrecv", data, opts);
    }

    // command "eventsub" [call]
    EventSubCommand(client: RpcClient, data: SubscriptionRequest, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("eventsub", data, opts);
    }

    // command "eventunsub" [call]
    EventUnsubCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("eventunsub", data, opts);
    }

    // command "eventunsuball" [call]
    EventUnsubAllCommand(client: RpcClient, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("eventunsuball", null, opts);
    }

    // command "fetchsuggestions" [call]
    FetchSuggestionsCommand(client: RpcClient, data: FetchSuggestionsData, opts?: RpcOpts): Promise<FetchSuggestionsResponse> {
        return client.rpcCall("fetchsuggestions", data, opts);
    }

    // command "fileappend" [call]
    FileAppendCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("fileappend", data, opts);
    }

    // command "fileappendijson" [call]
    FileAppendIJsonCommand(client: RpcClient, data: CommandAppendIJsonData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("fileappendijson", data, opts);
    }

    // command "filecopy" [call]
    FileCopyCommand(client: RpcClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("filecopy", data, opts);
    }

    // command "filecreate" [call]
    FileCreateCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("filecreate", data, opts);
    }

    // command "filedelete" [call]
    FileDeleteCommand(client: RpcClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("filedelete", data, opts);
    }

    // command "fileinfo" [call]
    FileInfoCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<FileInfo> {
        return client.rpcCall("fileinfo", data, opts);
    }

    // command "filejoin" [call]
    FileJoinCommand(client: RpcClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        return client.rpcCall("filejoin", data, opts);
    }

    // command "filelist" [call]
    FileListCommand(client: RpcClient, data: FileListData, opts?: RpcOpts): Promise<FileInfo[]> {
        return client.rpcCall("filelist", data, opts);
    }

    // command "fileliststream" [responsestream]
	FileListStreamCommand(client: RpcClient, data: FileListData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        return client.rpcStream("fileliststream", data, opts);
    }

    // command "filemkdir" [call]
    FileMkdirCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("filemkdir", data, opts);
    }

    // command "filemove" [call]
    FileMoveCommand(client: RpcClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("filemove", data, opts);
    }

    // command "fileread" [call]
    FileReadCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<FileData> {
        return client.rpcCall("fileread", data, opts);
    }

    // command "filereadstream" [responsestream]
	FileReadStreamCommand(client: RpcClient, data: FileData, opts?: RpcOpts): AsyncGenerator<FileData, void, boolean> {
        return client.rpcStream("filereadstream", data, opts);
    }

    // command "filesharecapability" [call]
    FileShareCapabilityCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<FileShareCapability> {
        return client.rpcCall("filesharecapability", data, opts);
    }

    // command "filestreamtar" [responsestream]
	FileStreamTarCommand(client: RpcClient, data: CommandRemoteStreamTarData, opts?: RpcOpts): AsyncGenerator<Packet, void, boolean> {
        return client.rpcStream("filestreamtar", data, opts);
    }

    // command "filewrite" [call]
    FileWriteCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("filewrite", data, opts);
    }

    // command "focuswindow" [call]
    FocusWindowCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("focuswindow", data, opts);
    }

    // command "getfullconfig" [call]
    GetFullConfigCommand(client: RpcClient, opts?: RpcOpts): Promise<FullConfigType> {
        return client.rpcCall("getfullconfig", null, opts);
    }

    // command "getmeta" [call]
    GetMetaCommand(client: RpcClient, data: CommandGetMetaData, opts?: RpcOpts): Promise<MetaType> {
        return client.rpcCall("getmeta", data, opts);
    }

    // command "getrtinfo" [call]
    GetRTInfoCommand(client: RpcClient, data: CommandGetRTInfoData, opts?: RpcOpts): Promise<ObjRTInfo> {
        return client.rpcCall("getrtinfo", data, opts);
    }

    // command "gettab" [call]
    GetTabCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<Tab> {
        return client.rpcCall("gettab", data, opts);
    }

    // command "getupdatechannel" [call]
    GetUpdateChannelCommand(client: RpcClient, opts?: RpcOpts): Promise<string> {
        return client.rpcCall("getupdatechannel", null, opts);
    }

    // command "getvar" [call]
    GetVarCommand(client: RpcClient, data: CommandVarData, opts?: RpcOpts): Promise<CommandVarResponseData> {
        return client.rpcCall("getvar", data, opts);
    }

    // command "message" [call]
    MessageCommand(client: RpcClient, data: CommandMessageData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("message", data, opts);
    }

    // command "notify" [call]
    NotifyCommand(client: RpcClient, data: WaveNotificationOptions, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("notify", data, opts);
    }

    // command "path" [call]
    PathCommand(client: RpcClient, data: PathCommandData, opts?: RpcOpts): Promise<string> {
        return client.rpcCall("path", data, opts);
    }

    // command "recordtevent" [call]
    RecordTEventCommand(client: RpcClient, data: TEvent, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("recordtevent", data, opts);
    }

    // command "remotefilecopy" [call]
    RemoteFileCopyCommand(client: RpcClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<boolean> {
        return client.rpcCall("remotefilecopy", data, opts);
    }

    // command "remotefiledelete" [call]
    RemoteFileDeleteCommand(client: RpcClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("remotefiledelete", data, opts);
    }

    // command "remotefileinfo" [call]
    RemoteFileInfoCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<FileInfo> {
        return client.rpcCall("remotefileinfo", data, opts);
    }

    // command "remotefilejoin" [call]
    RemoteFileJoinCommand(client: RpcClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        return client.rpcCall("remotefilejoin", data, opts);
    }

    // command "remotefilemove" [call]
    RemoteFileMoveCommand(client: RpcClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("remotefilemove", data, opts);
    }

    // command "remotefiletouch" [call]
    RemoteFileTouchCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("remotefiletouch", data, opts);
    }

    // command "remotegetinfo" [call]
    RemoteGetInfoCommand(client: RpcClient, opts?: RpcOpts): Promise<RemoteInfo> {
        return client.rpcCall("remotegetinfo", null, opts);
    }

    // command "remoteinstallrcfiles" [call]
    RemoteInstallRcFilesCommand(client: RpcClient, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("remoteinstallrcfiles", null, opts);
    }

    // command "remotelistentries" [responsestream]
	RemoteListEntriesCommand(client: RpcClient, data: CommandRemoteListEntriesData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        return client.rpcStream("remotelistentries", data, opts);
    }

    // command "remotemkdir" [call]
    RemoteMkdirCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("remotemkdir", data, opts);
    }

    // command "remotestreamcpudata" [responsestream]
	RemoteStreamCpuDataCommand(client: RpcClient, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        return client.rpcStream("remotestreamcpudata", null, opts);
    }

    // command "remotestreamfile" [responsestream]
	RemoteStreamFileCommand(client: RpcClient, data: CommandRemoteStreamFileData, opts?: RpcOpts): AsyncGenerator<FileData, void, boolean> {
        return client.rpcStream("remotestreamfile", data, opts);
    }

    // command "remotetarstream" [responsestream]
	RemoteTarStreamCommand(client: RpcClient, data: CommandRemoteStreamTarData, opts?: RpcOpts): AsyncGenerator<Packet, void, boolean> {
        return client.rpcStream("remotetarstream", data, opts);
    }

    // command "remotewritefile" [call]
    RemoteWriteFileCommand(client: RpcClient, data: FileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("remotewritefile", data, opts);
    }

    // command "resolveids" [call]
    ResolveIdsCommand(client: RpcClient, data: CommandResolveIdsData, opts?: RpcOpts): Promise<CommandResolveIdsRtnData> {
        return client.rpcCall("resolveids", data, opts);
    }

    // command "routeannounce" [call]
    RouteAnnounceCommand(client: RpcClient, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("routeannounce", null, opts);
    }

    // command "routeunannounce" [call]
    RouteUnannounceCommand(client: RpcClient, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("routeunannounce", null, opts);
    }

    // command "sendtelemetry" [call]
    SendTelemetryCommand(client: RpcClient, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("sendtelemetry", null, opts);
    }

    // command "setconfig" [call]
    SetConfigCommand(client: RpcClient, data: SettingsType, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("setconfig", data, opts);
    }

    // command "setconnectionsconfig" [call]
    SetConnectionsConfigCommand(client: RpcClient, data: ConnConfigRequest, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("setconnectionsconfig", data, opts);
    }

    // command "setmeta" [call]
    SetMetaCommand(client: RpcClient, data: CommandSetMetaData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("setmeta", data, opts);
    }

    // command "setrtinfo" [call]
    SetRTInfoCommand(client: RpcClient, data: CommandSetRTInfoData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("setrtinfo", data, opts);
    }

    // command "setvar" [call]
    SetVarCommand(client: RpcClient, data: CommandVarData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("setvar", data, opts);
    }

    // command "setview" [call]
    SetViewCommand(client: RpcClient, data: CommandBlockSetViewData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("setview", data, opts);
    }

    // command "streamcpudata" [responsestream]
	StreamCpuDataCommand(client: RpcClient, data: CpuDataRequest, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        return client.rpcStream("streamcpudata", data, opts);
    }

    // command "streamtest" [responsestream]
	StreamTestCommand(client: RpcClient, opts?: RpcOpts): AsyncGenerator<number, void, boolean> {
        return client.rpcStream("streamtest", null, opts);
    }

    // command "termgetscrollbacklines" [call]
    TermGetScrollbackLinesCommand(client: RpcClient, data: CommandTermGetScrollbackLinesData, opts?: RpcOpts): Promise<CommandTermGetScrollbackLinesRtnData> {
        return client.rpcCall("termgetscrollbacklines", data, opts);
    }

    // command "test" [call]
    TestCommand(client: RpcClient, data: string, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("test", data, opts);
    }

    // command "waitforroute" [call]
    WaitForRouteCommand(client: RpcClient, data: CommandWaitForRouteData, opts?: RpcOpts): Promise<boolean> {
        return client.rpcCall("waitforroute", data, opts);
    }


    // command "waveinfo" [call]
    WaveInfoCommand(client: RpcClient, opts?: RpcOpts): Promise<WaveInfoData> {
        return client.rpcCall("waveinfo", null, opts);
    }

    // command "webselector" [call]
    WebSelectorCommand(client: RpcClient, data: CommandWebSelectorData, opts?: RpcOpts): Promise<string[]> {
        return client.rpcCall("webselector", data, opts);
    }

    // command "workspacelist" [call]
    WorkspaceListCommand(client: RpcClient, opts?: RpcOpts): Promise<WorkspaceInfoData[]> {
        return client.rpcCall("workspacelist", null, opts);
    }

    // command "wshactivity" [call]
    WshActivityCommand(client: RpcClient, data: {[key: string]: number}, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("wshactivity", data, opts);
    }

    // command "wsldefaultdistro" [call]
    WslDefaultDistroCommand(client: RpcClient, opts?: RpcOpts): Promise<string> {
        return client.rpcCall("wsldefaultdistro", null, opts);
    }

    // command "wsllist" [call]
    WslListCommand(client: RpcClient, opts?: RpcOpts): Promise<string[]> {
        return client.rpcCall("wsllist", null, opts);
    }

    // command "wslstatus" [call]
    WslStatusCommand(client: RpcClient, opts?: RpcOpts): Promise<ConnStatus[]> {
        return client.rpcCall("wslstatus", null, opts);
    }

    // command "listforgeagents" [call]
    ListForgeAgentsCommand(client: RpcClient, opts?: RpcOpts): Promise<ForgeAgent[]> {
        return client.rpcCall("listforgeagents", {}, opts);
    }

    // command "createforgeagent" [call]
    CreateForgeAgentCommand(client: RpcClient, data: CommandCreateForgeAgentData, opts?: RpcOpts): Promise<ForgeAgent> {
        return client.rpcCall("createforgeagent", data, opts);
    }

    // command "updateforgeagent" [call]
    UpdateForgeAgentCommand(client: RpcClient, data: CommandUpdateForgeAgentData, opts?: RpcOpts): Promise<ForgeAgent> {
        return client.rpcCall("updateforgeagent", data, opts);
    }

    // command "deleteforgeagent" [call]
    DeleteForgeAgentCommand(client: RpcClient, data: CommandDeleteForgeAgentData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("deleteforgeagent", data, opts);
    }

    // command "getforgecontent" [call]
    GetForgeContentCommand(client: RpcClient, data: CommandGetForgeContentData, opts?: RpcOpts): Promise<ForgeContent | null> {
        return client.rpcCall("getforgecontent", data, opts);
    }

    // command "setforgecontent" [call]
    SetForgeContentCommand(client: RpcClient, data: CommandSetForgeContentData, opts?: RpcOpts): Promise<ForgeContent> {
        return client.rpcCall("setforgecontent", data, opts);
    }

    // command "getallforgecontent" [call]
    GetAllForgeContentCommand(client: RpcClient, data: CommandGetAllForgeContentData, opts?: RpcOpts): Promise<ForgeContent[]> {
        return client.rpcCall("getallforgecontent", data, opts);
    }

    // command "listforgeskills" [call]
    ListForgeSkillsCommand(client: RpcClient, data: CommandListForgeSkillsData, opts?: RpcOpts): Promise<ForgeSkill[]> {
        return client.rpcCall("listforgeskills", data, opts);
    }

    // command "createforgeskill" [call]
    CreateForgeSkillCommand(client: RpcClient, data: CommandCreateForgeSkillData, opts?: RpcOpts): Promise<ForgeSkill> {
        return client.rpcCall("createforgeskill", data, opts);
    }

    // command "updateforgeskill" [call]
    UpdateForgeSkillCommand(client: RpcClient, data: CommandUpdateForgeSkillData, opts?: RpcOpts): Promise<ForgeSkill> {
        return client.rpcCall("updateforgeskill", data, opts);
    }

    // command "deleteforgeskill" [call]
    DeleteForgeSkillCommand(client: RpcClient, data: CommandDeleteForgeSkillData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("deleteforgeskill", data, opts);
    }

    // command "appendforgehistory" [call]
    AppendForgeHistoryCommand(client: RpcClient, data: CommandAppendForgeHistoryData, opts?: RpcOpts): Promise<ForgeHistory> {
        return client.rpcCall("appendforgehistory", data, opts);
    }

    // command "listforgehistory" [call]
    ListForgeHistoryCommand(client: RpcClient, data: CommandListForgeHistoryData, opts?: RpcOpts): Promise<ForgeHistory[]> {
        return client.rpcCall("listforgehistory", data, opts);
    }

    // command "searchforgehistory" [call]
    SearchForgeHistoryCommand(client: RpcClient, data: CommandSearchForgeHistoryData, opts?: RpcOpts): Promise<ForgeHistory[]> {
        return client.rpcCall("searchforgehistory", data, opts);
    }

    // command "importforgefromclaw" [call]
    ImportForgeFromClawCommand(client: RpcClient, data: CommandImportForgeFromClawData, opts?: RpcOpts): Promise<ForgeAgent> {
        return client.rpcCall("importforgefromclaw", data, opts);
    }

    // command "reseedforgeagents" [call]
    ReseedForgeAgentsCommand(client: RpcClient, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("reseedforgeagents", {}, opts);
    }

    // ── v6: identity / instance / fork ──────────────────────────────────────

    // command "listidentityaccounts" [call]
    ListIdentityAccountsCommand(
        client: RpcClient,
        data: { provider?: string } = {},
        opts?: RpcOpts,
    ): Promise<IdentityAccount[]> {
        return client.rpcCall("listidentityaccounts", data, opts);
    }

    // command "getidentityaccount" [call]
    GetIdentityAccountCommand(
        client: RpcClient,
        data: { id: string },
        opts?: RpcOpts,
    ): Promise<IdentityAccount> {
        return client.rpcCall("getidentityaccount", data, opts);
    }

    // command "upsertidentityaccount" [call]
    UpsertIdentityAccountCommand(
        client: RpcClient,
        data: Partial<IdentityAccount>,
        opts?: RpcOpts,
    ): Promise<IdentityAccount> {
        return client.rpcCall("upsertidentityaccount", data, opts);
    }

    // command "deleteidentityaccount" [call]
    DeleteIdentityAccountCommand(
        client: RpcClient,
        data: { id: string },
        opts?: RpcOpts,
    ): Promise<{ deleted: boolean }> {
        return client.rpcCall("deleteidentityaccount", data, opts);
    }

    // command "linkagentidentity" [call]
    LinkAgentIdentityCommand(
        client: RpcClient,
        data: { agent_id: string; account_id: string; provider: string },
        opts?: RpcOpts,
    ): Promise<void> {
        return client.rpcCall("linkagentidentity", data, opts);
    }

    // command "unlinkagentidentity" [call]
    UnlinkAgentIdentityCommand(
        client: RpcClient,
        data: { agent_id: string; provider: string },
        opts?: RpcOpts,
    ): Promise<{ unlinked: boolean }> {
        return client.rpcCall("unlinkagentidentity", data, opts);
    }

    // command "listagentidentities" [call]
    ListAgentIdentitiesCommand(
        client: RpcClient,
        data: { agent_id: string },
        opts?: RpcOpts,
    ): Promise<ForgeAgentIdentity[]> {
        return client.rpcCall("listagentidentities", data, opts);
    }

    // command "listagentinstances" [call]
    ListAgentInstancesCommand(
        client: RpcClient,
        data: { definition_id?: string; status?: string } = {},
        opts?: RpcOpts,
    ): Promise<AgentInstance[]> {
        return client.rpcCall("listagentinstances", data, opts);
    }

    // command "getagentinstance" [call]
    GetAgentInstanceCommand(
        client: RpcClient,
        data: { id: string },
        opts?: RpcOpts,
    ): Promise<AgentInstance> {
        return client.rpcCall("getagentinstance", data, opts);
    }

    // command "createagentinstance" [call]
    CreateAgentInstanceCommand(
        client: RpcClient,
        data: { definition_id: string; block_id?: string; parent_instance_id?: string },
        opts?: RpcOpts,
    ): Promise<AgentInstance> {
        return client.rpcCall("createagentinstance", data, opts);
    }

    // command "updateagentinstance" [call]
    // PATCH semantics — absent fields preserve current value.
    UpdateAgentInstanceCommand(
        client: RpcClient,
        data: {
            id: string;
            block_id?: string;
            session_id?: string;
            status?: string;
            github_context?: string;
            ended_at?: number;
        },
        opts?: RpcOpts,
    ): Promise<AgentInstance> {
        return client.rpcCall("updateagentinstance", data, opts);
    }

    // command "deleteagentinstance" [call]
    DeleteAgentInstanceCommand(
        client: RpcClient,
        data: { id: string },
        opts?: RpcOpts,
    ): Promise<{ deleted: boolean }> {
        return client.rpcCall("deleteagentinstance", data, opts);
    }

    // command "forkagentdefinition" [call]
    ForkAgentDefinitionCommand(
        client: RpcClient,
        data: { source_id: string; branch_label?: string },
        opts?: RpcOpts,
    ): Promise<ForgeAgent> {
        return client.rpcCall("forkagentdefinition", data, opts);
    }

    // command "subprocessspawn" [call]
    SubprocessSpawnCommand(client: RpcClient, data: CommandSubprocessSpawnData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("subprocessspawn", data, opts);
    }

    // command "agentinput" [call]
    AgentInputCommand(client: RpcClient, data: CommandAgentInputData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("agentinput", data, opts);
    }

    // command "agentstop" [call]
    AgentStopCommand(client: RpcClient, data: CommandAgentStopData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("agentstop", data, opts);
    }

    // command "writeagentconfig" [call]
    WriteAgentConfigCommand(client: RpcClient, data: CommandWriteAgentConfigData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("writeagentconfig", data, opts);
    }

    // command "readeditorfile" [call]
    ReadEditorFileCommand(client: RpcClient, data: CommandReadEditorFileData, opts?: RpcOpts): Promise<CommandReadEditorFileResult> {
        return client.rpcCall("readeditorfile", data, opts);
    }

    // command "writeeditorfile" [call]
    WriteEditorFileCommand(client: RpcClient, data: CommandWriteEditorFileData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("writeeditorfile", data, opts);
    }

    // command "resolvecli" [call]
    ResolveCliCommand(client: RpcClient, data: CommandResolveCliData, opts?: RpcOpts): Promise<ResolveCliResult> {
        return client.rpcCall("resolvecli", data, opts);
    }

    // command "checkcliauth" [call]
    CheckCliAuthCommand(client: RpcClient, data: CommandCheckCliAuthData, opts?: RpcOpts): Promise<CheckCliAuthResult> {
        return client.rpcCall("checkcliauth", data, opts);
    }

    // command "runclilogin" [call]
    RunCliLoginCommand(client: RpcClient, data: CommandRunCliLoginData, opts?: RpcOpts): Promise<RunCliLoginResult> {
        return client.rpcCall("runclilogin", data, opts);
    }

    // command "gettoolstatus" [call]
    GetToolStatusCommand(client: RpcClient, opts?: RpcOpts): Promise<GetToolStatusResult> {
        return client.rpcCall("gettoolstatus", {}, opts);
    }

    // command "installtool" [call]
    InstallToolCommand(client: RpcClient, data: CommandInstallToolData, opts?: RpcOpts): Promise<InstallToolResult> {
        return client.rpcCall("installtool", data, opts);
    }

    // command "blockfile:line_count" [call]
    BlockfileLineCountCommand(client: RpcClient, data: CommandBlockfileLineCountData, opts?: RpcOpts): Promise<BlockfileLineCountResult> {
        return client.rpcCall("blockfile:line_count", data, opts);
    }

    // command "blockfile:read_range" [call]
    BlockfileReadRangeCommand(client: RpcClient, data: CommandBlockfileReadRangeData, opts?: RpcOpts): Promise<BlockfileReadRangeResult> {
        return client.rpcCall("blockfile:read_range", data, opts);
    }

    // command "session:digest" [call]
    SessionDigestCommand(client: RpcClient, data: CommandSessionDigestData, opts?: RpcOpts): Promise<SessionDigestResult> {
        return client.rpcCall("session:digest", data, opts);
    }

    // command "session:archive" [call]
    SessionArchiveCommand(client: RpcClient, data: CommandSessionArchiveData, opts?: RpcOpts): Promise<SessionArchiveResult> {
        return client.rpcCall("session:archive", data, opts);
    }

    // command "session:restore" [call]
    SessionRestoreCommand(client: RpcClient, data: CommandSessionRestoreData, opts?: RpcOpts): Promise<SessionRestoreResult> {
        return client.rpcCall("session:restore", data, opts);
    }

    // command "session:export" [call]
    SessionExportCommand(client: RpcClient, data: CommandSessionExportData, opts?: RpcOpts): Promise<SessionExportResult> {
        return client.rpcCall("session:export", data, opts);
    }

}

export const RpcApi = new RpcApiType();
