// Copyright 2024-2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

/**
 * Type definitions for the unified agent widget
 *
 * This widget displays a living markdown document showing agent activity,
 * tool executions, and inter-agent communication.
 */

/**
 * A single terminal-style activity-log entry — emitted throughout the
 * pane lifecycle: launch flow (CLI resolution, install progress, auth
 * check, login poll), subprocess lifecycle (spawned / turn complete /
 * exit codes), slash-command outcomes, history pagination, subagent
 * events, errors. Collected into an array by `useActivityLog` and
 * rendered in the collapsible `<ActivityLogPanel>` above the composer.
 */
export interface LogLine {
    /** Stable id used as the key for per-line expanded-state (hover strip
     *  expand button). Generated by `useActivityLog.append`. */
    id: string;
    tag: string; // "agent", "cli", "auth", "env", "error", "install", etc.
    text: string;
    level?: "info" | "error" | "warn";
    /** Unix ms when the line was ingested. Shown by the per-line hover
     *  strip, same pattern as document nodes. */
    timestamp: number;
}

/**
 * Initialization question asked by the CLI during startup
 */
export interface InitQuestion {
    type: "theme" | "login" | "generic" | "other";
    text?: string;
    prompt?: string;
    options?: string[];
    expectsInput?: boolean;
}

/**
 * State of the CLI initialization process
 */
export type InitState = {
    phase: "spawning" | "awaiting_response" | "processing" | "ready" | "error";
    message?: string;
    question?: InitQuestion;
    error?: string;
};

/**
 * Document node types that make up the agent's markdown document
 */
export type DocumentNode = MarkdownNode | SectionNode | ToolNode | AgentMessageNode | UserMessageNode | SubagentLinkNode;

/**
 * Raw markdown text block
 */
export interface MarkdownNode {
    type: "markdown";
    id: string;
    content: string; // Raw markdown text
    timestamp?: number; // Unix ms — when this node was first received
    metadata?: {
        thinking?: boolean; // Whether this is a thinking block
    };
}

/**
 * Section heading (H1, H2, H3)
 */
export interface SectionNode {
    type: "section";
    id: string;
    level: 1 | 2 | 3; // H1, H2, H3
    title: string;
    collapsible: boolean;
    collapsed: boolean;
    timestamp?: number; // Unix ms
}

/**
 * Tool-specific parameter types
 */
export interface ReadParams {
    file_path: string;
    offset?: number;
    limit?: number;
}

export interface EditParams {
    file_path: string;
    old_string: string;
    new_string: string;
    replace_all?: boolean;
}

export interface WriteParams {
    file_path: string;
    content: string;
}

export interface BashParams {
    command: string;
    timeout?: number;
}

export interface GrepParams {
    pattern: string;
    path?: string;
    glob?: string;
}

export interface GlobParams {
    pattern: string;
    path?: string;
}

export type ToolParams = ReadParams | EditParams | WriteParams | BashParams | GrepParams | GlobParams | Record<string, unknown>;

/**
 * Tool-specific result types
 */
export interface ReadResult {
    content: string;
    lines?: number;
}

export interface EditResult {
    linesChanged: number;
    diff?: string;
}

export interface WriteResult {
    bytesWritten: number;
}

export interface BashResult {
    stdout: string;
    stderr: string;
    exitCode: number;
}

export interface GrepResult {
    matches: Array<{ file: string; line: number; content: string }>;
}

export interface GlobResult {
    files: string[];
}

export type ToolResult = ReadResult | EditResult | WriteResult | BashResult | GrepResult | GlobResult | Record<string, unknown>;

/**
 * Kind of a live log chunk. `stdout`/`stderr` are bash-style streams,
 * `diff-hunk` is one hunk of an Edit-tool incremental diff, `system`
 * is provider-emitted metadata (e.g. "command spawned", retry banner).
 */
export type ToolLogChunkKind = "stdout" | "stderr" | "system" | "diff-hunk";

/**
 * One append delivered while a tool is running. The reducer keeps an
 * append-only buffer of these on ToolNode.log.chunks until the
 * matching tool_result arrives. See SPEC_TOOL_BLOCK_LIVE_LOG_2026_05_11.md.
 */
export interface ToolLogChunk {
    kind: ToolLogChunkKind;
    content: string;
    /** Unix ms — defaults to receive time on the reducer side when the
     *  event omits it. Also used as the dedup key on history replay. */
    timestamp: number;
}

/**
 * Streaming log buffer attached to a ToolNode while it's running.
 * Append-only — chunks are never reordered or removed. `open` flips
 * false when `tool_result` lands; `result` (on ToolNode) holds the
 * final snapshot.
 */
export interface ToolStreamingLog {
    chunks: ReadonlyArray<ToolLogChunk>;
    /** True while the tool is producing output. Distinct from
     *  ToolNode.status because status flips at the network level; the
     *  reducer may still drain queued chunks for the same tool id
     *  even after status flips. */
    open: boolean;
}

/**
 * Tool execution block (Read, Edit, Bash, etc.)
 */
export interface ToolNode {
    type: "tool";
    id: string;
    tool: "Read" | "Edit" | "Bash" | "Write" | "Grep" | "Glob" | "Task" | "Agent" | "Other";
    params: ToolParams;
    /** Lifecycle:
     *  - `running`           — call dispatched, awaiting result
     *  - `pending_approval`  — provider gated the call; user owes a decision
     *  - `success`           — completed without error
     *  - `failed`            — completed with error
     *  - `denied`            — user denied the call via the decision panel
     *  Spec: docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §4.2.
     */
    status: "running" | "pending_approval" | "success" | "failed" | "denied";
    duration?: number; // Seconds
    result?: ToolResult;
    /** Live streaming buffer. Populated when the provider emits
     *  `tool_chunk` events between `tool_call` and `tool_result`.
     *  Undefined for tools that don't stream partials (e.g. Read,
     *  Grep). See SPEC_TOOL_BLOCK_LIVE_LOG_2026_05_11.md. */
    log?: ToolStreamingLog;
    collapsed: boolean;
    summary: string; // e.g., "📖 Read auth.ts (0.3s) ✓"
    timestamp?: number; // Unix ms — when this tool call was initiated
    /** Set when status === "pending_approval". Carried into the
     *  decision panel + echoed back through `tool:decision` IPC. */
    pendingPermission?: PermissionRequestEvent;
}

/**
 * Agent-to-agent message (mux or ject)
 */
export interface AgentMessageNode {
    type: "agent_message";
    id: string;
    from: string; // Agent ID
    to: string; // Agent ID (this agent)
    message: string;
    method: "mux" | "ject"; // Mux = async mailbox, Ject = terminal injection
    direction: "incoming" | "outgoing";
    timestamp: number;
    collapsed: boolean;
    summary: string; // e.g., "📨 claude-1 → reviewer (mux)" or "📥 From claude-1 (mux)"
}

/**
 * User message to agent
 */
export interface UserMessageNode {
    type: "user_message";
    id: string;
    message: string;
    timestamp: number;
    collapsed: boolean;
    summary: string; // "👤 User Message"
}

/**
 * Subagent link — rendered as a clickable badge in the agent pane.
 * Clicking opens a subagent activity pane split from the parent.
 */
export interface SubagentLinkNode {
    type: "subagent_link";
    id: string;
    subagentId: string;
    slug: string;
    parentAgent: string;
    sessionId: string;
    status: "active" | "completed";
    model: string | null;
    timestamp?: number; // Unix ms
}

/**
 * Stats from a completed agent session (from the Claude CLI `result` event).
 */
export interface SessionStats {
    cost_usd?: number;    // from result.cost_usd
    duration_ms?: number; // from result.duration_ms
    num_turns?: number;   // from result.num_turns
    /** Snapshot of TurnTokens.input at finalizeTurn — preserved here
     *  because the live TurnTokens signal is nulled on session_end
     *  before the Worked footer renders. See PR #549 reagent/codex P1. */
    input_tokens?: number;
    /** Snapshot of TurnTokens.output at finalizeTurn (see above). */
    output_tokens?: number;
}

/**
 * Live token counts accumulated during the current turn.
 * input is set from message_start.message.usage.input_tokens.
 * output accumulates from message_delta.usage.output_tokens.
 */
export interface TurnTokens {
    input: number;
    output: number;
}

/**
 * Stream events from Claude Code NDJSON output
 */
export type StreamEvent =
    | TextEvent
    | ThinkingEvent
    | ToolCallEvent
    | ToolChunkEvent
    | ToolResultEvent
    | AgentMessageEvent
    | UserMessageEvent
    | SessionEndEvent
    | PermissionRequestEvent;

export interface TextEvent {
    type: "text";
    content: string;
}

export interface ThinkingEvent {
    type: "thinking";
    content: string;
}

export interface ToolCallEvent {
    type: "tool_call";
    tool: string;
    id: string;
    params: Record<string, any>;
}

/**
 * Streaming chunk delivered between `tool_call` and `tool_result` for
 * tools that produce partial output (bash stdout/stderr lines, edit
 * diff hunks). The reducer routes one of these into the matching
 * ToolNode's `log.chunks` via `ToolChunkAppend`. See
 * SPEC_TOOL_BLOCK_LIVE_LOG_2026_05_11.md.
 */
export interface ToolChunkEvent {
    type: "tool_chunk";
    /** Tool call id — matches the preceding `tool_call.id`. */
    id: string;
    kind: ToolLogChunkKind;
    content: string;
    /** Unix ms. Optional — defaults to receive time when the provider
     *  omits it. Used as part of the dedup key on history replay. */
    timestamp?: number;
}

export interface ToolResultEvent {
    type: "tool_result";
    tool: string;
    id: string;
    status: "success" | "failed" | "denied";
    duration?: number;
    result?: any;
    exitCode?: number;
}

/**
 * Per-tool-call permission gate. Emitted by the provider adapter
 * when the CLI asks the user to allow / deny a specific tool call.
 *
 * Today's adapters return null from their `parsePermissionRequest`
 * hook (no structured CLI event yet — see
 * docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §9.1). The type is
 * defined here so the rest of the system (UI panel, IPC handler,
 * memory store) can be built against the shape while the
 * detection strategy is still being chosen.
 *
 * Spec: docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §4.1.
 */
export interface PermissionRequestEvent {
    type: "permission_request";
    /** Opaque id; echoed back in the `tool:decision` IPC. */
    request_id: string;
    /** Tool the agent wants to invoke ("bash", "str_replace", …). */
    tool: string;
    /** Path / command / url the tool will act on. May be null when
     *  the tool's args don't have a single canonical target. */
    target: string | null;
    /** Provider-supplied rationale. Optional. */
    reason?: string;
    /** Optional preview content (diff text, bash command, …). */
    preview?: PermissionPreview;
    /** Risk classification — drives whether single-keystroke
     *  approval is allowed or a confirm step is required. Defaults
     *  to "medium" when the adapter doesn't supply one. */
    risk?: "low" | "medium" | "high";
}

export type PermissionPreview =
    | { kind: "diff"; content: string }
    | { kind: "bash"; command: string }
    | { kind: "text"; content: string }
    | { kind: "none" };

export interface AgentMessageEvent {
    type: "agent_message";
    from: string;
    to: string;
    message: string;
    method: "mux" | "ject";
    timestamp?: number;
}

export interface UserMessageEvent {
    type: "user_message";
    message: string;
    timestamp?: number;
}

export interface SessionEndEvent {
    type: "session_end";
    stats: SessionStats;
}

/**
 * Bookmark — pins a document node for quick navigation.
 * Stored as a JSON array under block meta key "agent:bookmarks".
 *
 * Known limitation: if the session is replayed from history, node IDs are
 * regenerated (UUIDs) and will not match the stored nodeId. The `preview`
 * text can be used as a fallback to search for the original content.
 */
export interface Bookmark {
    id: string;       // uuid — unique bookmark identifier
    nodeId: string;   // DocumentNode.id this bookmark points to
    createdAt: number; // Unix ms
    label: string;    // user-editable; defaults to first 60 chars of node content
    preview: string;  // immutable snapshot of node content at bookmark time (80 chars)
}

/**
 * Document state (managed by Jotai atoms)
 */
export interface DocumentState {
    collapsedNodes: Set<string>; // Node IDs that are collapsed (agent messages)
    /**
     * Nodes the user has clicked to PIN expanded. For tool nodes this opens
     * the portal overlay with tool-specific content; for other kinds this is
     * used by future expansion surfaces. Default is collapsed — see
     * docs/specs/tool-collapse.md.
     */
    pinnedNodes: Set<string>;
    scrollPosition: number;
    selectedNode: string | null; // For keyboard navigation
    filter: FilterState;
}

export interface FilterState {
    showThinking: boolean; // Hide thinking by default
    showSuccessfulTools: boolean; // Show successful tools
    showFailedTools: boolean; // Always show failures
    showIncoming: boolean; // Show incoming messages
    showOutgoing: boolean; // Show outgoing messages
}

/**
 * Streaming state
 */
export interface StreamingState {
    active: boolean;
    agentId: string | null;
    bufferSize: number; // Number of events buffered
    lastEventTime: number;
}

/**
 * Shared logging callback passed into hooks and flows.
 * Implementations append a tagged line to the launch-log document.
 */
export type LogFn = (tag: string, text: string, level?: "info" | "error" | "warn") => void;

/**
 * Runtime configuration for agent pane controls.
 * Stored in block metadata as "agent:runtime".
 * Applied as CLI flags on each turn (between --resume spawns).
 */
export type PermissionMode = "bypass" | "auto" | "acceptEdits" | "plan" | "default";
export type ModelChoice = "opus" | "sonnet" | "haiku";
export type EffortLevel = "low" | "medium" | "high" | "max";

export interface AgentRuntimeConfig {
    permissionMode: PermissionMode;
    model: ModelChoice;
    effort: EffortLevel;
}

export const DEFAULT_RUNTIME_CONFIG: AgentRuntimeConfig = {
    permissionMode: "bypass",
    model: "sonnet",
    effort: "medium",
};

/**
 * Tool icon mapping
 */
export const TOOL_ICONS: Record<string, string> = {
    Read: "📖",
    Edit: "✏️",
    Write: "📝",
    Bash: "🔧",
    Grep: "🔍",
    Glob: "📁",
    Task: "🛠️",
    Agent: "🤖",
    Other: "🛠️",
};

/**
 * Status icon mapping
 */
export const STATUS_ICONS: Record<string, string> = {
    running: "⏳",
    success: "✓",
    failed: "✗",
};

/**
 * Agent message icon mapping
 */
export const AGENT_MESSAGE_ICONS: Record<string, string> = {
    mux: "📨", // Async mailbox
    ject: "⚡", // Terminal injection
};

/**
 * Direction icon mapping
 */
export const DIRECTION_ICONS: Record<string, string> = {
    incoming: "📥",
    outgoing: "📤",
};
