// Copyright 2024-2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

/**
 * Type definitions for the unified agent widget
 *
 * This widget displays a living markdown document showing agent activity,
 * tool executions, and inter-agent communication.
 */

/**
 * A single terminal-style activity-log entry — emitted throughout the
 * pane lifecycle: launch flow (CLI resolution, install progress, auth
 * check, login poll), subprocess lifecycle (spawned / turn complete /
 * exit codes), slash-command outcomes, history pagination, subagent
 * events, errors. Collected into an array by `useActivityLog` and written
 * directly into the shell terminal (agent-view.tsx's `log`/
 * `handleShellTermReady`) rather than a separate panel.
 */
export interface LogLine {
    /** Stable id used as the key for per-line expanded-state (hover strip
     *  expand button). Generated by `useActivityLog.append`. */
    id: string;
    tag: string; // "agent", "cli", "auth", "env", "error", "install", etc.
    text: string;
    level?: "info" | "error" | "warn";
    /** Unix ms when the line was ingested. Shown by the per-line hover
     *  strip, same pattern as document nodes. */
    timestamp: number;
}

/**
 * Initialization question asked by the CLI during startup
 */
export interface InitQuestion {
    type: "theme" | "login" | "generic" | "other";
    text?: string;
    prompt?: string;
    options?: string[];
    expectsInput?: boolean;
}

/**
 * State of the CLI initialization process
 */
export type InitState = {
    phase: "spawning" | "awaiting_response" | "processing" | "ready" | "error";
    message?: string;
    question?: InitQuestion;
    error?: string;
};

/**
 * Document node types that make up the agent's markdown document
 */
export type DocumentNode = MarkdownNode | SectionNode | ToolNode | AgentMessageNode | UserMessageNode | ShellNode | AgentErrorNode | ContextCompactedNode | CompactionStartedNode | JektMessageNode | SessionOutcomeNode | DayDividerNode | HistoryLinkNode;

/**
 * Raw markdown text block
 */
export interface MarkdownNode {
    type: "markdown";
    id: string;
    content: string; // Raw markdown text
    timestamp?: number; // Unix ms — when this node was first received
    metadata?: {
        thinking?: boolean; // Whether this is a thinking block
        /**
         * Set when the node was a thinking block whose stream
         * ended before completion (pane closed, app killed, etc.).
         * On the next session open, the orphan-scrub pass on
         * SessionEnd / HistoryLoaded flips this to `true` and
         * clears `thinking` — so the UI can render the partial
         * content as historical-canceled (collapsed by default,
         * "⏹ Canceled — partial thought" label) instead of
         * misleadingly showing a live "Thinking..." spinner on
         * something the agent will never finish.
         *
         * Spec: docs/specs/SPEC_ORPHAN_THINKING_NODES_2026_05_27.md.
         */
        canceled?: boolean;
        /** Unix ms when the orphan-scrub pass marked this node
         *  canceled. Optional; primarily for future audit/tooltip. */
        canceledAt?: number;
    };
}

/**
 * Section heading (H1, H2, H3)
 */
export interface SectionNode {
    type: "section";
    id: string;
    level: 1 | 2 | 3; // H1, H2, H3
    title: string;
    collapsible: boolean;
    collapsed: boolean;
    timestamp?: number; // Unix ms
}

/**
 * Tool-specific parameter types
 */
interface ReadParams {
    file_path: string;
    offset?: number;
    limit?: number;
}

export interface EditParams {
    file_path: string;
    old_string: string;
    new_string: string;
    replace_all?: boolean;
}

interface WriteParams {
    file_path: string;
    content: string;
}

export interface BashParams {
    command: string;
    timeout?: number;
    /**
     * True when the harness runs this command detached: the tool_result
     * returns almost immediately ("Command running in background with
     * ID: …") while the real process tree keeps running, and a
     * `<task-notification>` user message carrying this call's
     * `tool_use_id` arrives when it actually finishes. The flag was
     * always present in the wire `tool_use.input` and flows through
     * `ToolNode.params` untouched — this field just names it so
     * tool-adapter.ts can give backgrounded calls a dock row that
     * tracks the REAL lifetime instead of the instant tool_result
     * (issue #2490; docs/status/STATUS_ATTACHED_TASK_AXIS_AND_DEV_LOOP_2026_08_09.md
     * rung 2).
     */
    run_in_background?: boolean;
}

interface GrepParams {
    pattern: string;
    path?: string;
    glob?: string;
}

interface GlobParams {
    pattern: string;
    path?: string;
}

type ToolParams = ReadParams | EditParams | WriteParams | BashParams | GrepParams | GlobParams | Record<string, unknown>;

/**
 * Tool-specific result types
 */
interface ReadResult {
    content: string;
    lines?: number;
}

export interface EditResult {
    linesChanged: number;
    diff?: string;
}

export interface WriteResult {
    bytesWritten: number;
}

export interface BashResult {
    stdout: string;
    stderr: string;
    exitCode: number;
}

export interface GrepResult {
    matches: Array<{ file: string; line: number; content: string }>;
}

export interface GlobResult {
    files: string[];
}

type ToolResult = ReadResult | EditResult | WriteResult | BashResult | GrepResult | GlobResult | Record<string, unknown>;

/**
 * Kind of a live log chunk. `stdout`/`stderr` are bash-style streams,
 * `diff-hunk` is one hunk of an Edit-tool incremental diff, `system`
 * is provider-emitted metadata (e.g. "command spawned", retry banner).
 */
type ToolLogChunkKind = "stdout" | "stderr" | "system" | "diff-hunk";

/**
 * One append delivered while a tool is running. The reducer keeps an
 * append-only buffer of these on ToolNode.log.chunks until the
 * matching tool_result arrives. See SPEC_TOOL_BLOCK_LIVE_LOG_2026_05_11.md.
 */
export interface ToolLogChunk {
    kind: ToolLogChunkKind;
    content: string;
    /** Unix ms — defaults to receive time on the reducer side when the
     *  event omits it. Also used as the dedup key on history replay. */
    timestamp: number;
}

/**
 * Streaming log buffer attached to a ToolNode while it's running.
 * Append-only — chunks are never reordered or removed. `open` flips
 * false when `tool_result` lands; `result` (on ToolNode) holds the
 * final snapshot.
 */
export interface ToolStreamingLog {
    chunks: ReadonlyArray<ToolLogChunk>;
    /** True while the tool is producing output. Distinct from
     *  ToolNode.status because status flips at the network level; the
     *  reducer may still drain queued chunks for the same tool id
     *  even after status flips. */
    open: boolean;
}

/**
 * Tool execution block (Read, Edit, Bash, etc.)
 */
export interface ToolNode {
    type: "tool";
    id: string;
    tool: "Read" | "Edit" | "Bash" | "Write" | "Grep" | "Glob" | "Task" | "Agent" | "Other";
    /**
     * The raw provider tool name (e.g. "WebSearch", "TodoWrite",
     * "mcp__github__search_issues"). `tool` above is the coarse, closed "kind"
     * (unknown → "Other"); `toolName` preserves the real name so the tool-result
     * renderer registry can route the open-ended tool universe by name. Optional
     * for back-compat with older nodes that predate the field — matchers fall
     * back to `tool`. See SPEC_TOOL_RESULT_RENDERER_REGISTRY_2026_06_17.md §5.1.
     */
    toolName?: string;
    params: ToolParams;
    /** Lifecycle:
     *  - `running`           — call dispatched, awaiting result
     *  - `pending_approval`  — provider gated the call; user owes a decision
     *  - `success`           — completed without error
     *  - `failed`            — completed with error
     *  - `denied`            — user denied the call via the decision panel
     *  - `canceled`          — was running when the session ended;
     *                          the orphan-scrub pass on SessionEnd /
     *                          HistoryLoaded transitioned it. Render
     *                          collapsed with the ⏹ icon, never with a
     *                          spinner. Spec:
     *                          SPEC_ORPHAN_THINKING_NODES_2026_05_27.md.
     *  - `awaiting_answer`   — the agent called `AskUserQuestion` and is
     *                          blocked on the user's answer (delivered as a
     *                          tool_result). Carries `question`. Spec:
     *                          SPEC_ASK_USER_QUESTION_2026_06_15.md.
     *  Spec: docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §4.2.
     */
    status: "running" | "pending_approval" | "awaiting_answer" | "success" | "failed" | "denied" | "canceled";
    duration?: number; // Seconds
    result?: ToolResult;
    /** Live streaming buffer. Populated when the provider emits
     *  `tool_chunk` events between `tool_call` and `tool_result`.
     *  Undefined for tools that don't stream partials (e.g. Read,
     *  Grep). See SPEC_TOOL_BLOCK_LIVE_LOG_2026_05_11.md. */
    log?: ToolStreamingLog;
    collapsed: boolean;
    summary: string; // e.g., "📖 Read auth.ts (0.3s) ✓"
    timestamp?: number; // Unix ms — when this tool call was initiated
    /** Set when status === "pending_approval". Carried into the
     *  decision panel + echoed back through `tool:decision` IPC. */
    pendingPermission?: PermissionRequestEvent;
    /** Set when status === "awaiting_answer" (the tool is AskUserQuestion).
     *  Drives the question panel; the answer goes back as a tool_result. */
    question?: AskUserQuestionRequest;
    /** Set alongside `summary` when an AskUserQuestion is answered (status
     *  flips to "success"). Raw answer text with real newlines preserved —
     *  `summary` is the decorated one-line log form (`; `-joined, prefixed
     *  with an icon) and isn't fit for display as message content. Absent
     *  on nodes answered before this field existed (legacy transcripts);
     *  renderers must guard on presence, not just tool+status, and fall
     *  back to the generic collapsed-row rendering.
     *  See SPEC_ASK_USER_QUESTION_HISTORY_STYLING_2026_08_17.md. */
    answerText?: string;
}

/**
 * Agent-to-agent message (mux or ject)
 */
export interface AgentMessageNode {
    type: "agent_message";
    id: string;
    from: string; // Agent ID
    to: string; // Agent ID (this agent)
    message: string;
    method: "mux" | "ject"; // Mux = async mailbox, Ject = terminal injection
    direction: "incoming" | "outgoing";
    timestamp: number;
    collapsed: boolean;
    summary: string; // e.g., "📨 claude-1 → reviewer (mux)" or "📥 From claude-1 (mux)"
}

/** Sensitivity tier declared by the sender (or escalated on delivery). See
 *  docs/specs/SPEC_JEKT_SECURITY_AND_VISIBILITY_2026_07_01.md §4. */
export type JektTier = "info" | "coord" | "sensitive";

/** Network path the jekt crossed to reach this agent. */
export type JektDeliveryTier = "host" | "lan" | "wan";

/** Sender trust classification. Host-tier deliveries are agent-originated on
 *  this machine; lan/wan cross a network boundary and are only as
 *  trustworthy as the sender's token. Spec §5. */
export type JektTrust = "host-verified" | "network-claimed";

/**
 * A muxbus jekt message, parsed out of the `[JEKT:FROM=... TIER=... ...]` /
 * `[/JEKT]` marker block that `wrap_jekt_message` (agentmux-srv) and
 * `wrapJektMessage` (muxbus-cloud) wrap around injected text before it lands
 * in the agent's input stream. Rendered as a `JektBubble` instead of the raw
 * marker text.
 *
 * Spec: docs/specs/SPEC_JEKT_SECURITY_AND_VISIBILITY_2026_07_01.md §3.3.
 */
export interface JektMessageNode {
    type: "jekt_message";
    id: string;
    from: string; // Agent ID (sender)
    to: string; // Agent ID (recipient)
    /** Inner message text with the marker's presentational scaffolding
     *  (divider lines, From/To header, sensitive warning, reply hint)
     *  stripped — what the sender actually typed/sent. */
    message: string;
    /** Full original `[JEKT:...]...[/JEKT]` block, unmodified. Shown in the
     *  expanded metadata view (spec §3.3: "raw payload"). */
    raw: string;
    tier: JektTier;
    deliveryTier: JektDeliveryTier;
    trust: JektTrust;
    msgId: string;
    priority: "normal" | "urgent";
    direction: "incoming" | "outgoing";
    timestamp: number;
}

/**
 * User message to agent.
 *
 * `collapsed` + `summary` fields were retired in PR #1020 — the
 * renderer (`UserMessageBlock`) keys its render shape off
 * `isStartup` + `documentState.pinnedNodes`, not per-node mutable
 * state. The agent-message variant still carries `collapsed` /
 * `summary` because its toggle UI lives on the document-level
 * `collapsedNodes` set; user messages have their own pin model.
 */
export interface UserMessageNode {
    type: "user_message";
    id: string;
    message: string;
    timestamp: number;
    /** True when this row is the auto-generated startup context
     * payload (see `buildStartupPayload.ts` + onReadyFn in
     * `agent-view.tsx`). The renderer surfaces these
     * collapsed-by-default with hover-expand + click-to-pin,
     * mirroring the ToolBlock pattern — they otherwise dominate
     * the pane on every fresh agent launch.
     *
     * Detected by stream-parser via the literal `# Session Context`
     * heading the builder emits. Frontend-only marker; never
     * round-trips through the agent CLI.
     *
     * Spec:
     * `docs/specs/SPEC_USER_INPUT_VISIBILITY_AND_STARTUP_COLLAPSE_2026_05_24.md`. */
    isStartup?: boolean;
}

/**
 * Persistent shell — a long-running process launched by the agent via the
 * Shell tool (agentmux-mcp). Lives in the document as a single compact row
 * that expands inline to show the live-log.
 *
 * Unlike ToolNode, a ShellNode is not tied to a tool-call lifecycle —
 * the shell runs independently after the Shell tool returns.
 *
 * Spec: docs/specs/SPEC_PERSISTENT_SHELL_NODE_2026_06_11.md
 */
export interface ShellNode {
    type: "shell";
    id: string;
    cmd: string;
    title: string;
    cwd?: string;
    status: "running" | "exited-ok" | "exited-err" | "stopped";
    exitCode?: number;
    spawnedAt: number;   // Unix ms
    exitedAt?: number;   // Unix ms
    log: ToolStreamingLog;
}

/**
 * Inline API error node rendered in the transcript when a session ends with
 * is_error:true (e.g. 401 auth failure, 429 rate-limit). Not collapsible.
 * Spec: SPEC_AGENT_ERROR_FRAMEWORK_2026_06_20.md §P1.3
 */
export interface AgentErrorNode {
    type: "agent_error";
    id: string;
    code: number;   // HTTP status code (e.g. 401, 429)
    message: string; // Full error text from the CLI result event
}

/**
 * Transcript boundary marker inserted when Claude compacts its context.
 *
 * `source: "real"` — sourced from the backend's authoritative
 * `CompactionBoundary` event (Claude Code's `compact_boundary` frame,
 * exact data). `trigger`/`durationMs` are present.
 * `source: "heuristic"` — the pre-existing cross-provider fallback,
 * inferred from a ≥50%-drop in observed input tokens. `trigger`/
 * `durationMs` are absent (not knowable from the heuristic alone).
 * See docs/specs/SPEC_COMPACTION_DETECTION_AND_HANDLING_2026_07_31.md §4.3.
 */
export interface ContextCompactedNode {
    type: "context_compacted";
    id: string;
    tokensBefore: number;
    tokensAfter: number;
    timestamp: number;
    source: "real" | "heuristic";
    trigger?: "manual" | "auto";
    /** Real compaction duration in ms — only present when `source === "real"`. */
    durationMs?: number;
}

/**
 * Live "compaction is happening now" announcement — pushed the instant
 * the `PreCompact` hook's `compaction_started` signal lands (Tier 1 of
 * docs/specs/SPEC_COMPACTION_DETECTION_AND_HANDLING_2026_07_31.md).
 * Deliberately a SEPARATE node type from `ContextCompactedNode`: this
 * one represents an in-progress announcement with no outcome data yet,
 * while `ContextCompactedNode` is the completed record (real or
 * heuristic) — conflating the two would make a still-running
 * compaction look like a finished one in the transcript.
 */
export interface CompactionStartedNode {
    type: "compaction_started";
    id: string;
    trigger: "manual" | "auto";
    startedAt: number;
}

/**
 * Transcript boundary marker for a `--resume` attempt's outcome — sourced
 * from AgentMux's own `agentmux_session_outcome` frame (the backend's
 * `persistent_resume` state machine, not the provider CLI). `"resumed"`
 * means the CLI genuinely continued the prior session; `"fresh"` means it
 * could not, and the model has none of the turns before this marker even
 * though the pane's scrollback above it is still fully visible. See
 * docs/specs/SPEC_AGENT_PANE_HISTORY_ALIGNMENT_2026_08_05.md §2.2.
 */
export interface SessionOutcomeNode {
    type: "session_outcome";
    id: string;
    outcome: "resumed" | "fresh";
    attemptedSid: string;
    actualSid: string | null;
    timestamp: number;
}

/**
 * Calendar-day separator in the Agent History view. A render-time synthetic
 * (injected by `injectDayDividers`, never persisted, never part of the live
 * document store) — id `day-<YYYY-MM-DD>` is content-derived so pagination
 * prepends recompute to the identical node instead of duplicating.
 * Spec: SPEC_AGENT_PANE_SESSION_SCOPED_SCROLLBACK_AND_AGENT_HISTORY_VIEW_2026_08_09.md §4.4.
 */
export interface DayDividerNode {
    type: "day_divider";
    id: string;
    /** Human label, e.g. "Sun, Aug 10 2026". */
    dayLabel: string;
    /** Local midnight of the day, unix ms. */
    timestamp: number;
}

/**
 * "Open Agent History" link row in the LIVE working document. A render-time
 * synthetic (injected by `injectHistoryLink`, never persisted, never part of
 * the reducer store) — scrolls with the transcript instead of being pinned
 * above it, since opening it just switches/opens a pane tab (§3.2 of
 * SPEC_AGENT_HISTORY_AS_TAB_AND_DRAFT_PRESERVATION_2026_08_11.md). Never
 * injected into the Agent History reader itself — that view has no need to
 * link to itself. Fixed id: there is at most one per live document.
 */
export interface HistoryLinkNode {
    type: "history_link";
    id: "history-link";
}

/**
 * Stats from a completed agent session (from the Claude CLI `result` event).
 */
export interface SessionStats {
    cost_usd?: number;    // from result.cost_usd
    duration_ms?: number; // from result.duration_ms
    num_turns?: number;   // from result.num_turns
    /** Snapshot of TurnTokens.input at finalizeTurn — preserved here
     *  because the live TurnTokens signal is nulled on session_end
     *  before the Worked footer renders. See PR #549 reagent/codex P1. */
    input_tokens?: number;
    /** Snapshot of TurnTokens.output at finalizeTurn (see above). */
    output_tokens?: number;
}

/**
 * Live token counts accumulated during the current turn.
 * input is set from message_start.message.usage.input_tokens.
 * output accumulates from message_delta.usage.output_tokens.
 */
export interface TurnTokens {
    input: number;
    output: number;
}

/**
 * Stream events from Claude Code NDJSON output
 */
export type StreamEvent =
    | TextEvent
    | ThinkingEvent
    | ToolCallEvent
    | ToolChunkEvent
    | ToolResultEvent
    | AgentMessageEvent
    | UserMessageEvent
    | SessionEndEvent
    | ErrorResultEvent
    | PermissionRequestEvent
    | ProviderWaitingEvent;

/** Provider is rate-limited and retrying. Updates lastEventMs; shows "Rate limited…" in working row. */
interface ProviderWaitingEvent {
    type: "provider_waiting";
    reason: "rate_limited";
    retryAfterMs: number | null;
}

/** API error from a `type:"result"` line with is_error:true + api_error_status. */
export interface ErrorResultEvent {
    type: "error_result";
    code: number;   // api_error_status (HTTP code: 401, 429, 500, …)
    message: string; // rawEvent.result text
}

export interface TextEvent {
    type: "text";
    content: string;
}

export interface ThinkingEvent {
    type: "thinking";
    content: string;
}

export interface ToolCallEvent {
    type: "tool_call";
    tool: string;
    id: string;
    params: Record<string, any>;
}

/**
 * Streaming chunk delivered between `tool_call` and `tool_result` for
 * tools that produce partial output (bash stdout/stderr lines, edit
 * diff hunks). The reducer routes one of these into the matching
 * ToolNode's `log.chunks` via `ToolChunkAppend`. See
 * SPEC_TOOL_BLOCK_LIVE_LOG_2026_05_11.md.
 */
export interface ToolChunkEvent {
    type: "tool_chunk";
    /** Tool call id — matches the preceding `tool_call.id`. */
    id: string;
    kind: ToolLogChunkKind;
    content: string;
    /** Unix ms. Optional — defaults to receive time when the provider
     *  omits it. Used as part of the dedup key on history replay. */
    timestamp?: number;
}

export interface ToolResultEvent {
    type: "tool_result";
    tool: string;
    id: string;
    status: "success" | "failed" | "denied";
    duration?: number;
    result?: any;
    exitCode?: number;
}

/**
 * Per-tool-call permission gate. Emitted by the provider adapter
 * when the CLI asks the user to allow / deny a specific tool call.
 *
 * Today's adapters return null from their `parsePermissionRequest`
 * hook (no structured CLI event yet — see
 * docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §9.1). The type is
 * defined here so the rest of the system (UI panel, IPC handler,
 * memory store) can be built against the shape while the
 * detection strategy is still being chosen.
 *
 * Spec: docs/specs/SPEC_DECISION_PROMPT_2026_04_24.md §4.1.
 */
export interface PermissionRequestEvent {
    type: "permission_request";
    /** Opaque id; echoed back in the `tool:decision` IPC. */
    request_id: string;
    /** Tool the agent wants to invoke ("bash", "str_replace", …). */
    tool: string;
    /** Path / command / url the tool will act on. May be null when
     *  the tool's args don't have a single canonical target. */
    target: string | null;
    /** Provider-supplied rationale. Optional. */
    reason?: string;
    /** Optional preview content (diff text, bash command, …). */
    preview?: PermissionPreview;
    /** Risk classification — drives whether single-keystroke
     *  approval is allowed or a confirm step is required. Defaults
     *  to "medium" when the adapter doesn't supply one. */
    risk?: "low" | "medium" | "high";
}

type PermissionPreview =
    | { kind: "diff"; content: string }
    | { kind: "bash"; command: string }
    | { kind: "text"; content: string }
    | { kind: "none" };

/**
 * AskUserQuestion — the agent called the `AskUserQuestion` tool to ask the
 * human a structured multiple-choice question and is BLOCKING its turn on a
 * `tool_result`. Parsed from the tool_use `input` (validated wire shape:
 * `input.questions[]`). The answer is delivered back over the persistent
 * controller's live stdin as a tool_result.
 *
 * Spec: docs/specs/SPEC_ASK_USER_QUESTION_2026_06_15.md.
 */
export interface AskUserQuestionOption {
    label: string;
    description?: string;
}

export interface AskUserQuestionItem {
    question: string;
    /** Short chip label (≤12 chars), e.g. "Auth method". */
    header: string;
    /** true → checkbox semantics (pick many); false → radio (pick one). */
    multiSelect: boolean;
    options: AskUserQuestionOption[];
}

export interface AskUserQuestionRequest {
    type: "ask_user_question";
    /** The AskUserQuestion tool_use id; echoed in the tool_result reply. */
    tool_use_id: string;
    questions: AskUserQuestionItem[];
}

/** One question's answer. `selected` are chosen option labels (length 1 for
 *  single-select); `other` is free-text the user typed instead of / alongside. */
export interface AskUserQuestionAnswer {
    header: string;
    selected: string[];
    other?: string;
}

export interface AgentMessageEvent {
    type: "agent_message";
    from: string;
    to: string;
    message: string;
    method: "mux" | "ject";
    timestamp?: number;
}

export interface UserMessageEvent {
    type: "user_message";
    message: string;
    timestamp?: number;
}

interface SessionEndEvent {
    type: "session_end";
    stats: SessionStats;
}

/**
 * Document state (managed by Jotai atoms)
 */
export interface DocumentState {
    collapsedNodes: Set<string>; // Node IDs that are collapsed (agent messages)
    /**
     * Nodes the user has clicked to PIN expanded. For tool nodes this opens
     * the portal overlay with tool-specific content; for other kinds this is
     * used by future expansion surfaces. Default is collapsed — see
     * docs/specs/tool-collapse.md.
     */
    pinnedNodes: Set<string>;
    /**
     * Tool nodes currently held EXPANDED after completing live on screen. A
     * completed tool is added here on its active→inactive transition and removed
     * once its row scrolls off the top of the viewport (latched collapse) —
     * replacing the old 3 s post-completion timer. Loaded-history tools never
     * transition this session, so they're never added and render collapsed.
     * See docs/specs/PLAN_TOOL_BLOCK_SCROLL_DRIVEN_COLLAPSE_2026_06_16.md.
     */
    expandedTools: Set<string>;
    scrollPosition: number;
    selectedNode: string | null; // For keyboard navigation
    filter: FilterState;
}

export interface FilterState {
    showThinking: boolean; // Hide thinking by default
    showSuccessfulTools: boolean; // Show successful tools
    showFailedTools: boolean; // Always show failures
    showIncoming: boolean; // Show incoming messages
    showOutgoing: boolean; // Show outgoing messages
}

/**
 * Streaming state — telemetry sub-object on the agent-pane reducer.
 *
 * PR G dropped the legacy `active: boolean` field; "is the stream
 * subscribed?" is now derived from the reducer's `lastEventMs !== null`
 * (or the {@link isStreamSubscribed} selector). The remaining fields
 * are write-only telemetry consumed by the reducer for buffer
 * accounting and the stuck-stream watchdog.
 */
export interface StreamingState {
    agentId: string | null;
    bufferSize: number; // Number of events buffered
    lastEventTime: number;
}

/**
 * Shared logging callback passed into hooks and flows.
 * Implementations append a tagged line to the launch-log document.
 */
export type LogFn = (tag: string, text: string, level?: "info" | "error" | "warn") => void;

/**
 * Runtime configuration for agent pane controls.
 * Stored in block metadata as "agent:runtime".
 * Applied as CLI flags on each turn (between --resume spawns).
 */
export type PermissionMode = "bypass" | "auto" | "acceptEdits" | "plan" | "default";
export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface AgentRuntimeConfig {
    permissionMode: PermissionMode;
    // Provider-scoped model string (a value from the active provider's
    // `models` list). `ModelChoice` stays as the Claude-local alias type.
    model: string;
    effort: EffortLevel;
}

export const DEFAULT_RUNTIME_CONFIG: AgentRuntimeConfig = {
    permissionMode: "bypass",
    // Sonnet at high effort — faster default for routine/conversational turns.
    // Use the model picker or /model opus to escalate to Opus for complex work.
    model: "sonnet",
    effort: "high",
};

/**
 * Tool icon mapping
 */
export const TOOL_ICONS: Record<string, string> = {
    Read: "📖",
    Edit: "✏️",
    Write: "📝",
    Bash: "🔧",
    Grep: "🔍",
    Glob: "📁",
    Task: "🛠️",
    Agent: "🤖",
    WebSearch: "🌐",
    web_search: "🌐",
    WebFetch: "🌐",
    web_fetch: "🌐",
    Other: "🛠️",
};

/**
 * Status icon mapping
 */
export const STATUS_ICONS: Record<string, string> = {
    running: "⏳",
    success: "✓",
    failed: "✗",
    canceled: "⏹",
};

/**
 * Agent message icon mapping
 */
export const AGENT_MESSAGE_ICONS: Record<string, string> = {
    mux: "📨", // Async mailbox
    ject: "⚡", // Terminal injection
};

/**
 * Direction icon mapping
 */
export const DIRECTION_ICONS: Record<string, string> = {
    incoming: "📥",
    outgoing: "📤",
};

/**
 * Jekt tier (sensitivity) icon mapping
 */
export const JEKT_TIER_ICONS: Record<JektTier, string> = {
    info: "ℹ️",
    coord: "🔗",
    sensitive: "⚠️",
};

/**
 * Jekt delivery-tier icon mapping
 */
export const JEKT_DELIVERY_ICONS: Record<JektDeliveryTier, string> = {
    host: "🏠",
    lan: "🛰️",
    wan: "☁️",
};
