// Copyright 2025-2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0


pub mod agent_color;
pub mod agent_config;
pub mod agent_session;
pub mod blockcontroller;
pub mod bundle_export;
pub mod bundle_import;
pub mod bundle_validate;
pub mod dock_snapshot;
pub mod pending_background_pids;
pub mod mcp_probe;
pub mod mcp_seed;
/// Phase E.4.B Phase 4 — pure layout-tree helpers (Rust port of layoutTree.ts).
pub mod layout;
pub mod providers;
pub mod model_catalog;
pub mod config_watcher_fs;
pub mod editor_file_watcher;
pub mod fs_watch;
pub mod media_file_watcher;
pub mod native_memory_drift;
pub mod native_memory_retention;
pub mod ijson;
pub mod docsite;
pub mod eventbus;
pub mod agent_seed;
pub mod history;
pub mod skill_seed;
pub mod lan_discovery;
pub mod lsp;
pub mod messagebus;
pub mod oref;
pub mod process_tracker;
pub mod reactive;
pub mod rpc;
pub mod rpc_types;
pub mod schema;
pub mod service;
pub mod session_archive;
pub mod session_backfill;
pub mod shellexec;
pub mod transcript_backfill;
pub mod shellintegration;
pub mod sysinfo;
pub mod storage;
pub mod subagent_watcher;
pub mod userinput;
pub mod text_encoding;
pub mod base;
pub mod obj;
pub mod wconfig;
pub mod wcore;
pub mod wps;
pub mod osc_extractor;
pub mod tool_store;
pub mod container;
pub mod cron;
pub mod shell_node;

pub use oref::ORef;
