// Copyright 2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

/**
 * AmbientNarrationBlock — a line AgentMux wrote about its own action, rendered
 * in-flow in the agent's prose styling with a small trailing `ambient` tag.
 *
 * ON THE TAG. The line reads as the agent talking; it is not. The model did not
 * write it and the CLI transcript does not contain it, so read back later — by a
 * user, or by an agent debugging its own conversation — an unmarked line is
 * something the model appears to have claimed. The tag is what keeps that from
 * being true. It sits at the END of the text (inline, so it wraps with it) and is
 * deliberately quiet, but it is not optional: removing it is a decision about
 * transcript honesty, not a styling tweak.
 *
 * Spec: docs/specs/SPEC_AMBIENT_NARRATION_INLINE_AGENT_VOICE_2026_09_24.md.
 */

import { Show, createMemo, type JSX } from "solid-js";

import { useTick } from "@/app/hook/useTick";
import { formatExactTime, formatTimeAgo } from "@/util/format-time";
import { useNodePeek } from "../hooks/useNodePeek";
import type { AmbientNarrationNode } from "../types";
import { PeekOverlay } from "./PeekOverlay";
import "./AmbientNarrationBlock.scss";

export const AMBIENT_TAG_LABEL = "ambient";
export const AMBIENT_TAG_TITLE = "Generated by AgentMux, not by the model";

interface AmbientNarrationBlockProps {
    node: AmbientNarrationNode;
}

export const AmbientNarrationBlock = (props: AmbientNarrationBlockProps): JSX.Element => {
    // Don't destructure `node` — see MarkdownBlock for why.
    const peekTick = useTick(1000);
    const { isPeeking, rowEl: peekRowEl, setRowEl: setPeekRowEl, handlePeekEnter, handlePeekLeave } = useNodePeek();
    const peekTimeText = createMemo(() => {
        if (!isPeeking()) return null;
        peekTick();
        return `${formatExactTime(props.node.timestamp)} · ${formatTimeAgo(props.node.timestamp)}`;
    });

    return (
        <div
            ref={setPeekRowEl}
            class="agent-markdown-peek-anchor"
            onMouseEnter={handlePeekEnter}
            onMouseLeave={handlePeekLeave}
        >
            <div class="agent-markdown-block agent-ambient-narration" data-kind={props.node.kind}>
                <span class="agent-ambient-narration-text">{props.node.text}</span>
                {/* A real space, not margin: the tag must wrap with the text and
                    survive select-and-copy as "... ambient". */}
                {" "}
                <span class="agent-ambient-narration-tag" title={AMBIENT_TAG_TITLE}>
                    {AMBIENT_TAG_LABEL}
                </span>
            </div>
            <PeekOverlay show={isPeeking()} rowEl={peekRowEl}>
                <Show when={peekTimeText()}>
                    <div class="agent-node-peek-tooltip-meta">{peekTimeText()}</div>
                </Show>
                <div class="agent-node-peek-tooltip-meta">
                    AgentMux ambient narration ({props.node.kind}) — not written by the model
                </div>
            </PeekOverlay>
        </div>
    );
};
