// Copyright 2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0
//
// Unit tests for check-file-sizes.mjs.

import { describe, expect, it } from "vitest";
import {
    compare,
    countLines,
    formatBaseline,
    isGenerated,
    isSourcePath,
    lowered,
    parseBaseline,
} from "./check-file-sizes.mjs";

describe("isSourcePath", () => {
    it("takes Rust and TS/JS source", () => {
        for (const p of [
            "crates/srv/src/backend/storage/agents.rs",
            "frontend/app/view/agent/agent-view.tsx",
            "frontend/app/view/swarm/swarm-model.ts",
            "scripts/check-comment-hygiene.mjs",
            "prettier.config.cjs",
        ]) {
            expect(isSourcePath(p), p).toBe(true);
        }
    });

    it("skips tests, by name and by directory", () => {
        for (const p of [
            "frontend/app/store/agent-pane-state/reducer.test.ts",
            "frontend/app/x.spec.tsx",
            "frontend/app/store/agent-document/reducer.bench.ts",
            "scripts/check-ui-primitives.test.mjs",
            "crates/srv/src/server/tests.rs",
            "crates/srv/src/backend/fs_ops/jobs_tests.rs",
            "crates/srv/src/backend/storage/filestore/tests_atomic.rs",
            "crates/srv/src/test_support.rs",
            "crates/srv/src/server/tests/reactive/foo.rs",
            "crates/srv/tests/integration.rs",
            "frontend/app/notification/sound/__tests__/x.ts",
            "test/e2e/harness.ts",
            "frontend/test/replay/loader.ts",
        ]) {
            expect(isSourcePath(p), p).toBe(false);
        }
    });

    it("skips fixtures, snapshots, bindings and non-code", () => {
        for (const p of [
            "scripts/test-fixtures/gen-docs-index/fixtures.mjs",
            "frontend/app/view/agent/components/tool-renderers/websearch-fixture.ts",
            "frontend/app/__snapshots__/x.ts",
            "frontend/types/rpc/AgentDefinition.ts",
            "frontend/types/srv-types.d.ts",
            "package-lock.json",
            "Cargo.lock",
            "frontend/app/view/agent/styles/_document-nodes.scss",
            "docs/specs/INDEX.md",
        ]) {
            expect(isSourcePath(p), p).toBe(false);
        }
    });

    it("does not mistake a name that merely contains 'test' for a test", () => {
        expect(isSourcePath("frontend/app/view/agent/status/test-progress.ts")).toBe(true);
        expect(isSourcePath("crates/srv/src/latest.rs")).toBe(true);
    });
});

describe("isGenerated", () => {
    it("reads the marker from the head of the file only", () => {
        expect(isGenerated(Buffer.from("// @generated by gen-splash-font.py\nfn x() {}\n"))).toBe(true);
        expect(isGenerated(Buffer.from("// DO NOT EDIT\n"))).toBe(true);
        expect(isGenerated(Buffer.from("x".repeat(2000) + "\n// @generated\n"))).toBe(false);
        expect(isGenerated(Buffer.from("fn main() {}\n"))).toBe(false);
    });
});

describe("countLines", () => {
    it("counts newlines, plus a last line without one", () => {
        expect(countLines(Buffer.from(""))).toBe(0);
        expect(countLines(Buffer.from("a\n"))).toBe(1);
        expect(countLines(Buffer.from("a\nb"))).toBe(2);
        expect(countLines(Buffer.from("a\r\nb\r\n"))).toBe(2);
        expect(countLines(Buffer.from("\n\n\n"))).toBe(3);
    });
});

describe("baseline file", () => {
    it("round-trips, sorted by path, with comments ignored", () => {
        const text = formatBaseline(
            new Map([
                ["b.rs", 1600],
                ["a.ts", 2000],
            ])
        );
        expect(text.split("\n").filter((l) => l && !l.startsWith("#"))).toEqual(["2000 a.ts", "1600 b.rs"]);
        expect([...parseBaseline(text)]).toEqual([
            ["a.ts", 2000],
            ["b.rs", 1600],
        ]);
    });

    it("rejects a malformed line, naming it", () => {
        expect(() => parseBaseline("# ok\n1600 a.rs\nnot a line\n")).toThrow(/:3: expected/);
    });
});

describe("compare", () => {
    const baseline = new Map([
        ["big.rs", 2000],
        ["shrunk.ts", 1800],
        ["deleted.ts", 1700],
    ]);

    it("passes when every listed file is at its number and nothing else is over", () => {
        const sizes = new Map([
            ["big.rs", 2000],
            ["shrunk.ts", 1800],
            ["deleted.ts", 1700],
            ["small.ts", 1500],
        ]);
        expect(compare(sizes, baseline, 1500)).toEqual({ grew: [], added: [], shrank: [], gone: [] });
    });

    it("reports growth, a new file over the limit, a shrink and a removal", () => {
        const sizes = new Map([
            ["big.rs", 2001],
            ["shrunk.ts", 1790],
            ["new.tsx", 1501],
            ["small.ts", 1500],
        ]);
        expect(compare(sizes, baseline, 1500)).toEqual({
            grew: [{ path: "big.rs", now: 2001, allowed: 2000 }],
            added: [{ path: "new.tsx", now: 1501 }],
            shrank: [{ path: "shrunk.ts", now: 1790, allowed: 1800 }],
            gone: [{ path: "deleted.ts", allowed: 1700 }],
        });
    });

    it("treats a listed file under the limit as a shrink, not a pass", () => {
        const { shrank } = compare(new Map([["big.rs", 900]]), new Map([["big.rs", 2000]]), 1500);
        expect(shrank).toEqual([{ path: "big.rs", now: 900, allowed: 2000 }]);
    });
});

describe("lowered (--update)", () => {
    it("lowers numbers and drops files that are gone or under the limit", () => {
        const baseline = new Map([
            ["big.rs", 2000],
            ["shrunk.ts", 1800],
            ["split.ts", 1700],
            ["deleted.ts", 1600],
        ]);
        const sizes = new Map([
            ["big.rs", 2000],
            ["shrunk.ts", 1790],
            ["split.ts", 1200],
        ]);
        expect([...lowered(sizes, baseline, 1500)]).toEqual([
            ["big.rs", 2000],
            ["shrunk.ts", 1790],
        ]);
    });

    it("never raises a number or adds a file", () => {
        const sizes = new Map([
            ["big.rs", 2100],
            ["new.ts", 1900],
        ]);
        expect([...lowered(sizes, new Map([["big.rs", 2000]]), 1500)]).toEqual([["big.rs", 2000]]);
    });
});
