#!/usr/bin/env bash
# gen-docs-index.sh — regenerate the machine-maintained half of docs/specs/INDEX.md.
#
# docs/specs/PLAN_DOCS_CLEANUP_EXECUTION_2026_09_01.md (Batch D)
# docs/specs/SPEC_DOCS_LIFECYCLE_HARDENING_2026_08_03.md (Phase 3)
#
# WHY GENERATED, AND WHY GROUPED BY STATUS
#
# The curated index above the marker is genuinely useful and stays hand-written:
# it answers "where do I start for subsystem X", which no generator can.
#
# What it cannot do is keep up. Measured 2026-09-01: it lists 77 of 730 specs,
# and 165 specs added in the previous 30 days are absent from it. Nothing was
# broken — every curated entry still resolves — it is simply being outrun at
# ~165 new docs/month. That is the failure Phase 3 named: "the tool that's
# supposed to help an agent find the current doc is itself an instance of the
# problem it's meant to solve."
#
# Grouping by Status rather than subsystem is deliberate. Subsystem grouping
# needs human judgement (the 308 distinct filename prefixes do not map to
# subsystems), so a generator doing it would produce noise. Status answers the
# question a reader actually arrives with — "is this real, or someone's idea?" —
# and it is now an enforced closed enum (scripts/check-doc-status.sh), so it can
# be trusted enough to sort on.
#
# Usage:
#   bash scripts/gen-docs-index.sh          # rewrite the generated section
#   bash scripts/gen-docs-index.sh --check  # fail if it would change (CI)

set -uo pipefail

INDEX="docs/specs/INDEX.md"
BEGIN="<!-- BEGIN GENERATED INDEX — edit scripts/gen-docs-index.sh, not this section -->"
END="<!-- END GENERATED INDEX -->"

check_only=0
[ "${1:-}" = "--check" ] && check_only=1

# ── Build the generated section ─────────────────────────────────────────────
#
# Single pass over the tree. An earlier version looped the whole directory once
# per status word — 730 files x 8 statuses, ~5,800 process spawns — which took
# over two minutes on Windows. Now each file is read once into a status->rows
# map, which is ~730 spawns and seconds.
build() {
    declare -A ROWS
    for f in docs/specs/*.md; do
        b=$(basename "$f")
        case "$b" in INDEX.md|README.md) continue ;; esac

        # One read per file; pull the Status word and the H1 together.
        head -40 "$f" > "$scratch" 2>/dev/null || continue
        w=$(grep -m1 -i '^\*\*Status:\*\*' "$scratch" 2>/dev/null             | sed 's/^\*\*Status:\*\*[[:space:]]*//I'             | awk '{print tolower($1)}' | sed 's/[^a-z]//g')
        title=$(grep -m1 '^# ' "$scratch" 2>/dev/null | sed 's/^# *//' | tr -d '|')
        [ -z "$title" ] && title="$b"
        [ -z "$w" ] && w="__none__"

        ROWS["$w"]="${ROWS[$w]:-}| [\`${b%.md}\`](${b}) | ${title} |
"
    done

    printf '%s
' "$BEGIN"
    printf '
## All specs by status

'
    printf 'Generated by `scripts/gen-docs-index.sh` — do not hand-edit. Covers
'
    printf 'every file in `docs/specs/`, which the curated sections above
'
    printf 'deliberately do not.
'

    for st in implemented active proposed draft living historical superseded; do
        rows="${ROWS[$st]:-}"
        [ -z "$rows" ] && continue
        n=$(printf '%s' "$rows" | grep -c '^|')
        printf '
### %s (%s)

' "$st" "$n"
        printf '| Spec | Title |
|---|---|
'
        printf '%s' "$rows"
    done

    # Specs with no Status line at all — surfaced, not dropped. Hiding them
    # would make the index look complete while omitting a sixth of the tree.
    rows="${ROWS[__none__]:-}"
    if [ -n "$rows" ]; then
        n=$(printf '%s' "$rows" | grep -c '^|')
        printf '
### no status line (%s)

' "$n"
        printf 'Predate the closed vocabulary. Not a backlog to bulk-restamp —
'
        printf 'an unverified restamp turns "unknown" into "confidently wrong".
'
        printf 'Fix one when you touch it and know its real state.

'
        printf '| Spec | Title |
|---|---|
'
        printf '%s' "$rows"
    fi

    printf '
%s
' "$END"
}

[ -f "$INDEX" ] || { echo "gen-docs-index: $INDEX not found"; exit 1; }

scratch=$(mktemp)
trap 'rm -f "$scratch"' EXIT

# ── Splice into the index, preserving everything above the marker ───────────
tmp=$(mktemp)
if grep -qF "$BEGIN" "$INDEX"; then
    sed "/$(printf '%s' "$BEGIN" | sed 's/[]\/$*.^[]/\\&/g')/,\$d" "$INDEX" > "$tmp"
else
    cat "$INDEX" > "$tmp"
    printf '\n---\n\n' >> "$tmp"
fi
build >> "$tmp"

if [ "$check_only" -eq 1 ]; then
    if diff -q "$INDEX" "$tmp" >/dev/null 2>&1; then
        rm -f "$tmp"
        echo "gen-docs-index: INDEX.md is current."
        exit 0
    fi
    echo "gen-docs-index: INDEX.md is STALE."
    echo "  A spec was added, removed, or had its Status changed without"
    echo "  regenerating the index. Run: bash scripts/gen-docs-index.sh"
    rm -f "$tmp"
    exit 1
fi

mv "$tmp" "$INDEX"
echo "gen-docs-index: regenerated $INDEX"
