#!/usr/bin/env bash
# gen-docs-index.sh — regenerate the machine-maintained half of docs/specs/INDEX.md.
#
# docs/specs/PLAN_DOCS_CLEANUP_EXECUTION_2026_09_01.md (Batch D)
# docs/specs/SPEC_DOCS_LIFECYCLE_HARDENING_2026_08_03.md (Phase 3)
#
# WHY GENERATED, AND WHY GROUPED BY STATUS
#
# The curated index above the marker is genuinely useful and stays hand-written:
# it answers "where do I start for subsystem X", which no generator can.
#
# What it cannot do is keep up. Measured 2026-09-01: it lists 77 of 730 specs,
# and 165 specs added in the previous 30 days are absent from it. Nothing was
# broken — every curated entry still resolves — it is simply being outrun at
# ~165 new docs/month. That is the failure Phase 3 named: "the tool that's
# supposed to help an agent find the current doc is itself an instance of the
# problem it's meant to solve."
#
# Grouping by Status rather than subsystem is deliberate. Subsystem grouping
# needs human judgement (the 308 distinct filename prefixes do not map to
# subsystems), so a generator doing it would produce noise. Status answers the
# question a reader actually arrives with — "is this real, or someone's idea?" —
# and it is now an enforced closed enum (scripts/check-doc-status.sh), so it can
# be trusted enough to sort on.
#
# Usage:
#   bash scripts/gen-docs-index.sh          # rewrite the generated section
#   bash scripts/gen-docs-index.sh --check  # fail if it would change (CI)

set -uo pipefail

INDEX="docs/specs/INDEX.md"
BEGIN="<!-- BEGIN GENERATED INDEX — edit scripts/gen-docs-index.sh, not this section -->"
END="<!-- END GENERATED INDEX -->"

check_only=0
[ "${1:-}" = "--check" ] && check_only=1

# ── Build the generated section ─────────────────────────────────────────────
#
# Single pass over the tree. An earlier version looped the whole directory once
# per status word — 730 files x 8 statuses, ~5,800 process spawns — which took
# over two minutes on Windows. Now each file is read once into a status->rows
# map, which is ~730 spawns and seconds.
build() {
    declare -A ROWS
    local total=0 shown=0
    for f in docs/specs/*.md; do
        b=$(basename "$f")
        case "$b" in INDEX.md|README.md) continue ;; esac
        total=$((total + 1))

        # One read per file; pull the Status word and the H1 together.
        # Deliberately no `|| continue` here: an unreadable file must still get
        # a row (it falls through to __none__ with the filename as its title)
        # rather than vanishing. Every path out of this loop ends in a row, so
        # the completeness assertion at the bottom of build() is meaningful.
        head -40 "$f" > "$scratch" 2>/dev/null || :
        w=$(grep -m1 -i '^\*\*Status:\*\*' "$scratch" 2>/dev/null             | sed 's/^\*\*Status:\*\*[[:space:]]*//I'             | awk '{print tolower($1)}' | sed 's/[^a-z]//g')
        title=$(grep -m1 '^# ' "$scratch" 2>/dev/null | sed 's/^# *//' | tr -d '|')
        [ -z "$title" ] && title="$b"
        [ -z "$w" ] && w="__none__"

        ROWS["$w"]="${ROWS[$w]:-}| [\`${b%.md}\`](${b}) | ${title} |
"
    done

    printf '%s
' "$BEGIN"
    printf '
## All specs by status

'
    printf 'Generated by `scripts/gen-docs-index.sh` — do not hand-edit. Covers
'
    printf 'every spec directly in `docs/specs/`, which the curated sections
'
    printf 'above deliberately do not.
'
    printf '
`archive/` is excluded on purpose — it means "not worth reading unless you
'
    printf 'are doing history". Everything else is here; the completeness
'
    printf 'assertion in the generator fails the build rather than emit a
'
    printf 'partial list.
'

    for st in implemented active proposed draft living historical superseded; do
        rows="${ROWS[$st]:-}"
        [ -z "$rows" ] && continue
        n=$(printf '%s' "$rows" | grep -c '^|')
        shown=$((shown + n))
        printf '
### %s (%s)

' "$st" "$n"
        printf '| Spec | Title |
|---|---|
'
        printf '%s' "$rows"
    done

    # Specs with no Status line at all — surfaced, not dropped. Hiding them
    # would make the index look complete while omitting a sixth of the tree.
    rows="${ROWS[__none__]:-}"
    if [ -n "$rows" ]; then
        n=$(printf '%s' "$rows" | grep -c '^|')
        shown=$((shown + n))
        printf '
### no status line (%s)

' "$n"
        printf 'Predate the closed vocabulary. Not a backlog to bulk-restamp —
'
        printf 'an unverified restamp turns "unknown" into "confidently wrong".
'
        printf 'Fix one when you touch it and know its real state.

'
        printf '| Spec | Title |
|---|---|
'
        printf '%s' "$rows"
    fi

    # Status line present, but its first word is outside the closed enum.
    #
    # An earlier version of this script printed ONLY the seven canonical
    # buckets, so every one of these landed in a ROWS key the print loop never
    # iterated and vanished from the index with no trace — 189 specs (26% of
    # the tree) silently absent, while the header above claimed to cover every
    # file. That is the exact failure this batch exists to fix, reintroduced by
    # the fix itself. --check could not catch it: it only diffs a re-run of the
    # same logic, so a stable bug stays green forever.
    noncanon=""
    for st in $(printf '%s\n' "${!ROWS[@]}" | sort); do
        case " implemented active proposed draft living historical superseded __none__ " in
            *" $st "*) continue ;;
        esac
        noncanon="$noncanon $st"
    done

    if [ -n "$noncanon" ]; then
        n=0
        for st in $noncanon; do
            n=$((n + $(printf '%s' "${ROWS[$st]}" | grep -c '^|')))
        done
        shown=$((shown + n))
        printf '
### non-canonical status (%s)
' "$n"
        printf '
These carry a `**Status:**` line whose first word is not in the closed enum
'
        printf '(`docs/specs/README.md`). Grouped by the word actually found, so the
'
        printf 'real state is visible rather than guessed at. `check-doc-status.sh`
'
        printf 'requires a fix the next time one of these is edited; as with the
'
        printf 'section above, do not bulk-restamp them.
'
        for st in $noncanon; do
            printf '
**`%s`**

' "$st"
            printf '| Spec | Title |
|---|---|
'
            printf '%s' "${ROWS[$st]}"
        done
    fi

    # Completeness assertion — the check that would have caught the bug above,
    # and the reason it cannot come back. Every candidate file must be
    # accounted for by exactly one emitted row; if not, the index would be
    # claiming a coverage it does not have, so refuse to produce it at all.
    if [ "$shown" -ne "$total" ]; then
        echo "gen-docs-index: FATAL — emitted $shown rows for $total specs;" >&2
        echo "  $((total - shown)) unaccounted for. The index would be incomplete" >&2
        echo "  while claiming to cover every file; refusing to write it." >&2
        return 3
    fi

    printf '
%s
' "$END"
}

[ -f "$INDEX" ] || { echo "gen-docs-index: $INDEX not found"; exit 1; }

scratch=$(mktemp)
trap 'rm -f "$scratch"' EXIT

# ── Splice into the index, preserving everything above the marker ───────────
tmp=$(mktemp)
if grep -qF "$BEGIN" "$INDEX"; then
    sed "/$(printf '%s' "$BEGIN" | sed 's/[]\/$*.^[]/\\&/g')/,\$d" "$INDEX" > "$tmp"
else
    cat "$INDEX" > "$tmp"
    printf '\n---\n\n' >> "$tmp"
fi
if ! build >> "$tmp"; then
    # The completeness assertion tripped. Leave INDEX.md exactly as it was:
    # a stale index is recoverable, a confidently-incomplete one is not.
    rm -f "$tmp"
    exit 3
fi

if [ "$check_only" -eq 1 ]; then
    if diff -q "$INDEX" "$tmp" >/dev/null 2>&1; then
        rm -f "$tmp"
        echo "gen-docs-index: INDEX.md is current."
        exit 0
    fi
    echo "gen-docs-index: INDEX.md is STALE."
    echo "  A spec was added, removed, or had its Status changed without"
    echo "  regenerating the index. Run: bash scripts/gen-docs-index.sh"
    rm -f "$tmp"
    exit 1
fi

mv "$tmp" "$INDEX"
echo "gen-docs-index: regenerated $INDEX"
