#!/usr/bin/env bash
# Installs the AppArmor exception that lets AgentMux's CEF host create
# unprivileged user namespaces (the kernel-namespace sandbox CEF relies on
# on Linux — see agentmux-cef/src/app/mod.rs's Linux sandbox branch and
# docs/specs/SPEC_LINUX_SANDBOX_APPARMOR_USERNS_2026_08_23.md).
#
# Run via `pkexec` from agentmux-cef/src/linux_sandbox.rs's
# run_pkexec_fix(), which writes the actual profile content (generated by
# build_apparmor_profile(), the single source of truth — not duplicated
# here) to a temp file and passes its path as $1. This script's only job
# is the mechanical, privileged part: copy it into place and reload
# AppArmor. It intentionally does NOT construct the profile text itself.
#
# Usage: pkexec bash install-userns-apparmor-fix.sh <path-to-profile-file>

set -euo pipefail

PROFILE_SRC="${1:?usage: $0 <path-to-generated-profile-file>}"
PROFILE_DST="/etc/apparmor.d/agentmux-userns"

if [ ! -f "$PROFILE_SRC" ]; then
    echo "ERROR: profile source file not found: $PROFILE_SRC" >&2
    exit 1
fi

if ! command -v apparmor_parser >/dev/null 2>&1; then
    echo "ERROR: apparmor_parser not found — this system doesn't appear to" >&2
    echo "       have AppArmor installed/active. If the sandbox is blocked" >&2
    echo "       by something else, this fix won't help; use" >&2
    echo "       AGENTMUX_UNSAFE_NOSANDBOX=1 as a fallback." >&2
    exit 1
fi

cp "$PROFILE_SRC" "$PROFILE_DST"
chmod 0644 "$PROFILE_DST"
apparmor_parser -r "$PROFILE_DST"

echo "Installed and reloaded AppArmor profile: $PROFILE_DST"
