from PIL import ImageFont, ImageDraw, Image
import sys

TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
SIZE = 17  # px; tuned for the ~312px Linux card / scaled down elsewhere
font = ImageFont.truetype(TTF, SIZE)
asc, desc = font.getmetrics()
H = asc + desc
# monospace advance: width of a representative glyph
adv = round(font.getlength("M"))
W = adv
first, last = 0x20, 0x7E
n = last - first + 1
data = bytearray()
for code in range(first, last+1):
    ch = chr(code)
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    # draw at baseline = ascent; PIL anchor "la" draws top-left at (x,y)
    d.text((0, 0), ch, fill=255, font=font)
    px = img.load()
    for y in range(H):
        for x in range(W):
            data.append(px[x, y])
out = []
out.append("// @generated by scripts/dev/gen-splash-font.py from DejaVu Sans Mono")
out.append("// (Bitstream Vera / DejaVu license — permissive). Grayscale coverage")
out.append("// (0=transparent, 255=opaque), %d glyphs x %dx%d, ASCII 0x20..=0x7E." % (n, W, H))
out.append("// Regenerate: python3 scripts/dev/gen-splash-font.py > agentmux-launcher/src/splash_font.rs")
out.append("")
out.append("pub const GLYPH_W: usize = %d;" % W)
out.append("pub const GLYPH_H: usize = %d;" % H)
out.append("pub const FIRST: u8 = 0x%02X;" % first)
out.append("pub const LAST: u8 = 0x%02X;" % last)
out.append("/// Flat coverage: glyph g, pixel (x,y) at [(g*GLYPH_H + y)*GLYPH_W + x].")
out.append("#[rustfmt::skip]")
out.append("pub static COVERAGE: [u8; %d] = [" % len(data))
# emit 32 bytes per line
line = []
for i, b in enumerate(data):
    line.append(str(b))
    if len(line) == 32:
        out.append("    " + ",".join(line) + ",")
        line = []
if line:
    out.append("    " + ",".join(line) + ",")
out.append("];")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("font: W=%d H=%d glyphs=%d bytes=%d\n" % (W, H, n, len(data)))
