// Copyright 2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

// OS notification Router RPCs — docs/specs/SPEC_OS_NOTIFICATIONS_SYSTEM_2026_09_24.md
// §3.3, agentmux-srv/src/server/notify_handlers.rs. Types are generated by ts-rs.

import { RpcClient } from "../rpc-client";
import type { NotifyAckParams } from "@/types/rpc/NotifyAckParams";
import type { NotifyAckResult } from "@/types/rpc/NotifyAckResult";
import type { NotifyEmitParams } from "@/types/rpc/NotifyEmitParams";
import type { NotifyFocusParams } from "@/types/rpc/NotifyFocusParams";
import type { NotifyOk } from "@/types/rpc/NotifyOk";
import type { NotifyTakeActivationParams } from "@/types/rpc/NotifyTakeActivationParams";
import type { NotifyTakeActivationResult } from "@/types/rpc/NotifyTakeActivationResult";

export const NotifyApi = {
    NotifyEmitCommand(client: RpcClient, data: NotifyEmitParams, opts?: RpcOpts): Promise<NotifyOk> {
        return client.rpcCall("notify.emit", data, opts);
    },
    NotifyFocusCommand(client: RpcClient, data: NotifyFocusParams, opts?: RpcOpts): Promise<NotifyOk> {
        return client.rpcCall("notify.focus", data, opts);
    },
    NotifyAckCommand(client: RpcClient, data: NotifyAckParams, opts?: RpcOpts): Promise<NotifyAckResult> {
        return client.rpcCall("notify.ack", data, opts);
    },
    NotifyTestCommand(client: RpcClient, opts?: RpcOpts): Promise<NotifyOk> {
        return client.rpcCall("notify.test", {}, opts);
    },
    NotifyTakeActivationCommand(
        client: RpcClient,
        data?: NotifyTakeActivationParams,
        opts?: RpcOpts
    ): Promise<NotifyTakeActivationResult> {
        return client.rpcCall("notify.takeactivation", data ?? {}, opts);
    },
};
