// Copyright 2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

// The cloud presence publisher: its status and "Publish now"
// (crates/srv/src/server/app_api/presence.rs). Types are generated by ts-rs.

import { RpcClient } from "../rpc-client";
import type { PresencePublishNowResult } from "@/types/rpc/PresencePublishNowResult";
import type { PresenceStatusResult } from "@/types/rpc/PresenceStatusResult";

export type { PresenceState } from "@/types/rpc/PresenceState";
export type { PresenceStatusResult } from "@/types/rpc/PresenceStatusResult";

export const PresenceApi = {
    /** Whether this install's record reaches the cloud, and why not. Fails
     *  until the publisher has a status (or where none runs). */
    PresenceStatusCommand(client: RpcClient, opts?: RpcOpts): Promise<PresenceStatusResult> {
        return client.rpcCall("presence.status", {}, opts);
    },
    /** Forget the backoff and try at once. */
    PresencePublishNowCommand(client: RpcClient, opts?: RpcOpts): Promise<PresencePublishNowResult> {
        return client.rpcCall("presence.publish-now", {}, opts);
    },
};
