// Copyright 2026, AgentMux Corp.
// SPDX-License-Identifier: Apache-2.0

// Tower, the read-only task manager pane (crates/srv/src/server/app_api/tower_pane.rs).
// Types are generated by ts-rs.

import type { TowerSampleReq } from "@/types/rpc/TowerSampleReq";
import type { TowerSnapshot } from "@/types/rpc/TowerSnapshot";
import { RpcClient } from "../rpc-client";

export type { TowerHost } from "@/types/rpc/TowerHost";
export type { TowerProcess } from "@/types/rpc/TowerProcess";
export type { TowerProcessRole } from "@/types/rpc/TowerProcessRole";
export type { TowerSnapshot } from "@/types/rpc/TowerSnapshot";
export type { TowerTask } from "@/types/rpc/TowerTask";
export type { TowerTaskKind } from "@/types/rpc/TowerTaskKind";

export const TowerApi = {
    /** CPU and memory per task, and with `host` every process on the machine. */
    TowerSampleCommand(client: RpcClient, data: TowerSampleReq, opts?: RpcOpts): Promise<TowerSnapshot> {
        return client.rpcCall("tower.sample", data, opts);
    },
};
