github.com:
    users:
        a5af:
            oauth_token: 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
        AgentX-asaf:
            oauth_token: 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
        Agent1-asaf:
            oauth_token: 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
        Agent2-asaf:
            oauth_token: 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
        Agent3-asaf:
            oauth_token: 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
        Agent4-asaf:
            oauth_token: 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
        Agent5-asaf:
            oauth_token: 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
    git_protocol: https
    user: AgentX-asaf
    oauth_token: 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
